// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: auth/ack.proto

package pb_auth

import (
	pb_common "github.com/gogu-x/gogs/pb/pb_common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginGameAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          pb_common.ErrCode      `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginGameAck) Reset() {
	*x = LoginGameAck{}
	mi := &file_auth_ack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginGameAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGameAck) ProtoMessage() {}

func (x *LoginGameAck) ProtoReflect() protoreflect.Message {
	mi := &file_auth_ack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginGameAck.ProtoReflect.Descriptor instead.
func (*LoginGameAck) Descriptor() ([]byte, []int) {
	return file_auth_ack_proto_rawDescGZIP(), []int{0}
}

func (x *LoginGameAck) GetCode() pb_common.ErrCode {
	if x != nil {
		return x.Code
	}
	return pb_common.ErrCode(0)
}

func (x *LoginGameAck) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

var File_auth_ack_proto protoreflect.FileDescriptor

const file_auth_ack_proto_rawDesc = "" +
	"\n" +
	"\x0eauth/ack.proto\x1a\x12common/error.proto\">\n" +
	"\fLoginGameAck\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x0e2\b.ErrCodeR\x04code\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uidB#Z!github.com/gogu-x/gogs/pb/pb_authb\x06proto3"

var (
	file_auth_ack_proto_rawDescOnce sync.Once
	file_auth_ack_proto_rawDescData []byte
)

func file_auth_ack_proto_rawDescGZIP() []byte {
	file_auth_ack_proto_rawDescOnce.Do(func() {
		file_auth_ack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_ack_proto_rawDesc), len(file_auth_ack_proto_rawDesc)))
	})
	return file_auth_ack_proto_rawDescData
}

var file_auth_ack_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_auth_ack_proto_goTypes = []any{
	(*LoginGameAck)(nil),   // 0: LoginGameAck
	(pb_common.ErrCode)(0), // 1: ErrCode
}
var file_auth_ack_proto_depIdxs = []int32{
	1, // 0: LoginGameAck.code:type_name -> ErrCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auth_ack_proto_init() }
func file_auth_ack_proto_init() {
	if File_auth_ack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_ack_proto_rawDesc), len(file_auth_ack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_ack_proto_goTypes,
		DependencyIndexes: file_auth_ack_proto_depIdxs,
		MessageInfos:      file_auth_ack_proto_msgTypes,
	}.Build()
	File_auth_ack_proto = out.File
	file_auth_ack_proto_goTypes = nil
	file_auth_ack_proto_depIdxs = nil
}
