// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: cspb/gateway/struct.proto

package pb_gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用消息帧，Gate↔Game gRPC 传输单元
type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_cspb_gateway_struct_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_gateway_struct_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_cspb_gateway_struct_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ServerAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      uint32                 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerAccount) Reset() {
	*x = ServerAccount{}
	mi := &file_cspb_gateway_struct_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerAccount) ProtoMessage() {}

func (x *ServerAccount) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_gateway_struct_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerAccount.ProtoReflect.Descriptor instead.
func (*ServerAccount) Descriptor() ([]byte, []int) {
	return file_cspb_gateway_struct_proto_rawDescGZIP(), []int{1}
}

func (x *ServerAccount) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServerAccount) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

var File_cspb_gateway_struct_proto protoreflect.FileDescriptor

const file_cspb_gateway_struct_proto_rawDesc = "" +
	"\n" +
	"\x19cspb/gateway/struct.proto\"!\n" +
	"\x05Frame\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\">\n" +
	"\rServerAccount\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\rR\bserverId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid2'\n" +
	"\aGateway\x12\x1c\n" +
	"\x06Stream\x12\x06.Frame\x1a\x06.Frame(\x010\x01B+Z)github.com/gogu-x/gogs/pb/cspb/pb_gatewayb\x06proto3"

var (
	file_cspb_gateway_struct_proto_rawDescOnce sync.Once
	file_cspb_gateway_struct_proto_rawDescData []byte
)

func file_cspb_gateway_struct_proto_rawDescGZIP() []byte {
	file_cspb_gateway_struct_proto_rawDescOnce.Do(func() {
		file_cspb_gateway_struct_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cspb_gateway_struct_proto_rawDesc), len(file_cspb_gateway_struct_proto_rawDesc)))
	})
	return file_cspb_gateway_struct_proto_rawDescData
}

var file_cspb_gateway_struct_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cspb_gateway_struct_proto_goTypes = []any{
	(*Frame)(nil),         // 0: Frame
	(*ServerAccount)(nil), // 1: ServerAccount
}
var file_cspb_gateway_struct_proto_depIdxs = []int32{
	0, // 0: Gateway.Stream:input_type -> Frame
	0, // 1: Gateway.Stream:output_type -> Frame
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cspb_gateway_struct_proto_init() }
func file_cspb_gateway_struct_proto_init() {
	if File_cspb_gateway_struct_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cspb_gateway_struct_proto_rawDesc), len(file_cspb_gateway_struct_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cspb_gateway_struct_proto_goTypes,
		DependencyIndexes: file_cspb_gateway_struct_proto_depIdxs,
		MessageInfos:      file_cspb_gateway_struct_proto_msgTypes,
	}.Build()
	File_cspb_gateway_struct_proto = out.File
	file_cspb_gateway_struct_proto_goTypes = nil
	file_cspb_gateway_struct_proto_depIdxs = nil
}
