// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: gateway/gateway_req.proto

package protoGateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ServerId      int32                  `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_gateway_gateway_req_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_req_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_req_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LoginReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginReq) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type LogoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	mi := &file_gateway_gateway_req_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_req_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_req_proto_rawDescGZIP(), []int{1}
}

func (x *LogoutReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

var File_gateway_gateway_req_proto protoreflect.FileDescriptor

const file_gateway_gateway_req_proto_rawDesc = "" +
	"\n" +
	"\x19gateway/gateway_req.proto\"O\n" +
	"\bLoginReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\x05R\bserverId\"\x1d\n" +
	"\tLogoutReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uidB(Z&github.com/gogu-x/gogs/pb/protoGatewayb\x06proto3"

var (
	file_gateway_gateway_req_proto_rawDescOnce sync.Once
	file_gateway_gateway_req_proto_rawDescData []byte
)

func file_gateway_gateway_req_proto_rawDescGZIP() []byte {
	file_gateway_gateway_req_proto_rawDescOnce.Do(func() {
		file_gateway_gateway_req_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_gateway_req_proto_rawDesc), len(file_gateway_gateway_req_proto_rawDesc)))
	})
	return file_gateway_gateway_req_proto_rawDescData
}

var file_gateway_gateway_req_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gateway_gateway_req_proto_goTypes = []any{
	(*LoginReq)(nil),  // 0: LoginReq
	(*LogoutReq)(nil), // 1: LogoutReq
}
var file_gateway_gateway_req_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_gateway_req_proto_init() }
func file_gateway_gateway_req_proto_init() {
	if File_gateway_gateway_req_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_gateway_req_proto_rawDesc), len(file_gateway_gateway_req_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_gateway_req_proto_goTypes,
		DependencyIndexes: file_gateway_gateway_req_proto_depIdxs,
		MessageInfos:      file_gateway_gateway_req_proto_msgTypes,
	}.Build()
	File_gateway_gateway_req_proto = out.File
	file_gateway_gateway_req_proto_goTypes = nil
	file_gateway_gateway_req_proto_depIdxs = nil
}
