// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: gateway/gateway_internal.proto

package protoGateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SwitchMsg 通知 NatsActor 切换目标 serverID
type SwitchMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	NewAddr       string                 `protobuf:"bytes,2,opt,name=new_addr,json=newAddr,proto3" json:"new_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchMsg) Reset() {
	*x = SwitchMsg{}
	mi := &file_gateway_gateway_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchMsg) ProtoMessage() {}

func (x *SwitchMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchMsg.ProtoReflect.Descriptor instead.
func (*SwitchMsg) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_internal_proto_rawDescGZIP(), []int{0}
}

func (x *SwitchMsg) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *SwitchMsg) GetNewAddr() string {
	if x != nil {
		return x.NewAddr
	}
	return ""
}

// StreamMsg 包装发往 game 的消息帧
type StreamMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frame         *Frame                 `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMsg) Reset() {
	*x = StreamMsg{}
	mi := &file_gateway_gateway_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMsg) ProtoMessage() {}

func (x *StreamMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMsg.ProtoReflect.Descriptor instead.
func (*StreamMsg) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_internal_proto_rawDescGZIP(), []int{1}
}

func (x *StreamMsg) GetFrame() *Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

// CheckDeleteMsg 延迟确认 active 实例是否真的下线
type CheckDeleteMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	InstId        string                 `protobuf:"bytes,2,opt,name=inst_id,json=instId,proto3" json:"inst_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDeleteMsg) Reset() {
	*x = CheckDeleteMsg{}
	mi := &file_gateway_gateway_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDeleteMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDeleteMsg) ProtoMessage() {}

func (x *CheckDeleteMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDeleteMsg.ProtoReflect.Descriptor instead.
func (*CheckDeleteMsg) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_internal_proto_rawDescGZIP(), []int{2}
}

func (x *CheckDeleteMsg) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CheckDeleteMsg) GetInstId() string {
	if x != nil {
		return x.InstId
	}
	return ""
}

// ConnRegMsg ConnActor 上线时注册到 GateServer
type ConnRegMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        uint64                 `protobuf:"varint,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnRegMsg) Reset() {
	*x = ConnRegMsg{}
	mi := &file_gateway_gateway_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnRegMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnRegMsg) ProtoMessage() {}

func (x *ConnRegMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnRegMsg.ProtoReflect.Descriptor instead.
func (*ConnRegMsg) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_internal_proto_rawDescGZIP(), []int{3}
}

func (x *ConnRegMsg) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

// ConnUnregMsg ConnActor 下线时从 GateServer 注销
type ConnUnregMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        uint64                 `protobuf:"varint,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnUnregMsg) Reset() {
	*x = ConnUnregMsg{}
	mi := &file_gateway_gateway_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnUnregMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnUnregMsg) ProtoMessage() {}

func (x *ConnUnregMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnUnregMsg.ProtoReflect.Descriptor instead.
func (*ConnUnregMsg) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_internal_proto_rawDescGZIP(), []int{4}
}

func (x *ConnUnregMsg) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

// BroadcastMsg 向所有在线 ConnActor 广播消息
type BroadcastMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastMsg) Reset() {
	*x = BroadcastMsg{}
	mi := &file_gateway_gateway_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMsg) ProtoMessage() {}

func (x *BroadcastMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMsg.ProtoReflect.Descriptor instead.
func (*BroadcastMsg) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_internal_proto_rawDescGZIP(), []int{5}
}

func (x *BroadcastMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_gateway_gateway_internal_proto protoreflect.FileDescriptor

const file_gateway_gateway_internal_proto_rawDesc = "" +
	"\n" +
	"\x1egateway/gateway_internal.proto\x1a\x1cgateway/gateway_common.proto\"C\n" +
	"\tSwitchMsg\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x19\n" +
	"\bnew_addr\x18\x02 \x01(\tR\anewAddr\")\n" +
	"\tStreamMsg\x12\x1c\n" +
	"\x05frame\x18\x01 \x01(\v2\x06.FrameR\x05frame\"F\n" +
	"\x0eCheckDeleteMsg\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\ainst_id\x18\x02 \x01(\tR\x06instId\"%\n" +
	"\n" +
	"ConnRegMsg\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\x04R\x06connId\"'\n" +
	"\fConnUnregMsg\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\x04R\x06connId\"\"\n" +
	"\fBroadcastMsg\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04dataB(Z&github.com/gogu-x/gogs/pb/protoGatewayb\x06proto3"

var (
	file_gateway_gateway_internal_proto_rawDescOnce sync.Once
	file_gateway_gateway_internal_proto_rawDescData []byte
)

func file_gateway_gateway_internal_proto_rawDescGZIP() []byte {
	file_gateway_gateway_internal_proto_rawDescOnce.Do(func() {
		file_gateway_gateway_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_gateway_internal_proto_rawDesc), len(file_gateway_gateway_internal_proto_rawDesc)))
	})
	return file_gateway_gateway_internal_proto_rawDescData
}

var file_gateway_gateway_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gateway_gateway_internal_proto_goTypes = []any{
	(*SwitchMsg)(nil),      // 0: SwitchMsg
	(*StreamMsg)(nil),      // 1: StreamMsg
	(*CheckDeleteMsg)(nil), // 2: CheckDeleteMsg
	(*ConnRegMsg)(nil),     // 3: ConnRegMsg
	(*ConnUnregMsg)(nil),   // 4: ConnUnregMsg
	(*BroadcastMsg)(nil),   // 5: BroadcastMsg
	(*Frame)(nil),          // 6: Frame
}
var file_gateway_gateway_internal_proto_depIdxs = []int32{
	6, // 0: StreamMsg.frame:type_name -> Frame
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateway_gateway_internal_proto_init() }
func file_gateway_gateway_internal_proto_init() {
	if File_gateway_gateway_internal_proto != nil {
		return
	}
	file_gateway_gateway_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_gateway_internal_proto_rawDesc), len(file_gateway_gateway_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_gateway_internal_proto_goTypes,
		DependencyIndexes: file_gateway_gateway_internal_proto_depIdxs,
		MessageInfos:      file_gateway_gateway_internal_proto_msgTypes,
	}.Build()
	File_gateway_gateway_internal_proto = out.File
	file_gateway_gateway_internal_proto_goTypes = nil
	file_gateway_gateway_internal_proto_depIdxs = nil
}
