// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: gateway/gateway_common.proto

package protoGateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用消息帧，Gate↔Game gRPC 传输单元
type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ConnId        uint64                 `protobuf:"varint,4,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	MsgType       string                 `protobuf:"bytes,6,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_gateway_gateway_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_common_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Frame) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Frame) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Frame) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

var File_gateway_gateway_common_proto protoreflect.FileDescriptor

const file_gateway_gateway_common_proto_rawDesc = "" +
	"\n" +
	"\x1cgateway/gateway_common.proto\"\x84\x01\n" +
	"\x05Frame\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x17\n" +
	"\aconn_id\x18\x04 \x01(\x04R\x06connId\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x19\n" +
	"\bmsg_type\x18\x06 \x01(\tR\amsgType2'\n" +
	"\aGateway\x12\x1c\n" +
	"\x06Stream\x12\x06.Frame\x1a\x06.Frame(\x010\x01B(Z&github.com/gogu-x/gogs/pb/protoGatewayb\x06proto3"

var (
	file_gateway_gateway_common_proto_rawDescOnce sync.Once
	file_gateway_gateway_common_proto_rawDescData []byte
)

func file_gateway_gateway_common_proto_rawDescGZIP() []byte {
	file_gateway_gateway_common_proto_rawDescOnce.Do(func() {
		file_gateway_gateway_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_gateway_common_proto_rawDesc), len(file_gateway_gateway_common_proto_rawDesc)))
	})
	return file_gateway_gateway_common_proto_rawDescData
}

var file_gateway_gateway_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gateway_gateway_common_proto_goTypes = []any{
	(*Frame)(nil), // 0: Frame
}
var file_gateway_gateway_common_proto_depIdxs = []int32{
	0, // 0: Gateway.Stream:input_type -> Frame
	0, // 1: Gateway.Stream:output_type -> Frame
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_gateway_common_proto_init() }
func file_gateway_gateway_common_proto_init() {
	if File_gateway_gateway_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_gateway_common_proto_rawDesc), len(file_gateway_gateway_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_gateway_common_proto_goTypes,
		DependencyIndexes: file_gateway_gateway_common_proto_depIdxs,
		MessageInfos:      file_gateway_gateway_common_proto_msgTypes,
	}.Build()
	File_gateway_gateway_common_proto = out.File
	file_gateway_gateway_common_proto_goTypes = nil
	file_gateway_gateway_common_proto_depIdxs = nil
}
