// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: gateway/gateway_ack.proto

package protoGateway

import (
	protoCommon "github.com/gogu-x/gogs/pb/protoCommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          protoCommon.ErrCode    `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginAck) Reset() {
	*x = LoginAck{}
	mi := &file_gateway_gateway_ack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAck) ProtoMessage() {}

func (x *LoginAck) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_ack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAck.ProtoReflect.Descriptor instead.
func (*LoginAck) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_ack_proto_rawDescGZIP(), []int{0}
}

func (x *LoginAck) GetCode() protoCommon.ErrCode {
	if x != nil {
		return x.Code
	}
	return protoCommon.ErrCode(0)
}

func (x *LoginAck) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          protoCommon.ErrCode    `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_gateway_gateway_ack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_ack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_ack_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAck) GetCode() protoCommon.ErrCode {
	if x != nil {
		return x.Code
	}
	return protoCommon.ErrCode(0)
}

func (x *RegisterAck) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ServerAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      int32                  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerAccount) Reset() {
	*x = ServerAccount{}
	mi := &file_gateway_gateway_ack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerAccount) ProtoMessage() {}

func (x *ServerAccount) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_ack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerAccount.ProtoReflect.Descriptor instead.
func (*ServerAccount) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_ack_proto_rawDescGZIP(), []int{2}
}

func (x *ServerAccount) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServerAccount) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type ServerListAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          protoCommon.ErrCode    `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Accounts      []*ServerAccount       `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerListAck) Reset() {
	*x = ServerListAck{}
	mi := &file_gateway_gateway_ack_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerListAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerListAck) ProtoMessage() {}

func (x *ServerListAck) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_ack_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerListAck.ProtoReflect.Descriptor instead.
func (*ServerListAck) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_ack_proto_rawDescGZIP(), []int{3}
}

func (x *ServerListAck) GetCode() protoCommon.ErrCode {
	if x != nil {
		return x.Code
	}
	return protoCommon.ErrCode(0)
}

func (x *ServerListAck) GetAccounts() []*ServerAccount {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type LoginGameAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          protoCommon.ErrCode    `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginGameAck) Reset() {
	*x = LoginGameAck{}
	mi := &file_gateway_gateway_ack_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginGameAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGameAck) ProtoMessage() {}

func (x *LoginGameAck) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_ack_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginGameAck.ProtoReflect.Descriptor instead.
func (*LoginGameAck) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_ack_proto_rawDescGZIP(), []int{4}
}

func (x *LoginGameAck) GetCode() protoCommon.ErrCode {
	if x != nil {
		return x.Code
	}
	return protoCommon.ErrCode(0)
}

func (x *LoginGameAck) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

var File_gateway_gateway_ack_proto protoreflect.FileDescriptor

const file_gateway_gateway_ack_proto_rawDesc = "" +
	"\n" +
	"\x19gateway/gateway_ack.proto\x1a\x12common/error.proto\":\n" +
	"\bLoginAck\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x0e2\b.ErrCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"=\n" +
	"\vRegisterAck\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x0e2\b.ErrCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\">\n" +
	"\rServerAccount\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x05R\bserverId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\"Y\n" +
	"\rServerListAck\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x0e2\b.ErrCodeR\x04code\x12*\n" +
	"\baccounts\x18\x02 \x03(\v2\x0e.ServerAccountR\baccounts\">\n" +
	"\fLoginGameAck\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x0e2\b.ErrCodeR\x04code\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uidB(Z&github.com/gogu-x/gogs/pb/protoGatewayb\x06proto3"

var (
	file_gateway_gateway_ack_proto_rawDescOnce sync.Once
	file_gateway_gateway_ack_proto_rawDescData []byte
)

func file_gateway_gateway_ack_proto_rawDescGZIP() []byte {
	file_gateway_gateway_ack_proto_rawDescOnce.Do(func() {
		file_gateway_gateway_ack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_gateway_ack_proto_rawDesc), len(file_gateway_gateway_ack_proto_rawDesc)))
	})
	return file_gateway_gateway_ack_proto_rawDescData
}

var file_gateway_gateway_ack_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gateway_gateway_ack_proto_goTypes = []any{
	(*LoginAck)(nil),         // 0: LoginAck
	(*RegisterAck)(nil),      // 1: RegisterAck
	(*ServerAccount)(nil),    // 2: ServerAccount
	(*ServerListAck)(nil),    // 3: ServerListAck
	(*LoginGameAck)(nil),     // 4: LoginGameAck
	(protoCommon.ErrCode)(0), // 5: ErrCode
}
var file_gateway_gateway_ack_proto_depIdxs = []int32{
	5, // 0: LoginAck.code:type_name -> ErrCode
	5, // 1: RegisterAck.code:type_name -> ErrCode
	5, // 2: ServerListAck.code:type_name -> ErrCode
	2, // 3: ServerListAck.accounts:type_name -> ServerAccount
	5, // 4: LoginGameAck.code:type_name -> ErrCode
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gateway_gateway_ack_proto_init() }
func file_gateway_gateway_ack_proto_init() {
	if File_gateway_gateway_ack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_gateway_ack_proto_rawDesc), len(file_gateway_gateway_ack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_gateway_ack_proto_goTypes,
		DependencyIndexes: file_gateway_gateway_ack_proto_depIdxs,
		MessageInfos:      file_gateway_gateway_ack_proto_msgTypes,
	}.Build()
	File_gateway_gateway_ack_proto = out.File
	file_gateway_gateway_ack_proto_goTypes = nil
	file_gateway_gateway_ack_proto_depIdxs = nil
}
