// Code generated by deepcopy-gen. DO NOT EDIT.

package player

// DeepCopy 返回 Player 的独立副本。
func (in *Player) DeepCopy() *Player {
	if in == nil {
		return nil
	}
	out := *in
	out.AssetMgr = in.AssetMgr.DeepCopy()
	out.BagMgr = in.BagMgr.DeepCopy()
	out.CardGroupMgr = in.CardGroupMgr.DeepCopy()
	out.RoleMgr = in.RoleMgr.DeepCopy()
	out.EquipmentMgr = in.EquipmentMgr.DeepCopy()
	out.ShopMgr = in.ShopMgr.DeepCopy()
	out.TowerMgr = in.TowerMgr.DeepCopy()
	if in.TestMsgMap != nil {
		out.TestMsgMap = make(map[int]int32, len(in.TestMsgMap))
		for key1, value2 := range in.TestMsgMap {
			var cloned3 int32
			cloned3 = value2
			out.TestMsgMap[key1] = cloned3
		}
	}
	return &out
}
