// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: cspb/battle/ack.proto

package pb_battle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartBattleAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Outcome       BattleOutcome          `protobuf:"varint,2,opt,name=outcome,proto3,enum=BattleOutcome" json:"outcome,omitempty"`
	Units         []*BattleUnitResult    `protobuf:"bytes,3,rep,name=units,proto3" json:"units,omitempty"`
	Events        []*BattleEvent         `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	Checksum      string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Replay        *BattleReplay          `protobuf:"bytes,6,opt,name=replay,proto3" json:"replay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBattleAck) Reset() {
	*x = StartBattleAck{}
	mi := &file_cspb_battle_ack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBattleAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBattleAck) ProtoMessage() {}

func (x *StartBattleAck) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_battle_ack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBattleAck.ProtoReflect.Descriptor instead.
func (*StartBattleAck) Descriptor() ([]byte, []int) {
	return file_cspb_battle_ack_proto_rawDescGZIP(), []int{0}
}

func (x *StartBattleAck) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *StartBattleAck) GetOutcome() BattleOutcome {
	if x != nil {
		return x.Outcome
	}
	return BattleOutcome_BATTLE_OUTCOME_UNSPECIFIED
}

func (x *StartBattleAck) GetUnits() []*BattleUnitResult {
	if x != nil {
		return x.Units
	}
	return nil
}

func (x *StartBattleAck) GetEvents() []*BattleEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *StartBattleAck) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *StartBattleAck) GetReplay() *BattleReplay {
	if x != nil {
		return x.Replay
	}
	return nil
}

type VerifyBattleReplayAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyBattleReplayAck) Reset() {
	*x = VerifyBattleReplayAck{}
	mi := &file_cspb_battle_ack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyBattleReplayAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyBattleReplayAck) ProtoMessage() {}

func (x *VerifyBattleReplayAck) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_battle_ack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyBattleReplayAck.ProtoReflect.Descriptor instead.
func (*VerifyBattleReplayAck) Descriptor() ([]byte, []int) {
	return file_cspb_battle_ack_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyBattleReplayAck) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyBattleReplayAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type QueryBattleAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Result        *StartBattleAck        `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryBattleAck) Reset() {
	*x = QueryBattleAck{}
	mi := &file_cspb_battle_ack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryBattleAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBattleAck) ProtoMessage() {}

func (x *QueryBattleAck) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_battle_ack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBattleAck.ProtoReflect.Descriptor instead.
func (*QueryBattleAck) Descriptor() ([]byte, []int) {
	return file_cspb_battle_ack_proto_rawDescGZIP(), []int{2}
}

func (x *QueryBattleAck) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *QueryBattleAck) GetResult() *StartBattleAck {
	if x != nil {
		return x.Result
	}
	return nil
}

type RebuildBattleAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	BattleId      string                 `protobuf:"bytes,2,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildBattleAck) Reset() {
	*x = RebuildBattleAck{}
	mi := &file_cspb_battle_ack_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildBattleAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildBattleAck) ProtoMessage() {}

func (x *RebuildBattleAck) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_battle_ack_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildBattleAck.ProtoReflect.Descriptor instead.
func (*RebuildBattleAck) Descriptor() ([]byte, []int) {
	return file_cspb_battle_ack_proto_rawDescGZIP(), []int{3}
}

func (x *RebuildBattleAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RebuildBattleAck) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *RebuildBattleAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_cspb_battle_ack_proto protoreflect.FileDescriptor

const file_cspb_battle_ack_proto_rawDesc = "" +
	"\n" +
	"\x15cspb/battle/ack.proto\x1a\x18cspb/battle/struct.proto\"\xe9\x01\n" +
	"\x0eStartBattleAck\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12(\n" +
	"\aoutcome\x18\x02 \x01(\x0e2\x0e.BattleOutcomeR\aoutcome\x12'\n" +
	"\x05units\x18\x03 \x03(\v2\x11.BattleUnitResultR\x05units\x12$\n" +
	"\x06events\x18\x04 \x03(\v2\f.BattleEventR\x06events\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\x12%\n" +
	"\x06replay\x18\x06 \x01(\v2\r.BattleReplayR\x06replay\"E\n" +
	"\x15VerifyBattleReplayAck\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"O\n" +
	"\x0eQueryBattleAck\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12'\n" +
	"\x06result\x18\x02 \x01(\v2\x0f.StartBattleAckR\x06result\"c\n" +
	"\x10RebuildBattleAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1b\n" +
	"\tbattle_id\x18\x02 \x01(\tR\bbattleId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reasonB*Z(github.com/gogu-x/gogs/pb/cspb/pb_battleb\x06proto3"

var (
	file_cspb_battle_ack_proto_rawDescOnce sync.Once
	file_cspb_battle_ack_proto_rawDescData []byte
)

func file_cspb_battle_ack_proto_rawDescGZIP() []byte {
	file_cspb_battle_ack_proto_rawDescOnce.Do(func() {
		file_cspb_battle_ack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cspb_battle_ack_proto_rawDesc), len(file_cspb_battle_ack_proto_rawDesc)))
	})
	return file_cspb_battle_ack_proto_rawDescData
}

var file_cspb_battle_ack_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cspb_battle_ack_proto_goTypes = []any{
	(*StartBattleAck)(nil),        // 0: StartBattleAck
	(*VerifyBattleReplayAck)(nil), // 1: VerifyBattleReplayAck
	(*QueryBattleAck)(nil),        // 2: QueryBattleAck
	(*RebuildBattleAck)(nil),      // 3: RebuildBattleAck
	(BattleOutcome)(0),            // 4: BattleOutcome
	(*BattleUnitResult)(nil),      // 5: BattleUnitResult
	(*BattleEvent)(nil),           // 6: BattleEvent
	(*BattleReplay)(nil),          // 7: BattleReplay
}
var file_cspb_battle_ack_proto_depIdxs = []int32{
	4, // 0: StartBattleAck.outcome:type_name -> BattleOutcome
	5, // 1: StartBattleAck.units:type_name -> BattleUnitResult
	6, // 2: StartBattleAck.events:type_name -> BattleEvent
	7, // 3: StartBattleAck.replay:type_name -> BattleReplay
	0, // 4: QueryBattleAck.result:type_name -> StartBattleAck
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cspb_battle_ack_proto_init() }
func file_cspb_battle_ack_proto_init() {
	if File_cspb_battle_ack_proto != nil {
		return
	}
	file_cspb_battle_struct_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cspb_battle_ack_proto_rawDesc), len(file_cspb_battle_ack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cspb_battle_ack_proto_goTypes,
		DependencyIndexes: file_cspb_battle_ack_proto_depIdxs,
		MessageInfos:      file_cspb_battle_ack_proto_msgTypes,
	}.Build()
	File_cspb_battle_ack_proto = out.File
	file_cspb_battle_ack_proto_goTypes = nil
	file_cspb_battle_ack_proto_depIdxs = nil
}
