// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: cspb/battle/req.proto

package pb_battle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StartBattleReq 请求开始一场战斗。UID/serverID/sessionID 公共头由生成工具注入；
// attacker_roles/defender_roles/source_node_id 由 Game 权威覆盖，客户端值不可信。
type StartBattleReq struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UID                  uint64                 `protobuf:"varint,101,opt,name=uID,proto3" json:"uID,omitempty"`
	ServerID             uint32                 `protobuf:"varint,102,opt,name=serverID,proto3" json:"serverID,omitempty"`
	SessionID            string                 `protobuf:"bytes,103,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	BattleType           BattleType             `protobuf:"varint,1,opt,name=battle_type,json=battleType,proto3,enum=BattleType" json:"battle_type,omitempty"`
	BusinessId           string                 `protobuf:"bytes,2,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	AttackerRoles        []*Role                `protobuf:"bytes,3,rep,name=attacker_roles,json=attackerRoles,proto3" json:"attacker_roles,omitempty"`
	DefenderRoles        []*Role                `protobuf:"bytes,4,rep,name=defender_roles,json=defenderRoles,proto3" json:"defender_roles,omitempty"`
	MonsterGroupConfigId int32                  `protobuf:"varint,5,opt,name=monster_group_config_id,json=monsterGroupConfigId,proto3" json:"monster_group_config_id,omitempty"`
	SourceNodeId         uint32                 `protobuf:"varint,6,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StartBattleReq) Reset() {
	*x = StartBattleReq{}
	mi := &file_cspb_battle_req_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBattleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBattleReq) ProtoMessage() {}

func (x *StartBattleReq) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_battle_req_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBattleReq.ProtoReflect.Descriptor instead.
func (*StartBattleReq) Descriptor() ([]byte, []int) {
	return file_cspb_battle_req_proto_rawDescGZIP(), []int{0}
}

func (x *StartBattleReq) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *StartBattleReq) GetServerID() uint32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *StartBattleReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *StartBattleReq) GetBattleType() BattleType {
	if x != nil {
		return x.BattleType
	}
	return BattleType_BATTLE_TYPE_UNSPECIFIED
}

func (x *StartBattleReq) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *StartBattleReq) GetAttackerRoles() []*Role {
	if x != nil {
		return x.AttackerRoles
	}
	return nil
}

func (x *StartBattleReq) GetDefenderRoles() []*Role {
	if x != nil {
		return x.DefenderRoles
	}
	return nil
}

func (x *StartBattleReq) GetMonsterGroupConfigId() int32 {
	if x != nil {
		return x.MonsterGroupConfigId
	}
	return 0
}

func (x *StartBattleReq) GetSourceNodeId() uint32 {
	if x != nil {
		return x.SourceNodeId
	}
	return 0
}

var File_cspb_battle_req_proto protoreflect.FileDescriptor

const file_cspb_battle_req_proto_rawDesc = "" +
	"\n" +
	"\x15cspb/battle/req.proto\x1a\x18cspb/battle/struct.proto\"\xe4\x02\n" +
	"\x0eStartBattleReq\x12\x10\n" +
	"\x03uID\x18e \x01(\x04R\x03uID\x12\x1a\n" +
	"\bserverID\x18f \x01(\rR\bserverID\x12\x1c\n" +
	"\tsessionID\x18g \x01(\tR\tsessionID\x12,\n" +
	"\vbattle_type\x18\x01 \x01(\x0e2\v.BattleTypeR\n" +
	"battleType\x12\x1f\n" +
	"\vbusiness_id\x18\x02 \x01(\tR\n" +
	"businessId\x12,\n" +
	"\x0eattacker_roles\x18\x03 \x03(\v2\x05.RoleR\rattackerRoles\x12,\n" +
	"\x0edefender_roles\x18\x04 \x03(\v2\x05.RoleR\rdefenderRoles\x125\n" +
	"\x17monster_group_config_id\x18\x05 \x01(\x05R\x14monsterGroupConfigId\x12$\n" +
	"\x0esource_node_id\x18\x06 \x01(\rR\fsourceNodeIdB*Z(github.com/gogu-x/gogs/pb/cspb/pb_battleb\x06proto3"

var (
	file_cspb_battle_req_proto_rawDescOnce sync.Once
	file_cspb_battle_req_proto_rawDescData []byte
)

func file_cspb_battle_req_proto_rawDescGZIP() []byte {
	file_cspb_battle_req_proto_rawDescOnce.Do(func() {
		file_cspb_battle_req_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cspb_battle_req_proto_rawDesc), len(file_cspb_battle_req_proto_rawDesc)))
	})
	return file_cspb_battle_req_proto_rawDescData
}

var file_cspb_battle_req_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cspb_battle_req_proto_goTypes = []any{
	(*StartBattleReq)(nil), // 0: StartBattleReq
	(BattleType)(0),        // 1: BattleType
	(*Role)(nil),           // 2: Role
}
var file_cspb_battle_req_proto_depIdxs = []int32{
	1, // 0: StartBattleReq.battle_type:type_name -> BattleType
	2, // 1: StartBattleReq.attacker_roles:type_name -> Role
	2, // 2: StartBattleReq.defender_roles:type_name -> Role
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cspb_battle_req_proto_init() }
func file_cspb_battle_req_proto_init() {
	if File_cspb_battle_req_proto != nil {
		return
	}
	file_cspb_battle_struct_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cspb_battle_req_proto_rawDesc), len(file_cspb_battle_req_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cspb_battle_req_proto_goTypes,
		DependencyIndexes: file_cspb_battle_req_proto_depIdxs,
		MessageInfos:      file_cspb_battle_req_proto_msgTypes,
	}.Build()
	File_cspb_battle_req_proto = out.File
	file_cspb_battle_req_proto_goTypes = nil
	file_cspb_battle_req_proto_depIdxs = nil
}
