// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: cspb/battle/req.proto

package pb_battle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Correlation IDs are deliberately absent: Battle creates the battle_id from
// deterministic input and Game never retries an accepted create blindly.
type StartBattleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UID           uint64                 `protobuf:"varint,1,opt,name=uID,proto3" json:"uID,omitempty"`
	ServerID      uint32                 `protobuf:"varint,2,opt,name=serverID,proto3" json:"serverID,omitempty"`
	SessionID     string                 `protobuf:"bytes,3,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Input         *BattleInput           `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	SourceNodeId  uint32                 `protobuf:"varint,5,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBattleReq) Reset() {
	*x = StartBattleReq{}
	mi := &file_cspb_battle_req_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBattleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBattleReq) ProtoMessage() {}

func (x *StartBattleReq) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_battle_req_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBattleReq.ProtoReflect.Descriptor instead.
func (*StartBattleReq) Descriptor() ([]byte, []int) {
	return file_cspb_battle_req_proto_rawDescGZIP(), []int{0}
}

func (x *StartBattleReq) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *StartBattleReq) GetServerID() uint32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *StartBattleReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *StartBattleReq) GetInput() *BattleInput {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *StartBattleReq) GetSourceNodeId() uint32 {
	if x != nil {
		return x.SourceNodeId
	}
	return 0
}

type VerifyBattleReplayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UID           uint64                 `protobuf:"varint,1,opt,name=uID,proto3" json:"uID,omitempty"`
	ServerID      uint32                 `protobuf:"varint,2,opt,name=serverID,proto3" json:"serverID,omitempty"`
	SessionID     string                 `protobuf:"bytes,3,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Replay        *BattleReplay          `protobuf:"bytes,4,opt,name=replay,proto3" json:"replay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyBattleReplayReq) Reset() {
	*x = VerifyBattleReplayReq{}
	mi := &file_cspb_battle_req_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyBattleReplayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyBattleReplayReq) ProtoMessage() {}

func (x *VerifyBattleReplayReq) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_battle_req_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyBattleReplayReq.ProtoReflect.Descriptor instead.
func (*VerifyBattleReplayReq) Descriptor() ([]byte, []int) {
	return file_cspb_battle_req_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyBattleReplayReq) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *VerifyBattleReplayReq) GetServerID() uint32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *VerifyBattleReplayReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *VerifyBattleReplayReq) GetReplay() *BattleReplay {
	if x != nil {
		return x.Replay
	}
	return nil
}

type QueryBattleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UID           uint64                 `protobuf:"varint,1,opt,name=uID,proto3" json:"uID,omitempty"`
	ServerID      uint32                 `protobuf:"varint,2,opt,name=serverID,proto3" json:"serverID,omitempty"`
	SessionID     string                 `protobuf:"bytes,3,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	BattleId      string                 `protobuf:"bytes,4,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryBattleReq) Reset() {
	*x = QueryBattleReq{}
	mi := &file_cspb_battle_req_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryBattleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBattleReq) ProtoMessage() {}

func (x *QueryBattleReq) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_battle_req_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBattleReq.ProtoReflect.Descriptor instead.
func (*QueryBattleReq) Descriptor() ([]byte, []int) {
	return file_cspb_battle_req_proto_rawDescGZIP(), []int{2}
}

func (x *QueryBattleReq) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *QueryBattleReq) GetServerID() uint32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *QueryBattleReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *QueryBattleReq) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

// Rebuild accepts only an already persisted battle_id. Arbitrary input is not
// accepted, so a rebuild can only use the immutable input in the stored replay.
type RebuildBattleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UID           uint64                 `protobuf:"varint,1,opt,name=uID,proto3" json:"uID,omitempty"`
	ServerID      uint32                 `protobuf:"varint,2,opt,name=serverID,proto3" json:"serverID,omitempty"`
	SessionID     string                 `protobuf:"bytes,3,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	BattleId      string                 `protobuf:"bytes,4,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildBattleReq) Reset() {
	*x = RebuildBattleReq{}
	mi := &file_cspb_battle_req_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildBattleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildBattleReq) ProtoMessage() {}

func (x *RebuildBattleReq) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_battle_req_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildBattleReq.ProtoReflect.Descriptor instead.
func (*RebuildBattleReq) Descriptor() ([]byte, []int) {
	return file_cspb_battle_req_proto_rawDescGZIP(), []int{3}
}

func (x *RebuildBattleReq) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *RebuildBattleReq) GetServerID() uint32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *RebuildBattleReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *RebuildBattleReq) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

var File_cspb_battle_req_proto protoreflect.FileDescriptor

const file_cspb_battle_req_proto_rawDesc = "" +
	"\n" +
	"\x15cspb/battle/req.proto\x1a\x18cspb/battle/struct.proto\"\xa6\x01\n" +
	"\x0eStartBattleReq\x12\x10\n" +
	"\x03uID\x18\x01 \x01(\x04R\x03uID\x12\x1a\n" +
	"\bserverID\x18\x02 \x01(\rR\bserverID\x12\x1c\n" +
	"\tsessionID\x18\x03 \x01(\tR\tsessionID\x12\"\n" +
	"\x05input\x18\x04 \x01(\v2\f.BattleInputR\x05input\x12$\n" +
	"\x0esource_node_id\x18\x05 \x01(\rR\fsourceNodeId\"\x8a\x01\n" +
	"\x15VerifyBattleReplayReq\x12\x10\n" +
	"\x03uID\x18\x01 \x01(\x04R\x03uID\x12\x1a\n" +
	"\bserverID\x18\x02 \x01(\rR\bserverID\x12\x1c\n" +
	"\tsessionID\x18\x03 \x01(\tR\tsessionID\x12%\n" +
	"\x06replay\x18\x04 \x01(\v2\r.BattleReplayR\x06replay\"y\n" +
	"\x0eQueryBattleReq\x12\x10\n" +
	"\x03uID\x18\x01 \x01(\x04R\x03uID\x12\x1a\n" +
	"\bserverID\x18\x02 \x01(\rR\bserverID\x12\x1c\n" +
	"\tsessionID\x18\x03 \x01(\tR\tsessionID\x12\x1b\n" +
	"\tbattle_id\x18\x04 \x01(\tR\bbattleId\"{\n" +
	"\x10RebuildBattleReq\x12\x10\n" +
	"\x03uID\x18\x01 \x01(\x04R\x03uID\x12\x1a\n" +
	"\bserverID\x18\x02 \x01(\rR\bserverID\x12\x1c\n" +
	"\tsessionID\x18\x03 \x01(\tR\tsessionID\x12\x1b\n" +
	"\tbattle_id\x18\x04 \x01(\tR\bbattleIdB*Z(github.com/gogu-x/gogs/pb/cspb/pb_battleb\x06proto3"

var (
	file_cspb_battle_req_proto_rawDescOnce sync.Once
	file_cspb_battle_req_proto_rawDescData []byte
)

func file_cspb_battle_req_proto_rawDescGZIP() []byte {
	file_cspb_battle_req_proto_rawDescOnce.Do(func() {
		file_cspb_battle_req_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cspb_battle_req_proto_rawDesc), len(file_cspb_battle_req_proto_rawDesc)))
	})
	return file_cspb_battle_req_proto_rawDescData
}

var file_cspb_battle_req_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cspb_battle_req_proto_goTypes = []any{
	(*StartBattleReq)(nil),        // 0: StartBattleReq
	(*VerifyBattleReplayReq)(nil), // 1: VerifyBattleReplayReq
	(*QueryBattleReq)(nil),        // 2: QueryBattleReq
	(*RebuildBattleReq)(nil),      // 3: RebuildBattleReq
	(*BattleInput)(nil),           // 4: BattleInput
	(*BattleReplay)(nil),          // 5: BattleReplay
}
var file_cspb_battle_req_proto_depIdxs = []int32{
	4, // 0: StartBattleReq.input:type_name -> BattleInput
	5, // 1: VerifyBattleReplayReq.replay:type_name -> BattleReplay
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cspb_battle_req_proto_init() }
func file_cspb_battle_req_proto_init() {
	if File_cspb_battle_req_proto != nil {
		return
	}
	file_cspb_battle_struct_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cspb_battle_req_proto_rawDesc), len(file_cspb_battle_req_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cspb_battle_req_proto_goTypes,
		DependencyIndexes: file_cspb_battle_req_proto_depIdxs,
		MessageInfos:      file_cspb_battle_req_proto_msgTypes,
	}.Build()
	File_cspb_battle_req_proto = out.File
	file_cspb_battle_req_proto_goTypes = nil
	file_cspb_battle_req_proto_depIdxs = nil
}
