// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: cspb/battle/struct.proto

package pb_battle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BattleTeam int32

const (
	BattleTeam_BATTLE_TEAM_UNSPECIFIED BattleTeam = 0
	BattleTeam_BATTLE_TEAM_ATTACKER    BattleTeam = 1
	BattleTeam_BATTLE_TEAM_DEFENDER    BattleTeam = 2
)

// Enum value maps for BattleTeam.
var (
	BattleTeam_name = map[int32]string{
		0: "BATTLE_TEAM_UNSPECIFIED",
		1: "BATTLE_TEAM_ATTACKER",
		2: "BATTLE_TEAM_DEFENDER",
	}
	BattleTeam_value = map[string]int32{
		"BATTLE_TEAM_UNSPECIFIED": 0,
		"BATTLE_TEAM_ATTACKER":    1,
		"BATTLE_TEAM_DEFENDER":    2,
	}
)

func (x BattleTeam) Enum() *BattleTeam {
	p := new(BattleTeam)
	*p = x
	return p
}

func (x BattleTeam) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleTeam) Descriptor() protoreflect.EnumDescriptor {
	return file_cspb_battle_struct_proto_enumTypes[0].Descriptor()
}

func (BattleTeam) Type() protoreflect.EnumType {
	return &file_cspb_battle_struct_proto_enumTypes[0]
}

func (x BattleTeam) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleTeam.Descriptor instead.
func (BattleTeam) EnumDescriptor() ([]byte, []int) {
	return file_cspb_battle_struct_proto_rawDescGZIP(), []int{0}
}

type BattleOutcome int32

const (
	BattleOutcome_BATTLE_OUTCOME_UNSPECIFIED  BattleOutcome = 0
	BattleOutcome_BATTLE_OUTCOME_ATTACKER_WIN BattleOutcome = 1
	BattleOutcome_BATTLE_OUTCOME_DEFENDER_WIN BattleOutcome = 2
	BattleOutcome_BATTLE_OUTCOME_DRAW         BattleOutcome = 3
)

// Enum value maps for BattleOutcome.
var (
	BattleOutcome_name = map[int32]string{
		0: "BATTLE_OUTCOME_UNSPECIFIED",
		1: "BATTLE_OUTCOME_ATTACKER_WIN",
		2: "BATTLE_OUTCOME_DEFENDER_WIN",
		3: "BATTLE_OUTCOME_DRAW",
	}
	BattleOutcome_value = map[string]int32{
		"BATTLE_OUTCOME_UNSPECIFIED":  0,
		"BATTLE_OUTCOME_ATTACKER_WIN": 1,
		"BATTLE_OUTCOME_DEFENDER_WIN": 2,
		"BATTLE_OUTCOME_DRAW":         3,
	}
)

func (x BattleOutcome) Enum() *BattleOutcome {
	p := new(BattleOutcome)
	*p = x
	return p
}

func (x BattleOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_cspb_battle_struct_proto_enumTypes[1].Descriptor()
}

func (BattleOutcome) Type() protoreflect.EnumType {
	return &file_cspb_battle_struct_proto_enumTypes[1]
}

func (x BattleOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleOutcome.Descriptor instead.
func (BattleOutcome) EnumDescriptor() ([]byte, []int) {
	return file_cspb_battle_struct_proto_rawDescGZIP(), []int{1}
}

type TargetRule int32

const (
	TargetRule_TARGET_RULE_UNSPECIFIED    TargetRule = 0
	TargetRule_TARGET_RULE_ENEMY_SINGLE   TargetRule = 1
	TargetRule_TARGET_RULE_ENEMY_ALL      TargetRule = 2
	TargetRule_TARGET_RULE_ALLY_LOWEST_HP TargetRule = 3
	TargetRule_TARGET_RULE_SELF           TargetRule = 4
)

// Enum value maps for TargetRule.
var (
	TargetRule_name = map[int32]string{
		0: "TARGET_RULE_UNSPECIFIED",
		1: "TARGET_RULE_ENEMY_SINGLE",
		2: "TARGET_RULE_ENEMY_ALL",
		3: "TARGET_RULE_ALLY_LOWEST_HP",
		4: "TARGET_RULE_SELF",
	}
	TargetRule_value = map[string]int32{
		"TARGET_RULE_UNSPECIFIED":    0,
		"TARGET_RULE_ENEMY_SINGLE":   1,
		"TARGET_RULE_ENEMY_ALL":      2,
		"TARGET_RULE_ALLY_LOWEST_HP": 3,
		"TARGET_RULE_SELF":           4,
	}
)

func (x TargetRule) Enum() *TargetRule {
	p := new(TargetRule)
	*p = x
	return p
}

func (x TargetRule) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetRule) Descriptor() protoreflect.EnumDescriptor {
	return file_cspb_battle_struct_proto_enumTypes[2].Descriptor()
}

func (TargetRule) Type() protoreflect.EnumType {
	return &file_cspb_battle_struct_proto_enumTypes[2]
}

func (x TargetRule) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetRule.Descriptor instead.
func (TargetRule) EnumDescriptor() ([]byte, []int) {
	return file_cspb_battle_struct_proto_rawDescGZIP(), []int{2}
}

type EffectType int32

const (
	EffectType_EFFECT_TYPE_UNSPECIFIED  EffectType = 0
	EffectType_EFFECT_TYPE_DAMAGE       EffectType = 1
	EffectType_EFFECT_TYPE_HEAL         EffectType = 2
	EffectType_EFFECT_TYPE_APPLY_STATUS EffectType = 3
)

// Enum value maps for EffectType.
var (
	EffectType_name = map[int32]string{
		0: "EFFECT_TYPE_UNSPECIFIED",
		1: "EFFECT_TYPE_DAMAGE",
		2: "EFFECT_TYPE_HEAL",
		3: "EFFECT_TYPE_APPLY_STATUS",
	}
	EffectType_value = map[string]int32{
		"EFFECT_TYPE_UNSPECIFIED":  0,
		"EFFECT_TYPE_DAMAGE":       1,
		"EFFECT_TYPE_HEAL":         2,
		"EFFECT_TYPE_APPLY_STATUS": 3,
	}
)

func (x EffectType) Enum() *EffectType {
	p := new(EffectType)
	*p = x
	return p
}

func (x EffectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EffectType) Descriptor() protoreflect.EnumDescriptor {
	return file_cspb_battle_struct_proto_enumTypes[3].Descriptor()
}

func (EffectType) Type() protoreflect.EnumType {
	return &file_cspb_battle_struct_proto_enumTypes[3]
}

func (x EffectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EffectType.Descriptor instead.
func (EffectType) EnumDescriptor() ([]byte, []int) {
	return file_cspb_battle_struct_proto_rawDescGZIP(), []int{3}
}

type StatusType int32

const (
	StatusType_STATUS_TYPE_UNSPECIFIED        StatusType = 0
	StatusType_STATUS_TYPE_STUN               StatusType = 1
	StatusType_STATUS_TYPE_SILENCE            StatusType = 2
	StatusType_STATUS_TYPE_DOT                StatusType = 3
	StatusType_STATUS_TYPE_HOT                StatusType = 4
	StatusType_STATUS_TYPE_ATTRIBUTE_MODIFIER StatusType = 5
)

// Enum value maps for StatusType.
var (
	StatusType_name = map[int32]string{
		0: "STATUS_TYPE_UNSPECIFIED",
		1: "STATUS_TYPE_STUN",
		2: "STATUS_TYPE_SILENCE",
		3: "STATUS_TYPE_DOT",
		4: "STATUS_TYPE_HOT",
		5: "STATUS_TYPE_ATTRIBUTE_MODIFIER",
	}
	StatusType_value = map[string]int32{
		"STATUS_TYPE_UNSPECIFIED":        0,
		"STATUS_TYPE_STUN":               1,
		"STATUS_TYPE_SILENCE":            2,
		"STATUS_TYPE_DOT":                3,
		"STATUS_TYPE_HOT":                4,
		"STATUS_TYPE_ATTRIBUTE_MODIFIER": 5,
	}
)

func (x StatusType) Enum() *StatusType {
	p := new(StatusType)
	*p = x
	return p
}

func (x StatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_cspb_battle_struct_proto_enumTypes[4].Descriptor()
}

func (StatusType) Type() protoreflect.EnumType {
	return &file_cspb_battle_struct_proto_enumTypes[4]
}

func (x StatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusType.Descriptor instead.
func (StatusType) EnumDescriptor() ([]byte, []int) {
	return file_cspb_battle_struct_proto_rawDescGZIP(), []int{4}
}

type BattleEventType int32

const (
	BattleEventType_BATTLE_EVENT_TYPE_UNSPECIFIED    BattleEventType = 0
	BattleEventType_BATTLE_EVENT_TYPE_ACTION_STARTED BattleEventType = 1
	BattleEventType_BATTLE_EVENT_TYPE_SKILL_USED     BattleEventType = 2
	BattleEventType_BATTLE_EVENT_TYPE_DAMAGE         BattleEventType = 3
	BattleEventType_BATTLE_EVENT_TYPE_HEAL           BattleEventType = 4
	BattleEventType_BATTLE_EVENT_TYPE_STATUS_APPLIED BattleEventType = 5
	BattleEventType_BATTLE_EVENT_TYPE_ACTION_SKIPPED BattleEventType = 6
	BattleEventType_BATTLE_EVENT_TYPE_ACTION_ENDED   BattleEventType = 7
	BattleEventType_BATTLE_EVENT_TYPE_BATTLE_ENDED   BattleEventType = 8
)

// Enum value maps for BattleEventType.
var (
	BattleEventType_name = map[int32]string{
		0: "BATTLE_EVENT_TYPE_UNSPECIFIED",
		1: "BATTLE_EVENT_TYPE_ACTION_STARTED",
		2: "BATTLE_EVENT_TYPE_SKILL_USED",
		3: "BATTLE_EVENT_TYPE_DAMAGE",
		4: "BATTLE_EVENT_TYPE_HEAL",
		5: "BATTLE_EVENT_TYPE_STATUS_APPLIED",
		6: "BATTLE_EVENT_TYPE_ACTION_SKIPPED",
		7: "BATTLE_EVENT_TYPE_ACTION_ENDED",
		8: "BATTLE_EVENT_TYPE_BATTLE_ENDED",
	}
	BattleEventType_value = map[string]int32{
		"BATTLE_EVENT_TYPE_UNSPECIFIED":    0,
		"BATTLE_EVENT_TYPE_ACTION_STARTED": 1,
		"BATTLE_EVENT_TYPE_SKILL_USED":     2,
		"BATTLE_EVENT_TYPE_DAMAGE":         3,
		"BATTLE_EVENT_TYPE_HEAL":           4,
		"BATTLE_EVENT_TYPE_STATUS_APPLIED": 5,
		"BATTLE_EVENT_TYPE_ACTION_SKIPPED": 6,
		"BATTLE_EVENT_TYPE_ACTION_ENDED":   7,
		"BATTLE_EVENT_TYPE_BATTLE_ENDED":   8,
	}
)

func (x BattleEventType) Enum() *BattleEventType {
	p := new(BattleEventType)
	*p = x
	return p
}

func (x BattleEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_cspb_battle_struct_proto_enumTypes[5].Descriptor()
}

func (BattleEventType) Type() protoreflect.EnumType {
	return &file_cspb_battle_struct_proto_enumTypes[5]
}

func (x BattleEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleEventType.Descriptor instead.
func (BattleEventType) EnumDescriptor() ([]byte, []int) {
	return file_cspb_battle_struct_proto_rawDescGZIP(), []int{5}
}

type BattleCombatantInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	UnitConfigId  string                 `protobuf:"bytes,2,opt,name=unit_config_id,json=unitConfigId,proto3" json:"unit_config_id,omitempty"`
	Team          BattleTeam             `protobuf:"varint,3,opt,name=team,proto3,enum=BattleTeam" json:"team,omitempty"`
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleCombatantInput) Reset() {
	*x = BattleCombatantInput{}
	mi := &file_cspb_battle_struct_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleCombatantInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleCombatantInput) ProtoMessage() {}

func (x *BattleCombatantInput) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_battle_struct_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleCombatantInput.ProtoReflect.Descriptor instead.
func (*BattleCombatantInput) Descriptor() ([]byte, []int) {
	return file_cspb_battle_struct_proto_rawDescGZIP(), []int{0}
}

func (x *BattleCombatantInput) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *BattleCombatantInput) GetUnitConfigId() string {
	if x != nil {
		return x.UnitConfigId
	}
	return ""
}

func (x *BattleCombatantInput) GetTeam() BattleTeam {
	if x != nil {
		return x.Team
	}
	return BattleTeam_BATTLE_TEAM_UNSPECIFIED
}

func (x *BattleCombatantInput) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type BattleInput struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ConfigVersion string                  `protobuf:"bytes,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Seed          uint64                  `protobuf:"varint,2,opt,name=seed,proto3" json:"seed,omitempty"`
	Combatants    []*BattleCombatantInput `protobuf:"bytes,3,rep,name=combatants,proto3" json:"combatants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleInput) Reset() {
	*x = BattleInput{}
	mi := &file_cspb_battle_struct_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleInput) ProtoMessage() {}

func (x *BattleInput) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_battle_struct_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleInput.ProtoReflect.Descriptor instead.
func (*BattleInput) Descriptor() ([]byte, []int) {
	return file_cspb_battle_struct_proto_rawDescGZIP(), []int{1}
}

func (x *BattleInput) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *BattleInput) GetSeed() uint64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *BattleInput) GetCombatants() []*BattleCombatantInput {
	if x != nil {
		return x.Combatants
	}
	return nil
}

type BattleEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Action        uint64                 `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
	Tick          int64                  `protobuf:"varint,3,opt,name=tick,proto3" json:"tick,omitempty"`
	Type          BattleEventType        `protobuf:"varint,4,opt,name=type,proto3,enum=BattleEventType" json:"type,omitempty"`
	ActorId       string                 `protobuf:"bytes,5,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,6,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	SkillId       string                 `protobuf:"bytes,7,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	StatusId      string                 `protobuf:"bytes,8,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	Amount        int64                  `protobuf:"varint,9,opt,name=amount,proto3" json:"amount,omitempty"`
	HpBefore      int64                  `protobuf:"varint,10,opt,name=hp_before,json=hpBefore,proto3" json:"hp_before,omitempty"`
	HpAfter       int64                  `protobuf:"varint,11,opt,name=hp_after,json=hpAfter,proto3" json:"hp_after,omitempty"`
	Detail        string                 `protobuf:"bytes,12,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleEvent) Reset() {
	*x = BattleEvent{}
	mi := &file_cspb_battle_struct_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleEvent) ProtoMessage() {}

func (x *BattleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_battle_struct_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleEvent.ProtoReflect.Descriptor instead.
func (*BattleEvent) Descriptor() ([]byte, []int) {
	return file_cspb_battle_struct_proto_rawDescGZIP(), []int{2}
}

func (x *BattleEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *BattleEvent) GetAction() uint64 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *BattleEvent) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *BattleEvent) GetType() BattleEventType {
	if x != nil {
		return x.Type
	}
	return BattleEventType_BATTLE_EVENT_TYPE_UNSPECIFIED
}

func (x *BattleEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *BattleEvent) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *BattleEvent) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *BattleEvent) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

func (x *BattleEvent) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BattleEvent) GetHpBefore() int64 {
	if x != nil {
		return x.HpBefore
	}
	return 0
}

func (x *BattleEvent) GetHpAfter() int64 {
	if x != nil {
		return x.HpAfter
	}
	return 0
}

func (x *BattleEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type BattleUnitResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Team          BattleTeam             `protobuf:"varint,2,opt,name=team,proto3,enum=BattleTeam" json:"team,omitempty"`
	Hp            int64                  `protobuf:"varint,3,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int64                  `protobuf:"varint,4,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Alive         bool                   `protobuf:"varint,5,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleUnitResult) Reset() {
	*x = BattleUnitResult{}
	mi := &file_cspb_battle_struct_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleUnitResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleUnitResult) ProtoMessage() {}

func (x *BattleUnitResult) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_battle_struct_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleUnitResult.ProtoReflect.Descriptor instead.
func (*BattleUnitResult) Descriptor() ([]byte, []int) {
	return file_cspb_battle_struct_proto_rawDescGZIP(), []int{3}
}

func (x *BattleUnitResult) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *BattleUnitResult) GetTeam() BattleTeam {
	if x != nil {
		return x.Team
	}
	return BattleTeam_BATTLE_TEAM_UNSPECIFIED
}

func (x *BattleUnitResult) GetHp() int64 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *BattleUnitResult) GetMaxHp() int64 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *BattleUnitResult) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type BattleReplay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	ConfigVersion string                 `protobuf:"bytes,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	ConfigHash    string                 `protobuf:"bytes,3,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	Input         *BattleInput           `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	Events        []*BattleEvent         `protobuf:"bytes,5,rep,name=events,proto3" json:"events,omitempty"`
	Checksum      string                 `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleReplay) Reset() {
	*x = BattleReplay{}
	mi := &file_cspb_battle_struct_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleReplay) ProtoMessage() {}

func (x *BattleReplay) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_battle_struct_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleReplay.ProtoReflect.Descriptor instead.
func (*BattleReplay) Descriptor() ([]byte, []int) {
	return file_cspb_battle_struct_proto_rawDescGZIP(), []int{4}
}

func (x *BattleReplay) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *BattleReplay) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *BattleReplay) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *BattleReplay) GetInput() *BattleInput {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *BattleReplay) GetEvents() []*BattleEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *BattleReplay) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

// Asynchronous service lifecycle notifications. Created is always emitted
// before the first Action for a battle. Finished is idempotent by battle_id.
type BattleCreatedNtf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleCreatedNtf) Reset() {
	*x = BattleCreatedNtf{}
	mi := &file_cspb_battle_struct_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleCreatedNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleCreatedNtf) ProtoMessage() {}

func (x *BattleCreatedNtf) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_battle_struct_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleCreatedNtf.ProtoReflect.Descriptor instead.
func (*BattleCreatedNtf) Descriptor() ([]byte, []int) {
	return file_cspb_battle_struct_proto_rawDescGZIP(), []int{5}
}

func (x *BattleCreatedNtf) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *BattleCreatedNtf) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type BattleActionNtf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Event         *BattleEvent           `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleActionNtf) Reset() {
	*x = BattleActionNtf{}
	mi := &file_cspb_battle_struct_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleActionNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleActionNtf) ProtoMessage() {}

func (x *BattleActionNtf) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_battle_struct_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleActionNtf.ProtoReflect.Descriptor instead.
func (*BattleActionNtf) Descriptor() ([]byte, []int) {
	return file_cspb_battle_struct_proto_rawDescGZIP(), []int{6}
}

func (x *BattleActionNtf) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *BattleActionNtf) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BattleActionNtf) GetEvent() *BattleEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type BattleFinishedNtf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Outcome       BattleOutcome          `protobuf:"varint,3,opt,name=outcome,proto3,enum=BattleOutcome" json:"outcome,omitempty"`
	Units         []*BattleUnitResult    `protobuf:"bytes,4,rep,name=units,proto3" json:"units,omitempty"`
	Checksum      string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Replay        *BattleReplay          `protobuf:"bytes,6,opt,name=replay,proto3" json:"replay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleFinishedNtf) Reset() {
	*x = BattleFinishedNtf{}
	mi := &file_cspb_battle_struct_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleFinishedNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleFinishedNtf) ProtoMessage() {}

func (x *BattleFinishedNtf) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_battle_struct_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleFinishedNtf.ProtoReflect.Descriptor instead.
func (*BattleFinishedNtf) Descriptor() ([]byte, []int) {
	return file_cspb_battle_struct_proto_rawDescGZIP(), []int{7}
}

func (x *BattleFinishedNtf) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *BattleFinishedNtf) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BattleFinishedNtf) GetOutcome() BattleOutcome {
	if x != nil {
		return x.Outcome
	}
	return BattleOutcome_BATTLE_OUTCOME_UNSPECIFIED
}

func (x *BattleFinishedNtf) GetUnits() []*BattleUnitResult {
	if x != nil {
		return x.Units
	}
	return nil
}

func (x *BattleFinishedNtf) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *BattleFinishedNtf) GetReplay() *BattleReplay {
	if x != nil {
		return x.Replay
	}
	return nil
}

type BattleResultConfirmedNtf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleResultConfirmedNtf) Reset() {
	*x = BattleResultConfirmedNtf{}
	mi := &file_cspb_battle_struct_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleResultConfirmedNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleResultConfirmedNtf) ProtoMessage() {}

func (x *BattleResultConfirmedNtf) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_battle_struct_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleResultConfirmedNtf.ProtoReflect.Descriptor instead.
func (*BattleResultConfirmedNtf) Descriptor() ([]byte, []int) {
	return file_cspb_battle_struct_proto_rawDescGZIP(), []int{8}
}

func (x *BattleResultConfirmedNtf) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *BattleResultConfirmedNtf) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

var File_cspb_battle_struct_proto protoreflect.FileDescriptor

const file_cspb_battle_struct_proto_rawDesc = "" +
	"\n" +
	"\x18cspb/battle/struct.proto\"\x9a\x01\n" +
	"\x14BattleCombatantInput\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12$\n" +
	"\x0eunit_config_id\x18\x02 \x01(\tR\funitConfigId\x12\x1f\n" +
	"\x04team\x18\x03 \x01(\x0e2\v.BattleTeamR\x04team\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\"\x7f\n" +
	"\vBattleInput\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\tR\rconfigVersion\x12\x12\n" +
	"\x04seed\x18\x02 \x01(\x04R\x04seed\x125\n" +
	"\n" +
	"combatants\x18\x03 \x03(\v2\x15.BattleCombatantInputR\n" +
	"combatants\"\xd3\x02\n" +
	"\vBattleEvent\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x16\n" +
	"\x06action\x18\x02 \x01(\x04R\x06action\x12\x12\n" +
	"\x04tick\x18\x03 \x01(\x03R\x04tick\x12$\n" +
	"\x04type\x18\x04 \x01(\x0e2\x10.BattleEventTypeR\x04type\x12\x19\n" +
	"\bactor_id\x18\x05 \x01(\tR\aactorId\x12\x1b\n" +
	"\ttarget_id\x18\x06 \x01(\tR\btargetId\x12\x19\n" +
	"\bskill_id\x18\a \x01(\tR\askillId\x12\x1b\n" +
	"\tstatus_id\x18\b \x01(\tR\bstatusId\x12\x16\n" +
	"\x06amount\x18\t \x01(\x03R\x06amount\x12\x1b\n" +
	"\thp_before\x18\n" +
	" \x01(\x03R\bhpBefore\x12\x19\n" +
	"\bhp_after\x18\v \x01(\x03R\ahpAfter\x12\x16\n" +
	"\x06detail\x18\f \x01(\tR\x06detail\"\x91\x01\n" +
	"\x10BattleUnitResult\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1f\n" +
	"\x04team\x18\x02 \x01(\x0e2\v.BattleTeamR\x04team\x12\x0e\n" +
	"\x02hp\x18\x03 \x01(\x03R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x04 \x01(\x03R\x05maxHp\x12\x14\n" +
	"\x05alive\x18\x05 \x01(\bR\x05alive\"\xd9\x01\n" +
	"\fBattleReplay\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12%\n" +
	"\x0econfig_version\x18\x02 \x01(\tR\rconfigVersion\x12\x1f\n" +
	"\vconfig_hash\x18\x03 \x01(\tR\n" +
	"configHash\x12\"\n" +
	"\x05input\x18\x04 \x01(\v2\f.BattleInputR\x05input\x12$\n" +
	"\x06events\x18\x05 \x03(\v2\f.BattleEventR\x06events\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\"A\n" +
	"\x10BattleCreatedNtf\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\"d\n" +
	"\x0fBattleActionNtf\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\x12\"\n" +
	"\x05event\x18\x03 \x01(\v2\f.BattleEventR\x05event\"\xd8\x01\n" +
	"\x11BattleFinishedNtf\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\x12(\n" +
	"\aoutcome\x18\x03 \x01(\x0e2\x0e.BattleOutcomeR\aoutcome\x12'\n" +
	"\x05units\x18\x04 \x03(\v2\x11.BattleUnitResultR\x05units\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\x12%\n" +
	"\x06replay\x18\x06 \x01(\v2\r.BattleReplayR\x06replay\"I\n" +
	"\x18BattleResultConfirmedNtf\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid*]\n" +
	"\n" +
	"BattleTeam\x12\x1b\n" +
	"\x17BATTLE_TEAM_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14BATTLE_TEAM_ATTACKER\x10\x01\x12\x18\n" +
	"\x14BATTLE_TEAM_DEFENDER\x10\x02*\x8a\x01\n" +
	"\rBattleOutcome\x12\x1e\n" +
	"\x1aBATTLE_OUTCOME_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bBATTLE_OUTCOME_ATTACKER_WIN\x10\x01\x12\x1f\n" +
	"\x1bBATTLE_OUTCOME_DEFENDER_WIN\x10\x02\x12\x17\n" +
	"\x13BATTLE_OUTCOME_DRAW\x10\x03*\x98\x01\n" +
	"\n" +
	"TargetRule\x12\x1b\n" +
	"\x17TARGET_RULE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TARGET_RULE_ENEMY_SINGLE\x10\x01\x12\x19\n" +
	"\x15TARGET_RULE_ENEMY_ALL\x10\x02\x12\x1e\n" +
	"\x1aTARGET_RULE_ALLY_LOWEST_HP\x10\x03\x12\x14\n" +
	"\x10TARGET_RULE_SELF\x10\x04*u\n" +
	"\n" +
	"EffectType\x12\x1b\n" +
	"\x17EFFECT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EFFECT_TYPE_DAMAGE\x10\x01\x12\x14\n" +
	"\x10EFFECT_TYPE_HEAL\x10\x02\x12\x1c\n" +
	"\x18EFFECT_TYPE_APPLY_STATUS\x10\x03*\xa6\x01\n" +
	"\n" +
	"StatusType\x12\x1b\n" +
	"\x17STATUS_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10STATUS_TYPE_STUN\x10\x01\x12\x17\n" +
	"\x13STATUS_TYPE_SILENCE\x10\x02\x12\x13\n" +
	"\x0fSTATUS_TYPE_DOT\x10\x03\x12\x13\n" +
	"\x0fSTATUS_TYPE_HOT\x10\x04\x12\"\n" +
	"\x1eSTATUS_TYPE_ATTRIBUTE_MODIFIER\x10\x05*\xca\x02\n" +
	"\x0fBattleEventType\x12!\n" +
	"\x1dBATTLE_EVENT_TYPE_UNSPECIFIED\x10\x00\x12$\n" +
	" BATTLE_EVENT_TYPE_ACTION_STARTED\x10\x01\x12 \n" +
	"\x1cBATTLE_EVENT_TYPE_SKILL_USED\x10\x02\x12\x1c\n" +
	"\x18BATTLE_EVENT_TYPE_DAMAGE\x10\x03\x12\x1a\n" +
	"\x16BATTLE_EVENT_TYPE_HEAL\x10\x04\x12$\n" +
	" BATTLE_EVENT_TYPE_STATUS_APPLIED\x10\x05\x12$\n" +
	" BATTLE_EVENT_TYPE_ACTION_SKIPPED\x10\x06\x12\"\n" +
	"\x1eBATTLE_EVENT_TYPE_ACTION_ENDED\x10\a\x12\"\n" +
	"\x1eBATTLE_EVENT_TYPE_BATTLE_ENDED\x10\bB*Z(github.com/gogu-x/gogs/pb/cspb/pb_battleb\x06proto3"

var (
	file_cspb_battle_struct_proto_rawDescOnce sync.Once
	file_cspb_battle_struct_proto_rawDescData []byte
)

func file_cspb_battle_struct_proto_rawDescGZIP() []byte {
	file_cspb_battle_struct_proto_rawDescOnce.Do(func() {
		file_cspb_battle_struct_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cspb_battle_struct_proto_rawDesc), len(file_cspb_battle_struct_proto_rawDesc)))
	})
	return file_cspb_battle_struct_proto_rawDescData
}

var file_cspb_battle_struct_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_cspb_battle_struct_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cspb_battle_struct_proto_goTypes = []any{
	(BattleTeam)(0),                  // 0: BattleTeam
	(BattleOutcome)(0),               // 1: BattleOutcome
	(TargetRule)(0),                  // 2: TargetRule
	(EffectType)(0),                  // 3: EffectType
	(StatusType)(0),                  // 4: StatusType
	(BattleEventType)(0),             // 5: BattleEventType
	(*BattleCombatantInput)(nil),     // 6: BattleCombatantInput
	(*BattleInput)(nil),              // 7: BattleInput
	(*BattleEvent)(nil),              // 8: BattleEvent
	(*BattleUnitResult)(nil),         // 9: BattleUnitResult
	(*BattleReplay)(nil),             // 10: BattleReplay
	(*BattleCreatedNtf)(nil),         // 11: BattleCreatedNtf
	(*BattleActionNtf)(nil),          // 12: BattleActionNtf
	(*BattleFinishedNtf)(nil),        // 13: BattleFinishedNtf
	(*BattleResultConfirmedNtf)(nil), // 14: BattleResultConfirmedNtf
}
var file_cspb_battle_struct_proto_depIdxs = []int32{
	0,  // 0: BattleCombatantInput.team:type_name -> BattleTeam
	6,  // 1: BattleInput.combatants:type_name -> BattleCombatantInput
	5,  // 2: BattleEvent.type:type_name -> BattleEventType
	0,  // 3: BattleUnitResult.team:type_name -> BattleTeam
	7,  // 4: BattleReplay.input:type_name -> BattleInput
	8,  // 5: BattleReplay.events:type_name -> BattleEvent
	8,  // 6: BattleActionNtf.event:type_name -> BattleEvent
	1,  // 7: BattleFinishedNtf.outcome:type_name -> BattleOutcome
	9,  // 8: BattleFinishedNtf.units:type_name -> BattleUnitResult
	10, // 9: BattleFinishedNtf.replay:type_name -> BattleReplay
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_cspb_battle_struct_proto_init() }
func file_cspb_battle_struct_proto_init() {
	if File_cspb_battle_struct_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cspb_battle_struct_proto_rawDesc), len(file_cspb_battle_struct_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cspb_battle_struct_proto_goTypes,
		DependencyIndexes: file_cspb_battle_struct_proto_depIdxs,
		EnumInfos:         file_cspb_battle_struct_proto_enumTypes,
		MessageInfos:      file_cspb_battle_struct_proto_msgTypes,
	}.Build()
	File_cspb_battle_struct_proto = out.File
	file_cspb_battle_struct_proto_goTypes = nil
	file_cspb_battle_struct_proto_depIdxs = nil
}
