// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: cspb/chat/ack.proto

package pb_chat

import (
	pb_common "github.com/gogu-x/gogs/pb/cspb/pb_common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       pb_common.ErrCode      `protobuf:"varint,1,opt,name=errCode,proto3,enum=ErrCode" json:"errCode,omitempty"`
	State         int32                  `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatAck) Reset() {
	*x = ChatAck{}
	mi := &file_cspb_chat_ack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatAck) ProtoMessage() {}

func (x *ChatAck) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_chat_ack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatAck.ProtoReflect.Descriptor instead.
func (*ChatAck) Descriptor() ([]byte, []int) {
	return file_cspb_chat_ack_proto_rawDescGZIP(), []int{0}
}

func (x *ChatAck) GetErrCode() pb_common.ErrCode {
	if x != nil {
		return x.ErrCode
	}
	return pb_common.ErrCode(0)
}

func (x *ChatAck) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

var File_cspb_chat_ack_proto protoreflect.FileDescriptor

const file_cspb_chat_ack_proto_rawDesc = "" +
	"\n" +
	"\x13cspb/chat/ack.proto\x1a\x15cspb/comm/error.proto\"C\n" +
	"\aChatAck\x12\"\n" +
	"\aerrCode\x18\x01 \x01(\x0e2\b.ErrCodeR\aerrCode\x12\x14\n" +
	"\x05state\x18\x02 \x01(\x05R\x05stateB(Z&github.com/gogu-x/gogs/pb/cspb/pb_chatb\x06proto3"

var (
	file_cspb_chat_ack_proto_rawDescOnce sync.Once
	file_cspb_chat_ack_proto_rawDescData []byte
)

func file_cspb_chat_ack_proto_rawDescGZIP() []byte {
	file_cspb_chat_ack_proto_rawDescOnce.Do(func() {
		file_cspb_chat_ack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cspb_chat_ack_proto_rawDesc), len(file_cspb_chat_ack_proto_rawDesc)))
	})
	return file_cspb_chat_ack_proto_rawDescData
}

var file_cspb_chat_ack_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cspb_chat_ack_proto_goTypes = []any{
	(*ChatAck)(nil),        // 0: ChatAck
	(pb_common.ErrCode)(0), // 1: ErrCode
}
var file_cspb_chat_ack_proto_depIdxs = []int32{
	1, // 0: ChatAck.errCode:type_name -> ErrCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cspb_chat_ack_proto_init() }
func file_cspb_chat_ack_proto_init() {
	if File_cspb_chat_ack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cspb_chat_ack_proto_rawDesc), len(file_cspb_chat_ack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cspb_chat_ack_proto_goTypes,
		DependencyIndexes: file_cspb_chat_ack_proto_depIdxs,
		MessageInfos:      file_cspb_chat_ack_proto_msgTypes,
	}.Build()
	File_cspb_chat_ack_proto = out.File
	file_cspb_chat_ack_proto_goTypes = nil
	file_cspb_chat_ack_proto_depIdxs = nil
}
