// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: cspb/chat/req.proto

package pb_chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UID           uint64                 `protobuf:"varint,1,opt,name=uID,proto3" json:"uID,omitempty"`
	ServerID      uint32                 `protobuf:"varint,2,opt,name=serverID,proto3" json:"serverID,omitempty"`
	SessionID     string                 `protobuf:"bytes,3,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatReq) Reset() {
	*x = ChatReq{}
	mi := &file_cspb_chat_req_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReq) ProtoMessage() {}

func (x *ChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_chat_req_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReq.ProtoReflect.Descriptor instead.
func (*ChatReq) Descriptor() ([]byte, []int) {
	return file_cspb_chat_req_proto_rawDescGZIP(), []int{0}
}

func (x *ChatReq) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *ChatReq) GetServerID() uint32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *ChatReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *ChatReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ChatReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_cspb_chat_req_proto protoreflect.FileDescriptor

const file_cspb_chat_req_proto_rawDesc = "" +
	"\n" +
	"\x13cspb/chat/req.proto\"\x83\x01\n" +
	"\aChatReq\x12\x10\n" +
	"\x03uID\x18\x01 \x01(\x04R\x03uID\x12\x1a\n" +
	"\bserverID\x18\x02 \x01(\rR\bserverID\x12\x1c\n" +
	"\tsessionID\x18\x03 \x01(\tR\tsessionID\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontentB(Z&github.com/gogu-x/gogs/pb/cspb/pb_chatb\x06proto3"

var (
	file_cspb_chat_req_proto_rawDescOnce sync.Once
	file_cspb_chat_req_proto_rawDescData []byte
)

func file_cspb_chat_req_proto_rawDescGZIP() []byte {
	file_cspb_chat_req_proto_rawDescOnce.Do(func() {
		file_cspb_chat_req_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cspb_chat_req_proto_rawDesc), len(file_cspb_chat_req_proto_rawDesc)))
	})
	return file_cspb_chat_req_proto_rawDescData
}

var file_cspb_chat_req_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cspb_chat_req_proto_goTypes = []any{
	(*ChatReq)(nil), // 0: ChatReq
}
var file_cspb_chat_req_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cspb_chat_req_proto_init() }
func file_cspb_chat_req_proto_init() {
	if File_cspb_chat_req_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cspb_chat_req_proto_rawDesc), len(file_cspb_chat_req_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cspb_chat_req_proto_goTypes,
		DependencyIndexes: file_cspb_chat_req_proto_depIdxs,
		MessageInfos:      file_cspb_chat_req_proto_msgTypes,
	}.Build()
	File_cspb_chat_req_proto = out.File
	file_cspb_chat_req_proto_goTypes = nil
	file_cspb_chat_req_proto_depIdxs = nil
}
