// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: activity/activity_ack.proto

package protoActivity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetActivityListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*ActivityInfo        `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityListResp) Reset() {
	*x = GetActivityListResp{}
	mi := &file_activity_activity_ack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityListResp) ProtoMessage() {}

func (x *GetActivityListResp) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_ack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityListResp.ProtoReflect.Descriptor instead.
func (*GetActivityListResp) Descriptor() ([]byte, []int) {
	return file_activity_activity_ack_proto_rawDescGZIP(), []int{0}
}

func (x *GetActivityListResp) GetActivities() []*ActivityInfo {
	if x != nil {
		return x.Activities
	}
	return nil
}

type JoinActivityResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinActivityResp) Reset() {
	*x = JoinActivityResp{}
	mi := &file_activity_activity_ack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinActivityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinActivityResp) ProtoMessage() {}

func (x *JoinActivityResp) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_ack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinActivityResp.ProtoReflect.Descriptor instead.
func (*JoinActivityResp) Descriptor() ([]byte, []int) {
	return file_activity_activity_ack_proto_rawDescGZIP(), []int{1}
}

func (x *JoinActivityResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JoinActivityResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetProgressResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Progress      *ActivityProgress      `protobuf:"bytes,2,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressResp) Reset() {
	*x = GetProgressResp{}
	mi := &file_activity_activity_ack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressResp) ProtoMessage() {}

func (x *GetProgressResp) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_ack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressResp.ProtoReflect.Descriptor instead.
func (*GetProgressResp) Descriptor() ([]byte, []int) {
	return file_activity_activity_ack_proto_rawDescGZIP(), []int{2}
}

func (x *GetProgressResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetProgressResp) GetProgress() *ActivityProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type ClaimRewardResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRewardResp) Reset() {
	*x = ClaimRewardResp{}
	mi := &file_activity_activity_ack_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRewardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRewardResp) ProtoMessage() {}

func (x *ClaimRewardResp) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_ack_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRewardResp.ProtoReflect.Descriptor instead.
func (*ClaimRewardResp) Descriptor() ([]byte, []int) {
	return file_activity_activity_ack_proto_rawDescGZIP(), []int{3}
}

func (x *ClaimRewardResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ClaimRewardResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_activity_activity_ack_proto protoreflect.FileDescriptor

const file_activity_activity_ack_proto_rawDesc = "" +
	"\n" +
	"\x1bactivity/activity_ack.proto\x1a\x1eactivity/activity_common.proto\"D\n" +
	"\x13GetActivityListResp\x12-\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\r.ActivityInfoR\n" +
	"activities\"8\n" +
	"\x10JoinActivityResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"T\n" +
	"\x0fGetProgressResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12-\n" +
	"\bprogress\x18\x02 \x01(\v2\x11.ActivityProgressR\bprogress\"7\n" +
	"\x0fClaimRewardResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msgB)Z'github.com/gogu-x/gogs/pb/protoActivityb\x06proto3"

var (
	file_activity_activity_ack_proto_rawDescOnce sync.Once
	file_activity_activity_ack_proto_rawDescData []byte
)

func file_activity_activity_ack_proto_rawDescGZIP() []byte {
	file_activity_activity_ack_proto_rawDescOnce.Do(func() {
		file_activity_activity_ack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_activity_activity_ack_proto_rawDesc), len(file_activity_activity_ack_proto_rawDesc)))
	})
	return file_activity_activity_ack_proto_rawDescData
}

var file_activity_activity_ack_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_activity_activity_ack_proto_goTypes = []any{
	(*GetActivityListResp)(nil), // 0: GetActivityListResp
	(*JoinActivityResp)(nil),    // 1: JoinActivityResp
	(*GetProgressResp)(nil),     // 2: GetProgressResp
	(*ClaimRewardResp)(nil),     // 3: ClaimRewardResp
	(*ActivityInfo)(nil),        // 4: ActivityInfo
	(*ActivityProgress)(nil),    // 5: ActivityProgress
}
var file_activity_activity_ack_proto_depIdxs = []int32{
	4, // 0: GetActivityListResp.activities:type_name -> ActivityInfo
	5, // 1: GetProgressResp.progress:type_name -> ActivityProgress
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_activity_activity_ack_proto_init() }
func file_activity_activity_ack_proto_init() {
	if File_activity_activity_ack_proto != nil {
		return
	}
	file_activity_activity_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_activity_activity_ack_proto_rawDesc), len(file_activity_activity_ack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_activity_activity_ack_proto_goTypes,
		DependencyIndexes: file_activity_activity_ack_proto_depIdxs,
		MessageInfos:      file_activity_activity_ack_proto_msgTypes,
	}.Build()
	File_activity_activity_ack_proto = out.File
	file_activity_activity_ack_proto_goTypes = nil
	file_activity_activity_ack_proto_depIdxs = nil
}
