// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: activity/activity_req.proto

package protoActivity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetActivityListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityListReq) Reset() {
	*x = GetActivityListReq{}
	mi := &file_activity_activity_req_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityListReq) ProtoMessage() {}

func (x *GetActivityListReq) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_req_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityListReq.ProtoReflect.Descriptor instead.
func (*GetActivityListReq) Descriptor() ([]byte, []int) {
	return file_activity_activity_req_proto_rawDescGZIP(), []int{0}
}

type JoinActivityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ActivityId    uint64                 `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinActivityReq) Reset() {
	*x = JoinActivityReq{}
	mi := &file_activity_activity_req_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinActivityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinActivityReq) ProtoMessage() {}

func (x *JoinActivityReq) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_req_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinActivityReq.ProtoReflect.Descriptor instead.
func (*JoinActivityReq) Descriptor() ([]byte, []int) {
	return file_activity_activity_req_proto_rawDescGZIP(), []int{1}
}

func (x *JoinActivityReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *JoinActivityReq) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type GetProgressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ActivityId    uint64                 `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressReq) Reset() {
	*x = GetProgressReq{}
	mi := &file_activity_activity_req_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressReq) ProtoMessage() {}

func (x *GetProgressReq) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_req_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressReq.ProtoReflect.Descriptor instead.
func (*GetProgressReq) Descriptor() ([]byte, []int) {
	return file_activity_activity_req_proto_rawDescGZIP(), []int{2}
}

func (x *GetProgressReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetProgressReq) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type ClaimRewardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ActivityId    uint64                 `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRewardReq) Reset() {
	*x = ClaimRewardReq{}
	mi := &file_activity_activity_req_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRewardReq) ProtoMessage() {}

func (x *ClaimRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_req_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRewardReq.ProtoReflect.Descriptor instead.
func (*ClaimRewardReq) Descriptor() ([]byte, []int) {
	return file_activity_activity_req_proto_rawDescGZIP(), []int{3}
}

func (x *ClaimRewardReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ClaimRewardReq) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

var File_activity_activity_req_proto protoreflect.FileDescriptor

const file_activity_activity_req_proto_rawDesc = "" +
	"\n" +
	"\x1bactivity/activity_req.proto\"\x14\n" +
	"\x12GetActivityListReq\"D\n" +
	"\x0fJoinActivityReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x04R\n" +
	"activityId\"C\n" +
	"\x0eGetProgressReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x04R\n" +
	"activityId\"C\n" +
	"\x0eClaimRewardReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x04R\n" +
	"activityIdB)Z'github.com/gogu-x/gogs/pb/protoActivityb\x06proto3"

var (
	file_activity_activity_req_proto_rawDescOnce sync.Once
	file_activity_activity_req_proto_rawDescData []byte
)

func file_activity_activity_req_proto_rawDescGZIP() []byte {
	file_activity_activity_req_proto_rawDescOnce.Do(func() {
		file_activity_activity_req_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_activity_activity_req_proto_rawDesc), len(file_activity_activity_req_proto_rawDesc)))
	})
	return file_activity_activity_req_proto_rawDescData
}

var file_activity_activity_req_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_activity_activity_req_proto_goTypes = []any{
	(*GetActivityListReq)(nil), // 0: GetActivityListReq
	(*JoinActivityReq)(nil),    // 1: JoinActivityReq
	(*GetProgressReq)(nil),     // 2: GetProgressReq
	(*ClaimRewardReq)(nil),     // 3: ClaimRewardReq
}
var file_activity_activity_req_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_activity_activity_req_proto_init() }
func file_activity_activity_req_proto_init() {
	if File_activity_activity_req_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_activity_activity_req_proto_rawDesc), len(file_activity_activity_req_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_activity_activity_req_proto_goTypes,
		DependencyIndexes: file_activity_activity_req_proto_depIdxs,
		MessageInfos:      file_activity_activity_req_proto_msgTypes,
	}.Build()
	File_activity_activity_req_proto = out.File
	file_activity_activity_req_proto_goTypes = nil
	file_activity_activity_req_proto_depIdxs = nil
}
