// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: activity/activity_ack.proto

package protoActivity

import (
	protoCommon "github.com/gogu-x/gogs/pb/protoCommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetActivityListAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*ActivityInfo        `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityListAck) Reset() {
	*x = GetActivityListAck{}
	mi := &file_activity_activity_ack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityListAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityListAck) ProtoMessage() {}

func (x *GetActivityListAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_ack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityListAck.ProtoReflect.Descriptor instead.
func (*GetActivityListAck) Descriptor() ([]byte, []int) {
	return file_activity_activity_ack_proto_rawDescGZIP(), []int{0}
}

func (x *GetActivityListAck) GetActivities() []*ActivityInfo {
	if x != nil {
		return x.Activities
	}
	return nil
}

type JoinActivityAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          protoCommon.ErrCode    `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinActivityAck) Reset() {
	*x = JoinActivityAck{}
	mi := &file_activity_activity_ack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinActivityAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinActivityAck) ProtoMessage() {}

func (x *JoinActivityAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_ack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinActivityAck.ProtoReflect.Descriptor instead.
func (*JoinActivityAck) Descriptor() ([]byte, []int) {
	return file_activity_activity_ack_proto_rawDescGZIP(), []int{1}
}

func (x *JoinActivityAck) GetCode() protoCommon.ErrCode {
	if x != nil {
		return x.Code
	}
	return protoCommon.ErrCode(0)
}

func (x *JoinActivityAck) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetProgressAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          protoCommon.ErrCode    `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Progress      *ActivityProgress      `protobuf:"bytes,2,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressAck) Reset() {
	*x = GetProgressAck{}
	mi := &file_activity_activity_ack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressAck) ProtoMessage() {}

func (x *GetProgressAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_ack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressAck.ProtoReflect.Descriptor instead.
func (*GetProgressAck) Descriptor() ([]byte, []int) {
	return file_activity_activity_ack_proto_rawDescGZIP(), []int{2}
}

func (x *GetProgressAck) GetCode() protoCommon.ErrCode {
	if x != nil {
		return x.Code
	}
	return protoCommon.ErrCode(0)
}

func (x *GetProgressAck) GetProgress() *ActivityProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type ClaimRewardAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          protoCommon.ErrCode    `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRewardAck) Reset() {
	*x = ClaimRewardAck{}
	mi := &file_activity_activity_ack_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRewardAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRewardAck) ProtoMessage() {}

func (x *ClaimRewardAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_ack_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRewardAck.ProtoReflect.Descriptor instead.
func (*ClaimRewardAck) Descriptor() ([]byte, []int) {
	return file_activity_activity_ack_proto_rawDescGZIP(), []int{3}
}

func (x *ClaimRewardAck) GetCode() protoCommon.ErrCode {
	if x != nil {
		return x.Code
	}
	return protoCommon.ErrCode(0)
}

func (x *ClaimRewardAck) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_activity_activity_ack_proto protoreflect.FileDescriptor

const file_activity_activity_ack_proto_rawDesc = "" +
	"\n" +
	"\x1bactivity/activity_ack.proto\x1a\x1eactivity/activity_common.proto\x1a\x12common/error.proto\"C\n" +
	"\x12GetActivityListAck\x12-\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\r.ActivityInfoR\n" +
	"activities\"A\n" +
	"\x0fJoinActivityAck\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x0e2\b.ErrCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"]\n" +
	"\x0eGetProgressAck\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x0e2\b.ErrCodeR\x04code\x12-\n" +
	"\bprogress\x18\x02 \x01(\v2\x11.ActivityProgressR\bprogress\"@\n" +
	"\x0eClaimRewardAck\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x0e2\b.ErrCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msgB)Z'github.com/gogu-x/gogs/pb/protoActivityb\x06proto3"

var (
	file_activity_activity_ack_proto_rawDescOnce sync.Once
	file_activity_activity_ack_proto_rawDescData []byte
)

func file_activity_activity_ack_proto_rawDescGZIP() []byte {
	file_activity_activity_ack_proto_rawDescOnce.Do(func() {
		file_activity_activity_ack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_activity_activity_ack_proto_rawDesc), len(file_activity_activity_ack_proto_rawDesc)))
	})
	return file_activity_activity_ack_proto_rawDescData
}

var file_activity_activity_ack_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_activity_activity_ack_proto_goTypes = []any{
	(*GetActivityListAck)(nil), // 0: GetActivityListAck
	(*JoinActivityAck)(nil),    // 1: JoinActivityAck
	(*GetProgressAck)(nil),     // 2: GetProgressAck
	(*ClaimRewardAck)(nil),     // 3: ClaimRewardAck
	(*ActivityInfo)(nil),       // 4: ActivityInfo
	(protoCommon.ErrCode)(0),   // 5: ErrCode
	(*ActivityProgress)(nil),   // 6: ActivityProgress
}
var file_activity_activity_ack_proto_depIdxs = []int32{
	4, // 0: GetActivityListAck.activities:type_name -> ActivityInfo
	5, // 1: JoinActivityAck.code:type_name -> ErrCode
	5, // 2: GetProgressAck.code:type_name -> ErrCode
	6, // 3: GetProgressAck.progress:type_name -> ActivityProgress
	5, // 4: ClaimRewardAck.code:type_name -> ErrCode
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_activity_activity_ack_proto_init() }
func file_activity_activity_ack_proto_init() {
	if File_activity_activity_ack_proto != nil {
		return
	}
	file_activity_activity_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_activity_activity_ack_proto_rawDesc), len(file_activity_activity_ack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_activity_activity_ack_proto_goTypes,
		DependencyIndexes: file_activity_activity_ack_proto_depIdxs,
		MessageInfos:      file_activity_activity_ack_proto_msgTypes,
	}.Build()
	File_activity_activity_ack_proto = out.File
	file_activity_activity_ack_proto_goTypes = nil
	file_activity_activity_ack_proto_depIdxs = nil
}
