// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: activity/activity_common.proto

package protoActivity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 活动状态
type ActivityStatus int32

const (
	ActivityStatus_NOT_STARTED ActivityStatus = 0 // 未开始
	ActivityStatus_ONGOING     ActivityStatus = 1 // 进行中
	ActivityStatus_ENDED       ActivityStatus = 2 // 已结束
)

// Enum value maps for ActivityStatus.
var (
	ActivityStatus_name = map[int32]string{
		0: "NOT_STARTED",
		1: "ONGOING",
		2: "ENDED",
	}
	ActivityStatus_value = map[string]int32{
		"NOT_STARTED": 0,
		"ONGOING":     1,
		"ENDED":       2,
	}
)

func (x ActivityStatus) Enum() *ActivityStatus {
	p := new(ActivityStatus)
	*p = x
	return p
}

func (x ActivityStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_activity_activity_common_proto_enumTypes[0].Descriptor()
}

func (ActivityStatus) Type() protoreflect.EnumType {
	return &file_activity_activity_common_proto_enumTypes[0]
}

func (x ActivityStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityStatus.Descriptor instead.
func (ActivityStatus) EnumDescriptor() ([]byte, []int) {
	return file_activity_activity_common_proto_rawDescGZIP(), []int{0}
}

// 活动信息
type ActivityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        ActivityStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=ActivityStatus" json:"status,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityInfo) Reset() {
	*x = ActivityInfo{}
	mi := &file_activity_activity_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityInfo) ProtoMessage() {}

func (x *ActivityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityInfo.ProtoReflect.Descriptor instead.
func (*ActivityInfo) Descriptor() ([]byte, []int) {
	return file_activity_activity_common_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActivityInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActivityInfo) GetStatus() ActivityStatus {
	if x != nil {
		return x.Status
	}
	return ActivityStatus_NOT_STARTED
}

func (x *ActivityInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ActivityInfo) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// 玩家活动进度
type ActivityProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    uint64                 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Progress      int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	Target        int32                  `protobuf:"varint,4,opt,name=target,proto3" json:"target,omitempty"`
	Rewarded      bool                   `protobuf:"varint,5,opt,name=rewarded,proto3" json:"rewarded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityProgress) Reset() {
	*x = ActivityProgress{}
	mi := &file_activity_activity_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityProgress) ProtoMessage() {}

func (x *ActivityProgress) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityProgress.ProtoReflect.Descriptor instead.
func (*ActivityProgress) Descriptor() ([]byte, []int) {
	return file_activity_activity_common_proto_rawDescGZIP(), []int{1}
}

func (x *ActivityProgress) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ActivityProgress) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ActivityProgress) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ActivityProgress) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *ActivityProgress) GetRewarded() bool {
	if x != nil {
		return x.Rewarded
	}
	return false
}

var File_activity_activity_common_proto protoreflect.FileDescriptor

const file_activity_activity_common_proto_rawDesc = "" +
	"\n" +
	"\x1eactivity/activity_common.proto\"\x95\x01\n" +
	"\fActivityInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x06status\x18\x03 \x01(\x0e2\x0f.ActivityStatusR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\"\x95\x01\n" +
	"\x10ActivityProgress\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x04R\n" +
	"activityId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x12\x16\n" +
	"\x06target\x18\x04 \x01(\x05R\x06target\x12\x1a\n" +
	"\brewarded\x18\x05 \x01(\bR\brewarded*9\n" +
	"\x0eActivityStatus\x12\x0f\n" +
	"\vNOT_STARTED\x10\x00\x12\v\n" +
	"\aONGOING\x10\x01\x12\t\n" +
	"\x05ENDED\x10\x02B)Z'github.com/gogu-x/gogs/pb/protoActivityb\x06proto3"

var (
	file_activity_activity_common_proto_rawDescOnce sync.Once
	file_activity_activity_common_proto_rawDescData []byte
)

func file_activity_activity_common_proto_rawDescGZIP() []byte {
	file_activity_activity_common_proto_rawDescOnce.Do(func() {
		file_activity_activity_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_activity_activity_common_proto_rawDesc), len(file_activity_activity_common_proto_rawDesc)))
	})
	return file_activity_activity_common_proto_rawDescData
}

var file_activity_activity_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_activity_activity_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_activity_activity_common_proto_goTypes = []any{
	(ActivityStatus)(0),      // 0: ActivityStatus
	(*ActivityInfo)(nil),     // 1: ActivityInfo
	(*ActivityProgress)(nil), // 2: ActivityProgress
}
var file_activity_activity_common_proto_depIdxs = []int32{
	0, // 0: ActivityInfo.status:type_name -> ActivityStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_activity_activity_common_proto_init() }
func file_activity_activity_common_proto_init() {
	if File_activity_activity_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_activity_activity_common_proto_rawDesc), len(file_activity_activity_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_activity_activity_common_proto_goTypes,
		DependencyIndexes: file_activity_activity_common_proto_depIdxs,
		EnumInfos:         file_activity_activity_common_proto_enumTypes,
		MessageInfos:      file_activity_activity_common_proto_msgTypes,
	}.Build()
	File_activity_activity_common_proto = out.File
	file_activity_activity_common_proto_goTypes = nil
	file_activity_activity_common_proto_depIdxs = nil
}
