// Code generated by gen-register.py. DO NOT EDIT.
package pbregister

import (
	"github.com/gogu-x/gogs/codec"

	protoActivity "github.com/gogu-x/gogs/pb/protoActivity"
	protoChat "github.com/gogu-x/gogs/pb/protoChat"
	protoGateway "github.com/gogu-x/gogs/pb/protoGateway"
	protoGuild "github.com/gogu-x/gogs/pb/protoGuild"
	protoPlatform "github.com/gogu-x/gogs/pb/protoPlatform"
)

func init() {
	codec.RegisterMsg(
		&protoActivity.GetActivityListAck{},
		&protoActivity.JoinActivityAck{},
		&protoActivity.GetProgressAck{},
		&protoActivity.ClaimRewardAck{},
		&protoActivity.GetActivityListReq{},
		&protoActivity.JoinActivityReq{},
		&protoActivity.GetProgressReq{},
		&protoActivity.ClaimRewardReq{},
		&protoChat.ChatAck{},
		&protoChat.ChatReq{},
		&protoGateway.LoginAck{},
		&protoGateway.RegisterAck{},
		&protoGateway.ServerListAck{},
		&protoGateway.LoginReq{},
		&protoGateway.RegisterReq{},
		&protoGateway.LogoutReq{},
		&protoGateway.GetServerListReq{},
		&protoGateway.LoginGameReq{},
		&protoGuild.CreateGuildAck{},
		&protoGuild.JoinGuildAck{},
		&protoGuild.LeaveGuildAck{},
		&protoGuild.GetGuildAck{},
		&protoGuild.CreateGuildReq{},
		&protoGuild.JoinGuildReq{},
		&protoGuild.LeaveGuildReq{},
		&protoGuild.GetGuildReq{},
		&protoPlatform.RegisterReq{},
		&protoPlatform.AuthLoginReq{},
		&protoPlatform.AuthAck{},
		&protoPlatform.VerifyTokenReq{},
		&protoPlatform.VerifyAck{},
		&protoPlatform.GetServerListReq{},
		&protoPlatform.ServerListAck{},
		&protoPlatform.CreateOrderReq{},
		&protoPlatform.OrderAck{},
		&protoPlatform.QueryOrderReq{},
	)
}
