// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: guild/guild_ack.proto

package protoGuild

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGuildResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Guild         *GuildInfo             `protobuf:"bytes,3,opt,name=guild,proto3" json:"guild,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGuildResp) Reset() {
	*x = CreateGuildResp{}
	mi := &file_guild_guild_ack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGuildResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGuildResp) ProtoMessage() {}

func (x *CreateGuildResp) ProtoReflect() protoreflect.Message {
	mi := &file_guild_guild_ack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGuildResp.ProtoReflect.Descriptor instead.
func (*CreateGuildResp) Descriptor() ([]byte, []int) {
	return file_guild_guild_ack_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGuildResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateGuildResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateGuildResp) GetGuild() *GuildInfo {
	if x != nil {
		return x.Guild
	}
	return nil
}

type JoinGuildResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGuildResp) Reset() {
	*x = JoinGuildResp{}
	mi := &file_guild_guild_ack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGuildResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGuildResp) ProtoMessage() {}

func (x *JoinGuildResp) ProtoReflect() protoreflect.Message {
	mi := &file_guild_guild_ack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGuildResp.ProtoReflect.Descriptor instead.
func (*JoinGuildResp) Descriptor() ([]byte, []int) {
	return file_guild_guild_ack_proto_rawDescGZIP(), []int{1}
}

func (x *JoinGuildResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JoinGuildResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type LeaveGuildResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGuildResp) Reset() {
	*x = LeaveGuildResp{}
	mi := &file_guild_guild_ack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGuildResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGuildResp) ProtoMessage() {}

func (x *LeaveGuildResp) ProtoReflect() protoreflect.Message {
	mi := &file_guild_guild_ack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGuildResp.ProtoReflect.Descriptor instead.
func (*LeaveGuildResp) Descriptor() ([]byte, []int) {
	return file_guild_guild_ack_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveGuildResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LeaveGuildResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetGuildResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Guild         *GuildInfo             `protobuf:"bytes,2,opt,name=guild,proto3" json:"guild,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGuildResp) Reset() {
	*x = GetGuildResp{}
	mi := &file_guild_guild_ack_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGuildResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildResp) ProtoMessage() {}

func (x *GetGuildResp) ProtoReflect() protoreflect.Message {
	mi := &file_guild_guild_ack_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildResp.ProtoReflect.Descriptor instead.
func (*GetGuildResp) Descriptor() ([]byte, []int) {
	return file_guild_guild_ack_proto_rawDescGZIP(), []int{3}
}

func (x *GetGuildResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGuildResp) GetGuild() *GuildInfo {
	if x != nil {
		return x.Guild
	}
	return nil
}

var File_guild_guild_ack_proto protoreflect.FileDescriptor

const file_guild_guild_ack_proto_rawDesc = "" +
	"\n" +
	"\x15guild/guild_ack.proto\x1a\x18guild/guild_common.proto\"Y\n" +
	"\x0fCreateGuildResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12 \n" +
	"\x05guild\x18\x03 \x01(\v2\n" +
	".GuildInfoR\x05guild\"5\n" +
	"\rJoinGuildResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"6\n" +
	"\x0eLeaveGuildResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"D\n" +
	"\fGetGuildResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12 \n" +
	"\x05guild\x18\x02 \x01(\v2\n" +
	".GuildInfoR\x05guildB&Z$github.com/gogu-x/gogs/pb/protoGuildb\x06proto3"

var (
	file_guild_guild_ack_proto_rawDescOnce sync.Once
	file_guild_guild_ack_proto_rawDescData []byte
)

func file_guild_guild_ack_proto_rawDescGZIP() []byte {
	file_guild_guild_ack_proto_rawDescOnce.Do(func() {
		file_guild_guild_ack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guild_guild_ack_proto_rawDesc), len(file_guild_guild_ack_proto_rawDesc)))
	})
	return file_guild_guild_ack_proto_rawDescData
}

var file_guild_guild_ack_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_guild_guild_ack_proto_goTypes = []any{
	(*CreateGuildResp)(nil), // 0: CreateGuildResp
	(*JoinGuildResp)(nil),   // 1: JoinGuildResp
	(*LeaveGuildResp)(nil),  // 2: LeaveGuildResp
	(*GetGuildResp)(nil),    // 3: GetGuildResp
	(*GuildInfo)(nil),       // 4: GuildInfo
}
var file_guild_guild_ack_proto_depIdxs = []int32{
	4, // 0: CreateGuildResp.guild:type_name -> GuildInfo
	4, // 1: GetGuildResp.guild:type_name -> GuildInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_guild_guild_ack_proto_init() }
func file_guild_guild_ack_proto_init() {
	if File_guild_guild_ack_proto != nil {
		return
	}
	file_guild_guild_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guild_guild_ack_proto_rawDesc), len(file_guild_guild_ack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_guild_guild_ack_proto_goTypes,
		DependencyIndexes: file_guild_guild_ack_proto_depIdxs,
		MessageInfos:      file_guild_guild_ack_proto_msgTypes,
	}.Build()
	File_guild_guild_ack_proto = out.File
	file_guild_guild_ack_proto_goTypes = nil
	file_guild_guild_ack_proto_depIdxs = nil
}
