// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: guild/guild_ack.proto

package protoGuild

import (
	protoCommon "github.com/gogu-x/gogs/pb/protoCommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGuildAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          protoCommon.ErrCode    `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Guild         *GuildInfo             `protobuf:"bytes,3,opt,name=guild,proto3" json:"guild,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGuildAck) Reset() {
	*x = CreateGuildAck{}
	mi := &file_guild_guild_ack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGuildAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGuildAck) ProtoMessage() {}

func (x *CreateGuildAck) ProtoReflect() protoreflect.Message {
	mi := &file_guild_guild_ack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGuildAck.ProtoReflect.Descriptor instead.
func (*CreateGuildAck) Descriptor() ([]byte, []int) {
	return file_guild_guild_ack_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGuildAck) GetCode() protoCommon.ErrCode {
	if x != nil {
		return x.Code
	}
	return protoCommon.ErrCode(0)
}

func (x *CreateGuildAck) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateGuildAck) GetGuild() *GuildInfo {
	if x != nil {
		return x.Guild
	}
	return nil
}

type JoinGuildAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          protoCommon.ErrCode    `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGuildAck) Reset() {
	*x = JoinGuildAck{}
	mi := &file_guild_guild_ack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGuildAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGuildAck) ProtoMessage() {}

func (x *JoinGuildAck) ProtoReflect() protoreflect.Message {
	mi := &file_guild_guild_ack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGuildAck.ProtoReflect.Descriptor instead.
func (*JoinGuildAck) Descriptor() ([]byte, []int) {
	return file_guild_guild_ack_proto_rawDescGZIP(), []int{1}
}

func (x *JoinGuildAck) GetCode() protoCommon.ErrCode {
	if x != nil {
		return x.Code
	}
	return protoCommon.ErrCode(0)
}

func (x *JoinGuildAck) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type LeaveGuildAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          protoCommon.ErrCode    `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGuildAck) Reset() {
	*x = LeaveGuildAck{}
	mi := &file_guild_guild_ack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGuildAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGuildAck) ProtoMessage() {}

func (x *LeaveGuildAck) ProtoReflect() protoreflect.Message {
	mi := &file_guild_guild_ack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGuildAck.ProtoReflect.Descriptor instead.
func (*LeaveGuildAck) Descriptor() ([]byte, []int) {
	return file_guild_guild_ack_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveGuildAck) GetCode() protoCommon.ErrCode {
	if x != nil {
		return x.Code
	}
	return protoCommon.ErrCode(0)
}

func (x *LeaveGuildAck) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetGuildAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          protoCommon.ErrCode    `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Guild         *GuildInfo             `protobuf:"bytes,2,opt,name=guild,proto3" json:"guild,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGuildAck) Reset() {
	*x = GetGuildAck{}
	mi := &file_guild_guild_ack_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGuildAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildAck) ProtoMessage() {}

func (x *GetGuildAck) ProtoReflect() protoreflect.Message {
	mi := &file_guild_guild_ack_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildAck.ProtoReflect.Descriptor instead.
func (*GetGuildAck) Descriptor() ([]byte, []int) {
	return file_guild_guild_ack_proto_rawDescGZIP(), []int{3}
}

func (x *GetGuildAck) GetCode() protoCommon.ErrCode {
	if x != nil {
		return x.Code
	}
	return protoCommon.ErrCode(0)
}

func (x *GetGuildAck) GetGuild() *GuildInfo {
	if x != nil {
		return x.Guild
	}
	return nil
}

var File_guild_guild_ack_proto protoreflect.FileDescriptor

const file_guild_guild_ack_proto_rawDesc = "" +
	"\n" +
	"\x15guild/guild_ack.proto\x1a\x18guild/guild_common.proto\x1a\x12common/error.proto\"b\n" +
	"\x0eCreateGuildAck\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x0e2\b.ErrCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12 \n" +
	"\x05guild\x18\x03 \x01(\v2\n" +
	".GuildInfoR\x05guild\">\n" +
	"\fJoinGuildAck\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x0e2\b.ErrCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"?\n" +
	"\rLeaveGuildAck\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x0e2\b.ErrCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"M\n" +
	"\vGetGuildAck\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x0e2\b.ErrCodeR\x04code\x12 \n" +
	"\x05guild\x18\x02 \x01(\v2\n" +
	".GuildInfoR\x05guildB&Z$github.com/gogu-x/gogs/pb/protoGuildb\x06proto3"

var (
	file_guild_guild_ack_proto_rawDescOnce sync.Once
	file_guild_guild_ack_proto_rawDescData []byte
)

func file_guild_guild_ack_proto_rawDescGZIP() []byte {
	file_guild_guild_ack_proto_rawDescOnce.Do(func() {
		file_guild_guild_ack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guild_guild_ack_proto_rawDesc), len(file_guild_guild_ack_proto_rawDesc)))
	})
	return file_guild_guild_ack_proto_rawDescData
}

var file_guild_guild_ack_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_guild_guild_ack_proto_goTypes = []any{
	(*CreateGuildAck)(nil),   // 0: CreateGuildAck
	(*JoinGuildAck)(nil),     // 1: JoinGuildAck
	(*LeaveGuildAck)(nil),    // 2: LeaveGuildAck
	(*GetGuildAck)(nil),      // 3: GetGuildAck
	(protoCommon.ErrCode)(0), // 4: ErrCode
	(*GuildInfo)(nil),        // 5: GuildInfo
}
var file_guild_guild_ack_proto_depIdxs = []int32{
	4, // 0: CreateGuildAck.code:type_name -> ErrCode
	5, // 1: CreateGuildAck.guild:type_name -> GuildInfo
	4, // 2: JoinGuildAck.code:type_name -> ErrCode
	4, // 3: LeaveGuildAck.code:type_name -> ErrCode
	4, // 4: GetGuildAck.code:type_name -> ErrCode
	5, // 5: GetGuildAck.guild:type_name -> GuildInfo
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_guild_guild_ack_proto_init() }
func file_guild_guild_ack_proto_init() {
	if File_guild_guild_ack_proto != nil {
		return
	}
	file_guild_guild_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guild_guild_ack_proto_rawDesc), len(file_guild_guild_ack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_guild_guild_ack_proto_goTypes,
		DependencyIndexes: file_guild_guild_ack_proto_depIdxs,
		MessageInfos:      file_guild_guild_ack_proto_msgTypes,
	}.Build()
	File_guild_guild_ack_proto = out.File
	file_guild_guild_ack_proto_goTypes = nil
	file_guild_guild_ack_proto_depIdxs = nil
}
