// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: guild/guild_common.proto

package protoGuild

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 工会职位
type GuildRole int32

const (
	GuildRole_MEMBER  GuildRole = 0 // 普通成员
	GuildRole_OFFICER GuildRole = 1 // 副会长
	GuildRole_LEADER  GuildRole = 2 // 会长
)

// Enum value maps for GuildRole.
var (
	GuildRole_name = map[int32]string{
		0: "MEMBER",
		1: "OFFICER",
		2: "LEADER",
	}
	GuildRole_value = map[string]int32{
		"MEMBER":  0,
		"OFFICER": 1,
		"LEADER":  2,
	}
)

func (x GuildRole) Enum() *GuildRole {
	p := new(GuildRole)
	*p = x
	return p
}

func (x GuildRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GuildRole) Descriptor() protoreflect.EnumDescriptor {
	return file_guild_guild_common_proto_enumTypes[0].Descriptor()
}

func (GuildRole) Type() protoreflect.EnumType {
	return &file_guild_guild_common_proto_enumTypes[0]
}

func (x GuildRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GuildRole.Descriptor instead.
func (GuildRole) EnumDescriptor() ([]byte, []int) {
	return file_guild_guild_common_proto_rawDescGZIP(), []int{0}
}

// 工会成员快照
type GuildMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level         uint32                 `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Role          GuildRole              `protobuf:"varint,4,opt,name=role,proto3,enum=GuildRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildMember) Reset() {
	*x = GuildMember{}
	mi := &file_guild_guild_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildMember) ProtoMessage() {}

func (x *GuildMember) ProtoReflect() protoreflect.Message {
	mi := &file_guild_guild_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildMember.ProtoReflect.Descriptor instead.
func (*GuildMember) Descriptor() ([]byte, []int) {
	return file_guild_guild_common_proto_rawDescGZIP(), []int{0}
}

func (x *GuildMember) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GuildMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GuildMember) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GuildMember) GetRole() GuildRole {
	if x != nil {
		return x.Role
	}
	return GuildRole_MEMBER
}

// 工会信息
type GuildInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       uint64                 `protobuf:"varint,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Notice        string                 `protobuf:"bytes,3,opt,name=notice,proto3" json:"notice,omitempty"`
	Leader        uint64                 `protobuf:"varint,4,opt,name=leader,proto3" json:"leader,omitempty"`
	Members       []*GuildMember         `protobuf:"bytes,5,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildInfo) Reset() {
	*x = GuildInfo{}
	mi := &file_guild_guild_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildInfo) ProtoMessage() {}

func (x *GuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_guild_guild_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildInfo.ProtoReflect.Descriptor instead.
func (*GuildInfo) Descriptor() ([]byte, []int) {
	return file_guild_guild_common_proto_rawDescGZIP(), []int{1}
}

func (x *GuildInfo) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *GuildInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GuildInfo) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *GuildInfo) GetLeader() uint64 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *GuildInfo) GetMembers() []*GuildMember {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_guild_guild_common_proto protoreflect.FileDescriptor

const file_guild_guild_common_proto_rawDesc = "" +
	"\n" +
	"\x18guild/guild_common.proto\"i\n" +
	"\vGuildMember\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\rR\x05level\x12\x1e\n" +
	"\x04role\x18\x04 \x01(\x0e2\n" +
	".GuildRoleR\x04role\"\x92\x01\n" +
	"\tGuildInfo\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\x04R\aguildId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06notice\x18\x03 \x01(\tR\x06notice\x12\x16\n" +
	"\x06leader\x18\x04 \x01(\x04R\x06leader\x12&\n" +
	"\amembers\x18\x05 \x03(\v2\f.GuildMemberR\amembers*0\n" +
	"\tGuildRole\x12\n" +
	"\n" +
	"\x06MEMBER\x10\x00\x12\v\n" +
	"\aOFFICER\x10\x01\x12\n" +
	"\n" +
	"\x06LEADER\x10\x02B&Z$github.com/gogu-x/gogs/pb/protoGuildb\x06proto3"

var (
	file_guild_guild_common_proto_rawDescOnce sync.Once
	file_guild_guild_common_proto_rawDescData []byte
)

func file_guild_guild_common_proto_rawDescGZIP() []byte {
	file_guild_guild_common_proto_rawDescOnce.Do(func() {
		file_guild_guild_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guild_guild_common_proto_rawDesc), len(file_guild_guild_common_proto_rawDesc)))
	})
	return file_guild_guild_common_proto_rawDescData
}

var file_guild_guild_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_guild_guild_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_guild_guild_common_proto_goTypes = []any{
	(GuildRole)(0),      // 0: GuildRole
	(*GuildMember)(nil), // 1: GuildMember
	(*GuildInfo)(nil),   // 2: GuildInfo
}
var file_guild_guild_common_proto_depIdxs = []int32{
	0, // 0: GuildMember.role:type_name -> GuildRole
	1, // 1: GuildInfo.members:type_name -> GuildMember
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_guild_guild_common_proto_init() }
func file_guild_guild_common_proto_init() {
	if File_guild_guild_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guild_guild_common_proto_rawDesc), len(file_guild_guild_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_guild_guild_common_proto_goTypes,
		DependencyIndexes: file_guild_guild_common_proto_depIdxs,
		EnumInfos:         file_guild_guild_common_proto_enumTypes,
		MessageInfos:      file_guild_guild_common_proto_msgTypes,
	}.Build()
	File_guild_guild_common_proto = out.File
	file_guild_guild_common_proto_goTypes = nil
	file_guild_guild_common_proto_depIdxs = nil
}
