// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: cspb/equipment/equipment.proto

package pb_equipment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 装备槽位；客户端展示文字仅由客户端本地化，服务端使用枚举进行校验。
type EquipSlot int32

const (
	EquipSlot_EQUIP_SLOT_UNSPECIFIED EquipSlot = 0
	EquipSlot_EQUIP_SLOT_WEAPON      EquipSlot = 1
	EquipSlot_EQUIP_SLOT_HEAD        EquipSlot = 2
	EquipSlot_EQUIP_SLOT_BODY        EquipSlot = 3
	EquipSlot_EQUIP_SLOT_HAND        EquipSlot = 4
	EquipSlot_EQUIP_SLOT_WAIST       EquipSlot = 5
	EquipSlot_EQUIP_SLOT_FOOT        EquipSlot = 6
)

// Enum value maps for EquipSlot.
var (
	EquipSlot_name = map[int32]string{
		0: "EQUIP_SLOT_UNSPECIFIED",
		1: "EQUIP_SLOT_WEAPON",
		2: "EQUIP_SLOT_HEAD",
		3: "EQUIP_SLOT_BODY",
		4: "EQUIP_SLOT_HAND",
		5: "EQUIP_SLOT_WAIST",
		6: "EQUIP_SLOT_FOOT",
	}
	EquipSlot_value = map[string]int32{
		"EQUIP_SLOT_UNSPECIFIED": 0,
		"EQUIP_SLOT_WEAPON":      1,
		"EQUIP_SLOT_HEAD":        2,
		"EQUIP_SLOT_BODY":        3,
		"EQUIP_SLOT_HAND":        4,
		"EQUIP_SLOT_WAIST":       5,
		"EQUIP_SLOT_FOOT":        6,
	}
)

func (x EquipSlot) Enum() *EquipSlot {
	p := new(EquipSlot)
	*p = x
	return p
}

func (x EquipSlot) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EquipSlot) Descriptor() protoreflect.EnumDescriptor {
	return file_cspb_equipment_equipment_proto_enumTypes[0].Descriptor()
}

func (EquipSlot) Type() protoreflect.EnumType {
	return &file_cspb_equipment_equipment_proto_enumTypes[0]
}

func (x EquipSlot) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EquipSlot.Descriptor instead.
func (EquipSlot) EnumDescriptor() ([]byte, []int) {
	return file_cspb_equipment_equipment_proto_rawDescGZIP(), []int{0}
}

type EquipmentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ConfigId      int32                  `protobuf:"varint,2,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	Slot          EquipSlot              `protobuf:"varint,3,opt,name=slot,proto3,enum=EquipSlot" json:"slot,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	RefineLevel   int32                  `protobuf:"varint,5,opt,name=refine_level,json=refineLevel,proto3" json:"refine_level,omitempty"`
	Equipped      bool                   `protobuf:"varint,6,opt,name=equipped,proto3" json:"equipped,omitempty"`
	MaxHp         int64                  `protobuf:"varint,7,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Attack        int64                  `protobuf:"varint,8,opt,name=attack,proto3" json:"attack,omitempty"`
	Defense       int64                  `protobuf:"varint,9,opt,name=defense,proto3" json:"defense,omitempty"`
	Speed         int64                  `protobuf:"varint,10,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentItem) Reset() {
	*x = EquipmentItem{}
	mi := &file_cspb_equipment_equipment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentItem) ProtoMessage() {}

func (x *EquipmentItem) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_equipment_equipment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentItem.ProtoReflect.Descriptor instead.
func (*EquipmentItem) Descriptor() ([]byte, []int) {
	return file_cspb_equipment_equipment_proto_rawDescGZIP(), []int{0}
}

func (x *EquipmentItem) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *EquipmentItem) GetConfigId() int32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *EquipmentItem) GetSlot() EquipSlot {
	if x != nil {
		return x.Slot
	}
	return EquipSlot_EQUIP_SLOT_UNSPECIFIED
}

func (x *EquipmentItem) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *EquipmentItem) GetRefineLevel() int32 {
	if x != nil {
		return x.RefineLevel
	}
	return 0
}

func (x *EquipmentItem) GetEquipped() bool {
	if x != nil {
		return x.Equipped
	}
	return false
}

func (x *EquipmentItem) GetMaxHp() int64 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *EquipmentItem) GetAttack() int64 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *EquipmentItem) GetDefense() int64 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *EquipmentItem) GetSpeed() int64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type RoleEquipmentData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleLevel     int32                  `protobuf:"varint,2,opt,name=role_level,json=roleLevel,proto3" json:"role_level,omitempty"`
	MaxHp         int64                  `protobuf:"varint,3,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Attack        int64                  `protobuf:"varint,4,opt,name=attack,proto3" json:"attack,omitempty"`
	Defense       int64                  `protobuf:"varint,5,opt,name=defense,proto3" json:"defense,omitempty"`
	Speed         int64                  `protobuf:"varint,6,opt,name=speed,proto3" json:"speed,omitempty"`
	Items         []*EquipmentItem       `protobuf:"bytes,7,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleEquipmentData) Reset() {
	*x = RoleEquipmentData{}
	mi := &file_cspb_equipment_equipment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleEquipmentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleEquipmentData) ProtoMessage() {}

func (x *RoleEquipmentData) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_equipment_equipment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleEquipmentData.ProtoReflect.Descriptor instead.
func (*RoleEquipmentData) Descriptor() ([]byte, []int) {
	return file_cspb_equipment_equipment_proto_rawDescGZIP(), []int{1}
}

func (x *RoleEquipmentData) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RoleEquipmentData) GetRoleLevel() int32 {
	if x != nil {
		return x.RoleLevel
	}
	return 0
}

func (x *RoleEquipmentData) GetMaxHp() int64 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *RoleEquipmentData) GetAttack() int64 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *RoleEquipmentData) GetDefense() int64 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *RoleEquipmentData) GetSpeed() int64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *RoleEquipmentData) GetItems() []*EquipmentItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 登录后与打开角色装备页时拉取权威装备清单。
type GetRoleEquipmentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UID           uint64                 `protobuf:"varint,101,opt,name=uID,proto3" json:"uID,omitempty"`
	ServerID      uint32                 `protobuf:"varint,102,opt,name=serverID,proto3" json:"serverID,omitempty"`
	SessionID     string                 `protobuf:"bytes,103,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleEquipmentReq) Reset() {
	*x = GetRoleEquipmentReq{}
	mi := &file_cspb_equipment_equipment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleEquipmentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleEquipmentReq) ProtoMessage() {}

func (x *GetRoleEquipmentReq) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_equipment_equipment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleEquipmentReq.ProtoReflect.Descriptor instead.
func (*GetRoleEquipmentReq) Descriptor() ([]byte, []int) {
	return file_cspb_equipment_equipment_proto_rawDescGZIP(), []int{2}
}

func (x *GetRoleEquipmentReq) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *GetRoleEquipmentReq) GetServerID() uint32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *GetRoleEquipmentReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type GetRoleEquipmentAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *RoleEquipmentData     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleEquipmentAck) Reset() {
	*x = GetRoleEquipmentAck{}
	mi := &file_cspb_equipment_equipment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleEquipmentAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleEquipmentAck) ProtoMessage() {}

func (x *GetRoleEquipmentAck) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_equipment_equipment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleEquipmentAck.ProtoReflect.Descriptor instead.
func (*GetRoleEquipmentAck) Descriptor() ([]byte, []int) {
	return file_cspb_equipment_equipment_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoleEquipmentAck) GetData() *RoleEquipmentData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetRoleEquipmentAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// equipment_id 为空表示卸下指定槽位；否则服务端校验归属与槽位后穿戴。
type ChangeRoleEquipmentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UID           uint64                 `protobuf:"varint,101,opt,name=uID,proto3" json:"uID,omitempty"`
	ServerID      uint32                 `protobuf:"varint,102,opt,name=serverID,proto3" json:"serverID,omitempty"`
	SessionID     string                 `protobuf:"bytes,103,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Slot          EquipSlot              `protobuf:"varint,1,opt,name=slot,proto3,enum=EquipSlot" json:"slot,omitempty"`
	EquipmentId   string                 `protobuf:"bytes,2,opt,name=equipment_id,json=equipmentId,proto3" json:"equipment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRoleEquipmentReq) Reset() {
	*x = ChangeRoleEquipmentReq{}
	mi := &file_cspb_equipment_equipment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRoleEquipmentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRoleEquipmentReq) ProtoMessage() {}

func (x *ChangeRoleEquipmentReq) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_equipment_equipment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRoleEquipmentReq.ProtoReflect.Descriptor instead.
func (*ChangeRoleEquipmentReq) Descriptor() ([]byte, []int) {
	return file_cspb_equipment_equipment_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeRoleEquipmentReq) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *ChangeRoleEquipmentReq) GetServerID() uint32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *ChangeRoleEquipmentReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *ChangeRoleEquipmentReq) GetSlot() EquipSlot {
	if x != nil {
		return x.Slot
	}
	return EquipSlot_EQUIP_SLOT_UNSPECIFIED
}

func (x *ChangeRoleEquipmentReq) GetEquipmentId() string {
	if x != nil {
		return x.EquipmentId
	}
	return ""
}

type ChangeRoleEquipmentAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *RoleEquipmentData     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRoleEquipmentAck) Reset() {
	*x = ChangeRoleEquipmentAck{}
	mi := &file_cspb_equipment_equipment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRoleEquipmentAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRoleEquipmentAck) ProtoMessage() {}

func (x *ChangeRoleEquipmentAck) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_equipment_equipment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRoleEquipmentAck.ProtoReflect.Descriptor instead.
func (*ChangeRoleEquipmentAck) Descriptor() ([]byte, []int) {
	return file_cspb_equipment_equipment_proto_rawDescGZIP(), []int{5}
}

func (x *ChangeRoleEquipmentAck) GetData() *RoleEquipmentData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChangeRoleEquipmentAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_cspb_equipment_equipment_proto protoreflect.FileDescriptor

const file_cspb_equipment_equipment_proto_rawDesc = "" +
	"\n" +
	"\x1ecspb/equipment/equipment.proto\"\xa1\x02\n" +
	"\rEquipmentItem\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1b\n" +
	"\tconfig_id\x18\x02 \x01(\x05R\bconfigId\x12\x1e\n" +
	"\x04slot\x18\x03 \x01(\x0e2\n" +
	".EquipSlotR\x04slot\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12!\n" +
	"\frefine_level\x18\x05 \x01(\x05R\vrefineLevel\x12\x1a\n" +
	"\bequipped\x18\x06 \x01(\bR\bequipped\x12\x15\n" +
	"\x06max_hp\x18\a \x01(\x03R\x05maxHp\x12\x16\n" +
	"\x06attack\x18\b \x01(\x03R\x06attack\x12\x18\n" +
	"\adefense\x18\t \x01(\x03R\adefense\x12\x14\n" +
	"\x05speed\x18\n" +
	" \x01(\x03R\x05speed\"\xd0\x01\n" +
	"\x11RoleEquipmentData\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12\x1d\n" +
	"\n" +
	"role_level\x18\x02 \x01(\x05R\troleLevel\x12\x15\n" +
	"\x06max_hp\x18\x03 \x01(\x03R\x05maxHp\x12\x16\n" +
	"\x06attack\x18\x04 \x01(\x03R\x06attack\x12\x18\n" +
	"\adefense\x18\x05 \x01(\x03R\adefense\x12\x14\n" +
	"\x05speed\x18\x06 \x01(\x03R\x05speed\x12$\n" +
	"\x05items\x18\a \x03(\v2\x0e.EquipmentItemR\x05items\"a\n" +
	"\x13GetRoleEquipmentReq\x12\x10\n" +
	"\x03uID\x18e \x01(\x04R\x03uID\x12\x1a\n" +
	"\bserverID\x18f \x01(\rR\bserverID\x12\x1c\n" +
	"\tsessionID\x18g \x01(\tR\tsessionID\"S\n" +
	"\x13GetRoleEquipmentAck\x12&\n" +
	"\x04data\x18\x01 \x01(\v2\x12.RoleEquipmentDataR\x04data\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa7\x01\n" +
	"\x16ChangeRoleEquipmentReq\x12\x10\n" +
	"\x03uID\x18e \x01(\x04R\x03uID\x12\x1a\n" +
	"\bserverID\x18f \x01(\rR\bserverID\x12\x1c\n" +
	"\tsessionID\x18g \x01(\tR\tsessionID\x12\x1e\n" +
	"\x04slot\x18\x01 \x01(\x0e2\n" +
	".EquipSlotR\x04slot\x12!\n" +
	"\fequipment_id\x18\x02 \x01(\tR\vequipmentId\"V\n" +
	"\x16ChangeRoleEquipmentAck\x12&\n" +
	"\x04data\x18\x01 \x01(\v2\x12.RoleEquipmentDataR\x04data\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*\xa8\x01\n" +
	"\tEquipSlot\x12\x1a\n" +
	"\x16EQUIP_SLOT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EQUIP_SLOT_WEAPON\x10\x01\x12\x13\n" +
	"\x0fEQUIP_SLOT_HEAD\x10\x02\x12\x13\n" +
	"\x0fEQUIP_SLOT_BODY\x10\x03\x12\x13\n" +
	"\x0fEQUIP_SLOT_HAND\x10\x04\x12\x14\n" +
	"\x10EQUIP_SLOT_WAIST\x10\x05\x12\x13\n" +
	"\x0fEQUIP_SLOT_FOOT\x10\x06B-Z+github.com/gogu-x/gogs/pb/cspb/pb_equipmentb\x06proto3"

var (
	file_cspb_equipment_equipment_proto_rawDescOnce sync.Once
	file_cspb_equipment_equipment_proto_rawDescData []byte
)

func file_cspb_equipment_equipment_proto_rawDescGZIP() []byte {
	file_cspb_equipment_equipment_proto_rawDescOnce.Do(func() {
		file_cspb_equipment_equipment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cspb_equipment_equipment_proto_rawDesc), len(file_cspb_equipment_equipment_proto_rawDesc)))
	})
	return file_cspb_equipment_equipment_proto_rawDescData
}

var file_cspb_equipment_equipment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cspb_equipment_equipment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cspb_equipment_equipment_proto_goTypes = []any{
	(EquipSlot)(0),                 // 0: EquipSlot
	(*EquipmentItem)(nil),          // 1: EquipmentItem
	(*RoleEquipmentData)(nil),      // 2: RoleEquipmentData
	(*GetRoleEquipmentReq)(nil),    // 3: GetRoleEquipmentReq
	(*GetRoleEquipmentAck)(nil),    // 4: GetRoleEquipmentAck
	(*ChangeRoleEquipmentReq)(nil), // 5: ChangeRoleEquipmentReq
	(*ChangeRoleEquipmentAck)(nil), // 6: ChangeRoleEquipmentAck
}
var file_cspb_equipment_equipment_proto_depIdxs = []int32{
	0, // 0: EquipmentItem.slot:type_name -> EquipSlot
	1, // 1: RoleEquipmentData.items:type_name -> EquipmentItem
	2, // 2: GetRoleEquipmentAck.data:type_name -> RoleEquipmentData
	0, // 3: ChangeRoleEquipmentReq.slot:type_name -> EquipSlot
	2, // 4: ChangeRoleEquipmentAck.data:type_name -> RoleEquipmentData
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cspb_equipment_equipment_proto_init() }
func file_cspb_equipment_equipment_proto_init() {
	if File_cspb_equipment_equipment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cspb_equipment_equipment_proto_rawDesc), len(file_cspb_equipment_equipment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cspb_equipment_equipment_proto_goTypes,
		DependencyIndexes: file_cspb_equipment_equipment_proto_depIdxs,
		EnumInfos:         file_cspb_equipment_equipment_proto_enumTypes,
		MessageInfos:      file_cspb_equipment_equipment_proto_msgTypes,
	}.Build()
	File_cspb_equipment_equipment_proto = out.File
	file_cspb_equipment_equipment_proto_goTypes = nil
	file_cspb_equipment_equipment_proto_depIdxs = nil
}
