// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: sspb/struct.proto

package sspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EventTyp      int32                  `protobuf:"varint,2,opt,name=eventTyp,proto3" json:"eventTyp,omitempty"`
	Args          map[string]int32       `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_sspb_struct_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_sspb_struct_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_sspb_struct_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetEventTyp() int32 {
	if x != nil {
		return x.EventTyp
	}
	return 0
}

func (x *Event) GetArgs() map[string]int32 {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_sspb_struct_proto protoreflect.FileDescriptor

const file_sspb_struct_proto_rawDesc = "" +
	"\n" +
	"\x11sspb/struct.proto\"\x96\x01\n" +
	"\x05event\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\beventTyp\x18\x02 \x01(\x05R\beventTyp\x12$\n" +
	"\x04args\x18\x03 \x03(\v2\x10.event.ArgsEntryR\x04args\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B Z\x1egithub.com/gogu-x/gogs/pb/sspbb\x06proto3"

var (
	file_sspb_struct_proto_rawDescOnce sync.Once
	file_sspb_struct_proto_rawDescData []byte
)

func file_sspb_struct_proto_rawDescGZIP() []byte {
	file_sspb_struct_proto_rawDescOnce.Do(func() {
		file_sspb_struct_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sspb_struct_proto_rawDesc), len(file_sspb_struct_proto_rawDesc)))
	})
	return file_sspb_struct_proto_rawDescData
}

var file_sspb_struct_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sspb_struct_proto_goTypes = []any{
	(*Event)(nil), // 0: event
	nil,           // 1: event.ArgsEntry
}
var file_sspb_struct_proto_depIdxs = []int32{
	1, // 0: event.args:type_name -> event.ArgsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sspb_struct_proto_init() }
func file_sspb_struct_proto_init() {
	if File_sspb_struct_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sspb_struct_proto_rawDesc), len(file_sspb_struct_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sspb_struct_proto_goTypes,
		DependencyIndexes: file_sspb_struct_proto_depIdxs,
		MessageInfos:      file_sspb_struct_proto_msgTypes,
	}.Build()
	File_sspb_struct_proto = out.File
	file_sspb_struct_proto_goTypes = nil
	file_sspb_struct_proto_depIdxs = nil
}
