// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: cspb/guild/req.proto

package pb_guild

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGuildReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UID           uint64                 `protobuf:"varint,101,opt,name=uID,proto3" json:"uID,omitempty"`
	ServerID      uint32                 `protobuf:"varint,102,opt,name=serverID,proto3" json:"serverID,omitempty"`
	SessionID     string                 `protobuf:"bytes,103,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LeaderName    string                 `protobuf:"bytes,3,opt,name=leader_name,json=leaderName,proto3" json:"leader_name,omitempty"`
	LeaderLevel   uint32                 `protobuf:"varint,4,opt,name=leader_level,json=leaderLevel,proto3" json:"leader_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGuildReq) Reset() {
	*x = CreateGuildReq{}
	mi := &file_cspb_guild_req_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGuildReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGuildReq) ProtoMessage() {}

func (x *CreateGuildReq) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_guild_req_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGuildReq.ProtoReflect.Descriptor instead.
func (*CreateGuildReq) Descriptor() ([]byte, []int) {
	return file_cspb_guild_req_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGuildReq) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *CreateGuildReq) GetServerID() uint32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *CreateGuildReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *CreateGuildReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGuildReq) GetLeaderName() string {
	if x != nil {
		return x.LeaderName
	}
	return ""
}

func (x *CreateGuildReq) GetLeaderLevel() uint32 {
	if x != nil {
		return x.LeaderLevel
	}
	return 0
}

type JoinGuildReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UID           uint64                 `protobuf:"varint,101,opt,name=uID,proto3" json:"uID,omitempty"`
	ServerID      uint32                 `protobuf:"varint,102,opt,name=serverID,proto3" json:"serverID,omitempty"`
	SessionID     string                 `protobuf:"bytes,103,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	GuildId       uint64                 `protobuf:"varint,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	MemberName    string                 `protobuf:"bytes,3,opt,name=member_name,json=memberName,proto3" json:"member_name,omitempty"`
	MemberLevel   uint32                 `protobuf:"varint,4,opt,name=member_level,json=memberLevel,proto3" json:"member_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGuildReq) Reset() {
	*x = JoinGuildReq{}
	mi := &file_cspb_guild_req_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGuildReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGuildReq) ProtoMessage() {}

func (x *JoinGuildReq) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_guild_req_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGuildReq.ProtoReflect.Descriptor instead.
func (*JoinGuildReq) Descriptor() ([]byte, []int) {
	return file_cspb_guild_req_proto_rawDescGZIP(), []int{1}
}

func (x *JoinGuildReq) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *JoinGuildReq) GetServerID() uint32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *JoinGuildReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *JoinGuildReq) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *JoinGuildReq) GetMemberName() string {
	if x != nil {
		return x.MemberName
	}
	return ""
}

func (x *JoinGuildReq) GetMemberLevel() uint32 {
	if x != nil {
		return x.MemberLevel
	}
	return 0
}

type LeaveGuildReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UID           uint64                 `protobuf:"varint,101,opt,name=uID,proto3" json:"uID,omitempty"`
	ServerID      uint32                 `protobuf:"varint,102,opt,name=serverID,proto3" json:"serverID,omitempty"`
	SessionID     string                 `protobuf:"bytes,103,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGuildReq) Reset() {
	*x = LeaveGuildReq{}
	mi := &file_cspb_guild_req_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGuildReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGuildReq) ProtoMessage() {}

func (x *LeaveGuildReq) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_guild_req_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGuildReq.ProtoReflect.Descriptor instead.
func (*LeaveGuildReq) Descriptor() ([]byte, []int) {
	return file_cspb_guild_req_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveGuildReq) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *LeaveGuildReq) GetServerID() uint32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *LeaveGuildReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type GetGuildReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UID           uint64                 `protobuf:"varint,101,opt,name=uID,proto3" json:"uID,omitempty"`
	ServerID      uint32                 `protobuf:"varint,102,opt,name=serverID,proto3" json:"serverID,omitempty"`
	SessionID     string                 `protobuf:"bytes,103,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	GuildId       uint64                 `protobuf:"varint,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGuildReq) Reset() {
	*x = GetGuildReq{}
	mi := &file_cspb_guild_req_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGuildReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildReq) ProtoMessage() {}

func (x *GetGuildReq) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_guild_req_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildReq.ProtoReflect.Descriptor instead.
func (*GetGuildReq) Descriptor() ([]byte, []int) {
	return file_cspb_guild_req_proto_rawDescGZIP(), []int{3}
}

func (x *GetGuildReq) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *GetGuildReq) GetServerID() uint32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *GetGuildReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *GetGuildReq) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

var File_cspb_guild_req_proto protoreflect.FileDescriptor

const file_cspb_guild_req_proto_rawDesc = "" +
	"\n" +
	"\x14cspb/guild/req.proto\"\xb4\x01\n" +
	"\x0eCreateGuildReq\x12\x10\n" +
	"\x03uID\x18e \x01(\x04R\x03uID\x12\x1a\n" +
	"\bserverID\x18f \x01(\rR\bserverID\x12\x1c\n" +
	"\tsessionID\x18g \x01(\tR\tsessionID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vleader_name\x18\x03 \x01(\tR\n" +
	"leaderName\x12!\n" +
	"\fleader_level\x18\x04 \x01(\rR\vleaderLevel\"\xb9\x01\n" +
	"\fJoinGuildReq\x12\x10\n" +
	"\x03uID\x18e \x01(\x04R\x03uID\x12\x1a\n" +
	"\bserverID\x18f \x01(\rR\bserverID\x12\x1c\n" +
	"\tsessionID\x18g \x01(\tR\tsessionID\x12\x19\n" +
	"\bguild_id\x18\x02 \x01(\x04R\aguildId\x12\x1f\n" +
	"\vmember_name\x18\x03 \x01(\tR\n" +
	"memberName\x12!\n" +
	"\fmember_level\x18\x04 \x01(\rR\vmemberLevel\"[\n" +
	"\rLeaveGuildReq\x12\x10\n" +
	"\x03uID\x18e \x01(\x04R\x03uID\x12\x1a\n" +
	"\bserverID\x18f \x01(\rR\bserverID\x12\x1c\n" +
	"\tsessionID\x18g \x01(\tR\tsessionID\"t\n" +
	"\vGetGuildReq\x12\x10\n" +
	"\x03uID\x18e \x01(\x04R\x03uID\x12\x1a\n" +
	"\bserverID\x18f \x01(\rR\bserverID\x12\x1c\n" +
	"\tsessionID\x18g \x01(\tR\tsessionID\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\x04R\aguildIdB)Z'github.com/gogu-x/gogs/pb/cspb/pb_guildb\x06proto3"

var (
	file_cspb_guild_req_proto_rawDescOnce sync.Once
	file_cspb_guild_req_proto_rawDescData []byte
)

func file_cspb_guild_req_proto_rawDescGZIP() []byte {
	file_cspb_guild_req_proto_rawDescOnce.Do(func() {
		file_cspb_guild_req_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cspb_guild_req_proto_rawDesc), len(file_cspb_guild_req_proto_rawDesc)))
	})
	return file_cspb_guild_req_proto_rawDescData
}

var file_cspb_guild_req_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cspb_guild_req_proto_goTypes = []any{
	(*CreateGuildReq)(nil), // 0: CreateGuildReq
	(*JoinGuildReq)(nil),   // 1: JoinGuildReq
	(*LeaveGuildReq)(nil),  // 2: LeaveGuildReq
	(*GetGuildReq)(nil),    // 3: GetGuildReq
}
var file_cspb_guild_req_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cspb_guild_req_proto_init() }
func file_cspb_guild_req_proto_init() {
	if File_cspb_guild_req_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cspb_guild_req_proto_rawDesc), len(file_cspb_guild_req_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cspb_guild_req_proto_goTypes,
		DependencyIndexes: file_cspb_guild_req_proto_depIdxs,
		MessageInfos:      file_cspb_guild_req_proto_msgTypes,
	}.Build()
	File_cspb_guild_req_proto = out.File
	file_cspb_guild_req_proto_goTypes = nil
	file_cspb_guild_req_proto_depIdxs = nil
}
