// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: platform/platform.proto

package protoPlatform

import (
	protoCommon "github.com/gogu-x/gogs/pb/protoCommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_PENDING   OrderStatus = 0
	OrderStatus_PAID      OrderStatus = 1
	OrderStatus_DELIVERED OrderStatus = 2
	OrderStatus_FAILED    OrderStatus = 3
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "PENDING",
		1: "PAID",
		2: "DELIVERED",
		3: "FAILED",
	}
	OrderStatus_value = map[string]int32{
		"PENDING":   0,
		"PAID":      1,
		"DELIVERED": 2,
		"FAILED":    3,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_platform_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_platform_platform_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_platform_platform_proto_rawDescGZIP(), []int{0}
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ServerId      int32                  `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_platform_platform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_platform_platform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_platform_platform_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type AuthLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ServerId      int32                  `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLoginReq) Reset() {
	*x = AuthLoginReq{}
	mi := &file_platform_platform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLoginReq) ProtoMessage() {}

func (x *AuthLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_platform_platform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLoginReq.ProtoReflect.Descriptor instead.
func (*AuthLoginReq) Descriptor() ([]byte, []int) {
	return file_platform_platform_proto_rawDescGZIP(), []int{1}
}

func (x *AuthLoginReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AuthLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthLoginReq) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type AuthAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          protoCommon.ErrCode    `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Uid           uint64                 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthAck) Reset() {
	*x = AuthAck{}
	mi := &file_platform_platform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthAck) ProtoMessage() {}

func (x *AuthAck) ProtoReflect() protoreflect.Message {
	mi := &file_platform_platform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthAck.ProtoReflect.Descriptor instead.
func (*AuthAck) Descriptor() ([]byte, []int) {
	return file_platform_platform_proto_rawDescGZIP(), []int{2}
}

func (x *AuthAck) GetCode() protoCommon.ErrCode {
	if x != nil {
		return x.Code
	}
	return protoCommon.ErrCode(0)
}

func (x *AuthAck) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AuthAck) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AuthAck) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenReq) Reset() {
	*x = VerifyTokenReq{}
	mi := &file_platform_platform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenReq) ProtoMessage() {}

func (x *VerifyTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_platform_platform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenReq.ProtoReflect.Descriptor instead.
func (*VerifyTokenReq) Descriptor() ([]byte, []int) {
	return file_platform_platform_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAck) Reset() {
	*x = VerifyAck{}
	mi := &file_platform_platform_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAck) ProtoMessage() {}

func (x *VerifyAck) ProtoReflect() protoreflect.Message {
	mi := &file_platform_platform_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAck.ProtoReflect.Descriptor instead.
func (*VerifyAck) Descriptor() ([]byte, []int) {
	return file_platform_platform_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyAck) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyAck) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_platform_platform_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_platform_platform_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_platform_platform_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrderReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateOrderReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateOrderReq) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type OrderAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          protoCommon.ErrCode    `protobuf:"varint,1,opt,name=code,proto3,enum=ErrCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderAck) Reset() {
	*x = OrderAck{}
	mi := &file_platform_platform_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAck) ProtoMessage() {}

func (x *OrderAck) ProtoReflect() protoreflect.Message {
	mi := &file_platform_platform_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAck.ProtoReflect.Descriptor instead.
func (*OrderAck) Descriptor() ([]byte, []int) {
	return file_platform_platform_proto_rawDescGZIP(), []int{6}
}

func (x *OrderAck) GetCode() protoCommon.ErrCode {
	if x != nil {
		return x.Code
	}
	return protoCommon.ErrCode(0)
}

func (x *OrderAck) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *OrderAck) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type QueryOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryOrderReq) Reset() {
	*x = QueryOrderReq{}
	mi := &file_platform_platform_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOrderReq) ProtoMessage() {}

func (x *QueryOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_platform_platform_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOrderReq.ProtoReflect.Descriptor instead.
func (*QueryOrderReq) Descriptor() ([]byte, []int) {
	return file_platform_platform_proto_rawDescGZIP(), []int{7}
}

func (x *QueryOrderReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type OrderDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,4,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=platform.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDetail) Reset() {
	*x = OrderDetail{}
	mi := &file_platform_platform_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetail) ProtoMessage() {}

func (x *OrderDetail) ProtoReflect() protoreflect.Message {
	mi := &file_platform_platform_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetail.ProtoReflect.Descriptor instead.
func (*OrderDetail) Descriptor() ([]byte, []int) {
	return file_platform_platform_proto_rawDescGZIP(), []int{8}
}

func (x *OrderDetail) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderDetail) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *OrderDetail) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderDetail) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *OrderDetail) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_PENDING
}

type DeliverNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,4,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverNotify) Reset() {
	*x = DeliverNotify{}
	mi := &file_platform_platform_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverNotify) ProtoMessage() {}

func (x *DeliverNotify) ProtoReflect() protoreflect.Message {
	mi := &file_platform_platform_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverNotify.ProtoReflect.Descriptor instead.
func (*DeliverNotify) Descriptor() ([]byte, []int) {
	return file_platform_platform_proto_rawDescGZIP(), []int{9}
}

func (x *DeliverNotify) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *DeliverNotify) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DeliverNotify) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *DeliverNotify) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

var File_platform_platform_proto protoreflect.FileDescriptor

const file_platform_platform_proto_rawDesc = "" +
	"\n" +
	"\x17platform/platform.proto\x12\bplatform\x1a\x12common/error.proto\"`\n" +
	"\vRegisterReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\x05R\bserverId\"a\n" +
	"\fAuthLoginReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\x05R\bserverId\"a\n" +
	"\aAuthAck\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x0e2\b.ErrCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x04R\x03uid\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"&\n" +
	"\x0eVerifyTokenReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"3\n" +
	"\tVerifyAck\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\"^\n" +
	"\x0eCreateOrderReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId\"U\n" +
	"\bOrderAck\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x0e2\b.ErrCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\"*\n" +
	"\rQueryOrderReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\xa5\x01\n" +
	"\vOrderDetail\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x1b\n" +
	"\tserver_id\x18\x04 \x01(\tR\bserverId\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.platform.OrderStatusR\x06status\"x\n" +
	"\rDeliverNotify\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x1b\n" +
	"\tserver_id\x18\x04 \x01(\tR\bserverId*?\n" +
	"\vOrderStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\b\n" +
	"\x04PAID\x10\x01\x12\r\n" +
	"\tDELIVERED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x032\xb5\x01\n" +
	"\vAuthService\x124\n" +
	"\bRegister\x12\x15.platform.RegisterReq\x1a\x11.platform.AuthAck\x122\n" +
	"\x05Login\x12\x16.platform.AuthLoginReq\x1a\x11.platform.AuthAck\x12<\n" +
	"\vVerifyToken\x12\x18.platform.VerifyTokenReq\x1a\x13.platform.VerifyAck2\x89\x01\n" +
	"\fOrderService\x12;\n" +
	"\vCreateOrder\x12\x18.platform.CreateOrderReq\x1a\x12.platform.OrderAck\x12<\n" +
	"\n" +
	"QueryOrder\x12\x17.platform.QueryOrderReq\x1a\x15.platform.OrderDetailB)Z'github.com/gogu-x/gogs/pb/protoPlatformb\x06proto3"

var (
	file_platform_platform_proto_rawDescOnce sync.Once
	file_platform_platform_proto_rawDescData []byte
)

func file_platform_platform_proto_rawDescGZIP() []byte {
	file_platform_platform_proto_rawDescOnce.Do(func() {
		file_platform_platform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_platform_proto_rawDesc), len(file_platform_platform_proto_rawDesc)))
	})
	return file_platform_platform_proto_rawDescData
}

var file_platform_platform_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_platform_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_platform_platform_proto_goTypes = []any{
	(OrderStatus)(0),         // 0: platform.OrderStatus
	(*RegisterReq)(nil),      // 1: platform.RegisterReq
	(*AuthLoginReq)(nil),     // 2: platform.AuthLoginReq
	(*AuthAck)(nil),          // 3: platform.AuthAck
	(*VerifyTokenReq)(nil),   // 4: platform.VerifyTokenReq
	(*VerifyAck)(nil),        // 5: platform.VerifyAck
	(*CreateOrderReq)(nil),   // 6: platform.CreateOrderReq
	(*OrderAck)(nil),         // 7: platform.OrderAck
	(*QueryOrderReq)(nil),    // 8: platform.QueryOrderReq
	(*OrderDetail)(nil),      // 9: platform.OrderDetail
	(*DeliverNotify)(nil),    // 10: platform.DeliverNotify
	(protoCommon.ErrCode)(0), // 11: ErrCode
}
var file_platform_platform_proto_depIdxs = []int32{
	11, // 0: platform.AuthAck.code:type_name -> ErrCode
	11, // 1: platform.OrderAck.code:type_name -> ErrCode
	0,  // 2: platform.OrderDetail.status:type_name -> platform.OrderStatus
	1,  // 3: platform.AuthService.Register:input_type -> platform.RegisterReq
	2,  // 4: platform.AuthService.Login:input_type -> platform.AuthLoginReq
	4,  // 5: platform.AuthService.VerifyToken:input_type -> platform.VerifyTokenReq
	6,  // 6: platform.OrderService.CreateOrder:input_type -> platform.CreateOrderReq
	8,  // 7: platform.OrderService.QueryOrder:input_type -> platform.QueryOrderReq
	3,  // 8: platform.AuthService.Register:output_type -> platform.AuthAck
	3,  // 9: platform.AuthService.Login:output_type -> platform.AuthAck
	5,  // 10: platform.AuthService.VerifyToken:output_type -> platform.VerifyAck
	7,  // 11: platform.OrderService.CreateOrder:output_type -> platform.OrderAck
	9,  // 12: platform.OrderService.QueryOrder:output_type -> platform.OrderDetail
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_platform_platform_proto_init() }
func file_platform_platform_proto_init() {
	if File_platform_platform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_platform_proto_rawDesc), len(file_platform_platform_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_platform_platform_proto_goTypes,
		DependencyIndexes: file_platform_platform_proto_depIdxs,
		EnumInfos:         file_platform_platform_proto_enumTypes,
		MessageInfos:      file_platform_platform_proto_msgTypes,
	}.Build()
	File_platform_platform_proto = out.File
	file_platform_platform_proto_goTypes = nil
	file_platform_platform_proto_depIdxs = nil
}
