// Code generated by gen-register.lua. DO NOT EDIT.
package game

import "github.com/gogu-x/gogs/codec"

func init() {
	codec.RegisterMsg(
		&LoginReq{},
		&LoginResp{},
		&LogoutReq{},
		&HeartbeatReq{},
		&HeartbeatResp{},
		&MoveReq{},
		&ChatReq{},
		&ChatResp{},
	)
}
