// Code generated by deepcopy-gen. DO NOT EDIT.

package cardgroup

// DeepCopy 返回 Mgr 的独立副本。
func (in *Mgr) DeepCopy() *Mgr {
	if in == nil {
		return nil
	}
	out := *in
	if in.Cards != nil {
		out.Cards = make(map[uint64]int64, len(in.Cards))
		for key1, value2 := range in.Cards {
			var cloned3 int64
			cloned3 = value2
			out.Cards[key1] = cloned3
		}
	}
	return &out
}
