// Code generated by deepcopy-gen. DO NOT EDIT.

package bag

// DeepCopy 返回 Item 的独立副本。
func (in *Item) DeepCopy() *Item {
	if in == nil {
		return nil
	}
	out := *in
	return &out
}

// DeepCopy 返回 Mgr 的独立副本。
func (in *Mgr) DeepCopy() *Mgr {
	if in == nil {
		return nil
	}
	out := *in
	if in.Slots != nil {
		out.Slots = make(map[uint64]*Item, len(in.Slots))
		for key1, value2 := range in.Slots {
			var cloned3 *Item
			cloned3 = value2.DeepCopy()
			out.Slots[key1] = cloned3
		}
	}
	return &out
}
