// Code generated by gen-conf.py. DO NOT EDIT.
// Package glconf 包含自动生成的游戏配置。
package glconf

import (
	"fmt"

	"github.com/gogu-x/tree/tlog"
)

type confLoader func(dbURI, dbName, confName string) (*CsvConf, error)

type confMeta struct {
	source string
	loader confLoader
	csv    *CsvConf
}

var confs []*confMeta

// InitGameCfg 注册全部自动生成的配置表；可重复调用。
func InitGameCfg() {
	confs = confs[:0]
	confs = append(confs, &confMeta{source: ActvOnlineCfgKey, loader: loadActvOnlineCfg})
	confs = append(confs, &confMeta{source: BattleEquipCfgKey, loader: loadBattleEquipCfg})
	confs = append(confs, &confMeta{source: BattleMonsterCfgKey, loader: loadBattleMonsterCfg})
	confs = append(confs, &confMeta{source: BattleMonsterGroupCfgKey, loader: loadBattleMonsterGroupCfg})
	confs = append(confs, &confMeta{source: BattleRoleCfgKey, loader: loadBattleRoleCfg})
	confs = append(confs, &confMeta{source: BattleRuleCfgKey, loader: loadBattleRuleCfg})
	confs = append(confs, &confMeta{source: BattleSkillCfgKey, loader: loadBattleSkillCfg})
	confs = append(confs, &confMeta{source: BattleStatusCfgKey, loader: loadBattleStatusCfg})
	confs = append(confs, &confMeta{source: D2DailyGiftCfgKey, loader: loadD2DailyGiftCfg})
}

// LoadAllConfs 从 MongoDB 加载全部配置表。
// dbURI 是 MongoDB URI，dbName 是配置数据库名。isHotLoad 保留用于兼容旧调用。
func LoadAllConfs(dbURI, dbName string, isHotLoad bool) error {
	_ = isHotLoad
	InitGameCfg()
	for _, meta := range confs {
		if err := loadConf(meta, dbURI, dbName); err != nil {
			return err
		}
	}
	return nil
}

// LoadConfs 从 MongoDB 加载指定配置表。
func LoadConfs(
	names []string,
	dbURI,
	dbName string,
	isHotLoad bool,
) error {
	_ = isHotLoad
	if len(confs) == 0 {
		InitGameCfg()
	}
	for _, name := range names {
		meta := getConfMeta(name)
		if meta == nil {
			return fmt.Errorf("configuration metadata not found: %s", name)
		}
		if err := loadConf(meta, dbURI, dbName); err != nil {
			return err
		}
	}
	return nil
}

func getConfMeta(name string) *confMeta {
	for _, meta := range confs {
		if meta.source == name {
			return meta
		}
	}
	return nil
}

func loadConf(meta *confMeta, dbURI, dbName string) error {
	table, err := meta.loader(dbURI, dbName, meta.source)
	if err != nil {
		return fmt.Errorf("load configuration %s: %w", meta.source, err)
	}
	tlog.Log.Info("load configuration success %v", meta.source)
	meta.csv = table
	return nil
}
