// Code generated by gen-conf.py. DO NOT EDIT.
// Package glconf 包含自动生成的游戏配置。
package glconf

import (
	"sync/atomic"
)

// D2DailyGiftCfgKey 是配置表的 MongoDB collection 名称。
const D2DailyGiftCfgKey = "D2DailyGiftCfg"

var csvD2DailyGiftCfg atomic.Value

// D2DailyGiftCfg 表示 D2DailyGiftCfg 配置记录。
type D2DailyGiftCfg struct {
	CfgID        int32    `bson:"id"`             // 编号
	ShowIconType []int32  `bson:"show_icon_type"` // 显示图标类型
	ShowItemId   []int32  `bson:"show_item_id"`   // 显示道具编号
	ShowItemNum  []string `bson:"show_item_num"`  // 显示道具数量
}

func loadD2DailyGiftCfg(dbURI, dbName, confName string) (*CsvConf, error) {
	table, err := readCsv(dbURI, dbName, confName, &D2DailyGiftCfg{})
	if err != nil {
		return nil, err
	}
	csvD2DailyGiftCfg.Store(table)
	return table, nil
}

// GetD2DailyGiftCfg 按配置键查询记录；不存在时返回 nil。
func GetD2DailyGiftCfg(id int32) *D2DailyGiftCfg {
	if table := asCsv(csvD2DailyGiftCfg); table != nil {
		if cfg := table.Get(id); cfg != nil {
			return cfg.(*D2DailyGiftCfg)
		}
	}
	return nil
}

// GetD2DailyGiftCfgNoErr 按 ID 查询配置；不存在时返回 nil。
func GetD2DailyGiftCfgNoErr(id int32) *D2DailyGiftCfg {
	if table := asCsv(csvD2DailyGiftCfg); table != nil {
		if cfg := table.GetNoErr(id); cfg != nil {
			return cfg.(*D2DailyGiftCfg)
		}
	}
	return nil
}

// GetAllD2DailyGiftCfg 返回当前表的全部配置记录。
func GetAllD2DailyGiftCfg() []*D2DailyGiftCfg {
	table := asCsv(csvD2DailyGiftCfg)
	if table == nil {
		return nil
	}
	configs := make([]*D2DailyGiftCfg, 0, len(table.Records))
	for _, record := range table.Records {
		configs = append(configs, record.(*D2DailyGiftCfg))
	}
	return configs
}

// GetD2DailyGiftCfgInterface 按 ID 查询配置并返回通用接口。
func GetD2DailyGiftCfgInterface(id int32) interface{} {
	if table := asCsv(csvD2DailyGiftCfg); table != nil {
		return table.GetNoErr(id)
	}
	return nil
}
