// Code generated by gen-conf.py. DO NOT EDIT.
// Package glconf 包含自动生成的游戏配置。
package glconf

import (
	cspb "github.com/gogu-x/gogs/pb/cspb/pb_common"
	"sync/atomic"
)

// BattleStatusCfgKey 是配置表的 MongoDB collection 名称。
const BattleStatusCfgKey = "BattleStatusCfg"

var csvBattleStatusCfg atomic.Value

// BattleStatusCfg 表示 BattleStatusCfg 配置记录。
type BattleStatusCfg struct {
	CfgID         int32            `bson:"id"`             // 状态配置 ID
	Kind          int32            `bson:"kind"`           // 状态类型
	DurationTurns int32            `bson:"duration_turns"` // 持续行动次数
	Potency       int64            `bson:"potency"`        // DOT 或 HOT 数值
	Modifier      []*cspb.TypIDVal `bson:"modifier"`       // attribute modifiers (Typ=battle_attribute; IDs 1..4=max_hp/attack/defense/speed)
}

func loadBattleStatusCfg(dbURI, dbName, confName string) (*CsvConf, error) {
	table, err := readCsv(dbURI, dbName, confName, &BattleStatusCfg{})
	if err != nil {
		return nil, err
	}
	csvBattleStatusCfg.Store(table)
	return table, nil
}

// GetBattleStatusCfg 按配置键查询记录；不存在时返回 nil。
func GetBattleStatusCfg(id int32) *BattleStatusCfg {
	if table := asCsv(csvBattleStatusCfg); table != nil {
		if cfg := table.Get(id); cfg != nil {
			return cfg.(*BattleStatusCfg)
		}
	}
	return nil
}

// GetBattleStatusCfgNoErr 按 ID 查询配置；不存在时返回 nil。
func GetBattleStatusCfgNoErr(id int32) *BattleStatusCfg {
	if table := asCsv(csvBattleStatusCfg); table != nil {
		if cfg := table.GetNoErr(id); cfg != nil {
			return cfg.(*BattleStatusCfg)
		}
	}
	return nil
}

// GetAllBattleStatusCfg 返回当前表的全部配置记录。
func GetAllBattleStatusCfg() []*BattleStatusCfg {
	table := asCsv(csvBattleStatusCfg)
	if table == nil {
		return nil
	}
	configs := make([]*BattleStatusCfg, 0, len(table.Records))
	for _, record := range table.Records {
		configs = append(configs, record.(*BattleStatusCfg))
	}
	return configs
}

// GetBattleStatusCfgInterface 按 ID 查询配置并返回通用接口。
func GetBattleStatusCfgInterface(id int32) interface{} {
	if table := asCsv(csvBattleStatusCfg); table != nil {
		return table.GetNoErr(id)
	}
	return nil
}
