// Code generated by gen-conf.py. DO NOT EDIT.
// Package glconf 包含自动生成的游戏配置。
package glconf

import (
	cspb "github.com/gogu-x/gogs/pb/cspb/pb_common"
	"sync/atomic"
)

// BattleMonsterGroupCfgKey 是配置表的 MongoDB collection 名称。
const BattleMonsterGroupCfgKey = "BattleMonsterGroupCfg"

var csvBattleMonsterGroupCfg atomic.Value

// BattleMonsterGroupCfg 表示 BattleMonsterGroupCfg 配置记录。
type BattleMonsterGroupCfg struct {
	CfgID   int32            `bson:"id"`      // 怪物组配置 ID
	Members []*cspb.TypIDVal `bson:"members"` // monster members (Typ=battle_monster; ID=monster config ID; Val=position)
}

func loadBattleMonsterGroupCfg(dbURI, dbName, confName string) (*CsvConf, error) {
	table, err := readCsv(dbURI, dbName, confName, &BattleMonsterGroupCfg{})
	if err != nil {
		return nil, err
	}
	csvBattleMonsterGroupCfg.Store(table)
	return table, nil
}

// GetBattleMonsterGroupCfg 按配置键查询记录；不存在时返回 nil。
func GetBattleMonsterGroupCfg(id int32) *BattleMonsterGroupCfg {
	if table := asCsv(csvBattleMonsterGroupCfg); table != nil {
		if cfg := table.Get(id); cfg != nil {
			return cfg.(*BattleMonsterGroupCfg)
		}
	}
	return nil
}

// GetBattleMonsterGroupCfgNoErr 按 ID 查询配置；不存在时返回 nil。
func GetBattleMonsterGroupCfgNoErr(id int32) *BattleMonsterGroupCfg {
	if table := asCsv(csvBattleMonsterGroupCfg); table != nil {
		if cfg := table.GetNoErr(id); cfg != nil {
			return cfg.(*BattleMonsterGroupCfg)
		}
	}
	return nil
}

// GetAllBattleMonsterGroupCfg 返回当前表的全部配置记录。
func GetAllBattleMonsterGroupCfg() []*BattleMonsterGroupCfg {
	table := asCsv(csvBattleMonsterGroupCfg)
	if table == nil {
		return nil
	}
	configs := make([]*BattleMonsterGroupCfg, 0, len(table.Records))
	for _, record := range table.Records {
		configs = append(configs, record.(*BattleMonsterGroupCfg))
	}
	return configs
}

// GetBattleMonsterGroupCfgInterface 按 ID 查询配置并返回通用接口。
func GetBattleMonsterGroupCfgInterface(id int32) interface{} {
	if table := asCsv(csvBattleMonsterGroupCfg); table != nil {
		return table.GetNoErr(id)
	}
	return nil
}
