// Code generated by gen-conf.py. DO NOT EDIT.
// Package glconf 包含自动生成的游戏配置。
package glconf

import (
	"sync/atomic"
)

// BattleRoleCfgKey 是配置表的 MongoDB collection 名称。
const BattleRoleCfgKey = "BattleRoleCfg"

var csvBattleRoleCfg atomic.Value

// BattleRoleCfg 表示 BattleRoleCfg 配置记录。
type BattleRoleCfg struct {
	CfgID            int32   `bson:"id"`                 // 角色配置 ID
	MaxHP            int64   `bson:"max_hp"`             // 基础最大生命
	Attack           int64   `bson:"attack"`             // 基础攻击
	Defense          int64   `bson:"defense"`            // 基础防御
	Speed            int64   `bson:"speed"`              // 基础速度
	DefaultPosition  int32   `bson:"default_position"`   // 默认站位
	BasicSkillID     int32   `bson:"basic_skill_id"`     // 普攻技能 ID
	ActiveSkillIDs   []int32 `bson:"active_skill_ids"`   // 主动技能 ID
	InitialStatusIDs []int32 `bson:"initial_status_ids"` // 初始状态 ID
}

func loadBattleRoleCfg(dbURI, dbName, confName string) (*CsvConf, error) {
	table, err := readCsv(dbURI, dbName, confName, &BattleRoleCfg{})
	if err != nil {
		return nil, err
	}
	csvBattleRoleCfg.Store(table)
	return table, nil
}

// GetBattleRoleCfg 按配置键查询记录；不存在时返回 nil。
func GetBattleRoleCfg(id int32) *BattleRoleCfg {
	if table := asCsv(csvBattleRoleCfg); table != nil {
		if cfg := table.Get(id); cfg != nil {
			return cfg.(*BattleRoleCfg)
		}
	}
	return nil
}

// GetBattleRoleCfgNoErr 按 ID 查询配置；不存在时返回 nil。
func GetBattleRoleCfgNoErr(id int32) *BattleRoleCfg {
	if table := asCsv(csvBattleRoleCfg); table != nil {
		if cfg := table.GetNoErr(id); cfg != nil {
			return cfg.(*BattleRoleCfg)
		}
	}
	return nil
}

// GetAllBattleRoleCfg 返回当前表的全部配置记录。
func GetAllBattleRoleCfg() []*BattleRoleCfg {
	table := asCsv(csvBattleRoleCfg)
	if table == nil {
		return nil
	}
	configs := make([]*BattleRoleCfg, 0, len(table.Records))
	for _, record := range table.Records {
		configs = append(configs, record.(*BattleRoleCfg))
	}
	return configs
}

// GetBattleRoleCfgInterface 按 ID 查询配置并返回通用接口。
func GetBattleRoleCfgInterface(id int32) interface{} {
	if table := asCsv(csvBattleRoleCfg); table != nil {
		return table.GetNoErr(id)
	}
	return nil
}
