// Code generated by gen-conf.py. DO NOT EDIT.
// Package glconf 包含自动生成的游戏配置。
package glconf

import (
	"sync/atomic"
)

// ActvOnlineCfgKey 是配置表的 MongoDB collection 名称。
const ActvOnlineCfgKey = "ActvOnlineCfg"

var csvActvOnlineCfg atomic.Value

// ActvOnlineCfg 表示 ActvOnlineCfg 配置记录。
type ActvOnlineCfg struct {
	ID                  int32   `bson:"id"`                    // 编号
	ContentID           int32   `bson:"content_id"`            // 内容ID
	Available           bool    `bson:"available"`             // 开启状态
	Tab                 int32   `bson:"tab"`                   // 活动入口
	Type                int32   `bson:"type"`                  // 类型
	AcrossServerGroup   int32   `bson:"across_server_group"`   // 跨服组
	ServerGroups        []int32 `bson:"server_groups"`         // 服务器组
	TriggerType         int32   `bson:"trigger_type"`          // 时间类型
	TriggerVal          string  `bson:"trigger_val"`           // 时间数值
	Reopen              bool    `bson:"reopen"`                // 循环状态
	OpenDayLimit        string  `bson:"open_day_limit"`        // 开服时间限制
	TriggerRept         string  `bson:"trigger_rept"`          // 再次触发时间
	ForecastBeforeStart string  `bson:"forecast_before_start"` // 预告时间
	Duration            string  `bson:"duration"`              // 持续时间
	CloseAfterEnd       string  `bson:"close_after_end"`       // 关闭时间
	SpecialType         int32   `bson:"special_type"`          // 特殊条件
	SpecialVal          string  `bson:"special_val"`           // 特殊条件值
	LevelCondition      int32   `bson:"level_condition"`       // 等级条件
	LevelVal            int32   `bson:"level_val"`             // 等级条件值
}

func loadActvOnlineCfg(dbURI, dbName, confName string) (*CsvConf, error) {
	table, err := readCsv(dbURI, dbName, confName, &ActvOnlineCfg{})
	if err != nil {
		return nil, err
	}
	csvActvOnlineCfg.Store(table)
	return table, nil
}

// GetActvOnlineCfg 按配置键查询记录；不存在时返回 nil。
func GetActvOnlineCfg(id int32) *ActvOnlineCfg {
	if table := asCsv(csvActvOnlineCfg); table != nil {
		if cfg := table.Get(id); cfg != nil {
			return cfg.(*ActvOnlineCfg)
		}
	}
	return nil
}

// GetActvOnlineCfgNoErr 按 ID 查询配置；不存在时返回 nil。
func GetActvOnlineCfgNoErr(id int32) *ActvOnlineCfg {
	if table := asCsv(csvActvOnlineCfg); table != nil {
		if cfg := table.GetNoErr(id); cfg != nil {
			return cfg.(*ActvOnlineCfg)
		}
	}
	return nil
}

// GetAllActvOnlineCfg 返回当前表的全部配置记录。
func GetAllActvOnlineCfg() []*ActvOnlineCfg {
	table := asCsv(csvActvOnlineCfg)
	if table == nil {
		return nil
	}
	configs := make([]*ActvOnlineCfg, 0, len(table.Records))
	for _, record := range table.Records {
		configs = append(configs, record.(*ActvOnlineCfg))
	}
	return configs
}

// GetActvOnlineCfgInterface 按 ID 查询配置并返回通用接口。
func GetActvOnlineCfgInterface(id int32) interface{} {
	if table := asCsv(csvActvOnlineCfg); table != nil {
		return table.GetNoErr(id)
	}
	return nil
}
