// Code generated by gen-conf.py. DO NOT EDIT.
// Package glconf 包含自动生成的游戏配置。
package glconf

import (
	"sync/atomic"
)

// PlayerInitRoleCfgKey 是配置表的 MongoDB collection 名称。
const PlayerInitRoleCfgKey = "PlayerInitRoleCfg"

var csvPlayerInitRoleCfg atomic.Value

// PlayerInitRoleCfg 表示 PlayerInitRoleCfg 配置记录。
type PlayerInitRoleCfg struct {
	CfgID        int32 `bson:"id"`             // 配置 ID
	RoleConfigID int32 `bson:"role_config_id"` // 关联的角色战斗配置 ID
	Level        int32 `bson:"level"`          // 初始等级
	Star         int32 `bson:"star"`           // 初始星级
	Breakthrough int32 `bson:"breakthrough"`   // 初始境界等级
}

func loadPlayerInitRoleCfg(dbURI, dbName, confName string) (*CsvConf, error) {
	table, err := readCsv(dbURI, dbName, confName, &PlayerInitRoleCfg{})
	if err != nil {
		return nil, err
	}
	csvPlayerInitRoleCfg.Store(table)
	return table, nil
}

// GetPlayerInitRoleCfg 按配置键查询记录；不存在时返回 nil。
func GetPlayerInitRoleCfg(id int32) *PlayerInitRoleCfg {
	if table := asCsv(csvPlayerInitRoleCfg); table != nil {
		if cfg := table.Get(id); cfg != nil {
			return cfg.(*PlayerInitRoleCfg)
		}
	}
	return nil
}

// GetPlayerInitRoleCfgNoErr 按 ID 查询配置；不存在时返回 nil。
func GetPlayerInitRoleCfgNoErr(id int32) *PlayerInitRoleCfg {
	if table := asCsv(csvPlayerInitRoleCfg); table != nil {
		if cfg := table.GetNoErr(id); cfg != nil {
			return cfg.(*PlayerInitRoleCfg)
		}
	}
	return nil
}

// GetAllPlayerInitRoleCfg 返回当前表的全部配置记录。
func GetAllPlayerInitRoleCfg() []*PlayerInitRoleCfg {
	table := asCsv(csvPlayerInitRoleCfg)
	if table == nil {
		return nil
	}
	configs := make([]*PlayerInitRoleCfg, 0, len(table.Records))
	for _, record := range table.Records {
		configs = append(configs, record.(*PlayerInitRoleCfg))
	}
	return configs
}

// GetPlayerInitRoleCfgInterface 按 ID 查询配置并返回通用接口。
func GetPlayerInitRoleCfgInterface(id int32) interface{} {
	if table := asCsv(csvPlayerInitRoleCfg); table != nil {
		return table.GetNoErr(id)
	}
	return nil
}
