// Code generated by gen-conf.py. DO NOT EDIT.
// Package glconf 包含自动生成的游戏配置。
package glconf

import (
	"sync/atomic"
)

// BattleMonsterCfgKey 是配置表的 MongoDB collection 名称。
const BattleMonsterCfgKey = "BattleMonsterCfg"

var csvBattleMonsterCfg atomic.Value

// BattleMonsterCfg 表示 BattleMonsterCfg 配置记录。
type BattleMonsterCfg struct {
	CfgID            int32   `bson:"id"`                 // 怪物配置 ID
	MaxHP            int64   `bson:"max_hp"`             // 基础最大生命
	Attack           int64   `bson:"attack"`             // 基础攻击
	Defense          int64   `bson:"defense"`            // 基础防御
	Speed            int64   `bson:"speed"`              // 基础速度
	BasicSkillID     int32   `bson:"basic_skill_id"`     // 普攻技能 ID
	ActiveSkillIDs   []int32 `bson:"active_skill_ids"`   // 主动技能 ID
	InitialStatusIDs []int32 `bson:"initial_status_ids"` // 初始状态 ID
}

func loadBattleMonsterCfg(dbURI, dbName, confName string) (*CsvConf, error) {
	table, err := readCsv(dbURI, dbName, confName, &BattleMonsterCfg{})
	if err != nil {
		return nil, err
	}
	csvBattleMonsterCfg.Store(table)
	return table, nil
}

// GetBattleMonsterCfg 按配置键查询记录；不存在时返回 nil。
func GetBattleMonsterCfg(id int32) *BattleMonsterCfg {
	if table := asCsv(csvBattleMonsterCfg); table != nil {
		if cfg := table.Get(id); cfg != nil {
			return cfg.(*BattleMonsterCfg)
		}
	}
	return nil
}

// GetBattleMonsterCfgNoErr 按 ID 查询配置；不存在时返回 nil。
func GetBattleMonsterCfgNoErr(id int32) *BattleMonsterCfg {
	if table := asCsv(csvBattleMonsterCfg); table != nil {
		if cfg := table.GetNoErr(id); cfg != nil {
			return cfg.(*BattleMonsterCfg)
		}
	}
	return nil
}

// GetAllBattleMonsterCfg 返回当前表的全部配置记录。
func GetAllBattleMonsterCfg() []*BattleMonsterCfg {
	table := asCsv(csvBattleMonsterCfg)
	if table == nil {
		return nil
	}
	configs := make([]*BattleMonsterCfg, 0, len(table.Records))
	for _, record := range table.Records {
		configs = append(configs, record.(*BattleMonsterCfg))
	}
	return configs
}

// GetBattleMonsterCfgInterface 按 ID 查询配置并返回通用接口。
func GetBattleMonsterCfgInterface(id int32) interface{} {
	if table := asCsv(csvBattleMonsterCfg); table != nil {
		return table.GetNoErr(id)
	}
	return nil
}
