// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: cspb/comm/error.proto

package pb_common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_OK                ErrCode = 0
	ErrCode_UNKNOWN           ErrCode = -1
	ErrCode_PARAM             ErrCode = -2
	ErrCode_UNAUTHORIZED      ErrCode = -1001
	ErrCode_LOGIN_IN_PROGRESS ErrCode = -1002
	ErrCode_SERVER_NOT_FOUND  ErrCode = -1003
	ErrCode_USERNAME_EXISTS   ErrCode = -2001
	ErrCode_WRONG_PASSWORD    ErrCode = -2002
	ErrCode_INTERNAL          ErrCode = -2003
	ErrCode_GUILD_EXISTS      ErrCode = -3001
	ErrCode_GUILD_NOT_FOUND   ErrCode = -3002
	ErrCode_ALREADY_IN_GUILD  ErrCode = -3003
	ErrCode_NOT_IN_GUILD      ErrCode = -3004
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:     "OK",
		-1:    "UNKNOWN",
		-2:    "PARAM",
		-1001: "UNAUTHORIZED",
		-1002: "LOGIN_IN_PROGRESS",
		-1003: "SERVER_NOT_FOUND",
		-2001: "USERNAME_EXISTS",
		-2002: "WRONG_PASSWORD",
		-2003: "INTERNAL",
		-3001: "GUILD_EXISTS",
		-3002: "GUILD_NOT_FOUND",
		-3003: "ALREADY_IN_GUILD",
		-3004: "NOT_IN_GUILD",
	}
	ErrCode_value = map[string]int32{
		"OK":                0,
		"UNKNOWN":           -1,
		"PARAM":             -2,
		"UNAUTHORIZED":      -1001,
		"LOGIN_IN_PROGRESS": -1002,
		"SERVER_NOT_FOUND":  -1003,
		"USERNAME_EXISTS":   -2001,
		"WRONG_PASSWORD":    -2002,
		"INTERNAL":          -2003,
		"GUILD_EXISTS":      -3001,
		"GUILD_NOT_FOUND":   -3002,
		"ALREADY_IN_GUILD":  -3003,
		"NOT_IN_GUILD":      -3004,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_cspb_comm_error_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_cspb_comm_error_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_cspb_comm_error_proto_rawDescGZIP(), []int{0}
}

var File_cspb_comm_error_proto protoreflect.FileDescriptor

const file_cspb_comm_error_proto_rawDesc = "" +
	"\n" +
	"\x15cspb/comm/error.proto*\xda\x02\n" +
	"\aErrCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\x14\n" +
	"\aUNKNOWN\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x12\n" +
	"\x05PARAM\x10\xfe\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x19\n" +
	"\fUNAUTHORIZED\x10\x97\xf8\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1e\n" +
	"\x11LOGIN_IN_PROGRESS\x10\x96\xf8\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1d\n" +
	"\x10SERVER_NOT_FOUND\x10\x95\xf8\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1c\n" +
	"\x0fUSERNAME_EXISTS\x10\xaf\xf0\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1b\n" +
	"\x0eWRONG_PASSWORD\x10\xae\xf0\xff\xff\xff\xff\xff\xff\xff\x01\x12\x15\n" +
	"\bINTERNAL\x10\xad\xf0\xff\xff\xff\xff\xff\xff\xff\x01\x12\x19\n" +
	"\fGUILD_EXISTS\x10\xc7\xe8\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1c\n" +
	"\x0fGUILD_NOT_FOUND\x10\xc6\xe8\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1d\n" +
	"\x10ALREADY_IN_GUILD\x10\xc5\xe8\xff\xff\xff\xff\xff\xff\xff\x01\x12\x19\n" +
	"\fNOT_IN_GUILD\x10\xc4\xe8\xff\xff\xff\xff\xff\xff\xff\x01B*Z(github.com/gogu-x/gogs/pb/cspb/pb_commonb\x06proto3"

var (
	file_cspb_comm_error_proto_rawDescOnce sync.Once
	file_cspb_comm_error_proto_rawDescData []byte
)

func file_cspb_comm_error_proto_rawDescGZIP() []byte {
	file_cspb_comm_error_proto_rawDescOnce.Do(func() {
		file_cspb_comm_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cspb_comm_error_proto_rawDesc), len(file_cspb_comm_error_proto_rawDesc)))
	})
	return file_cspb_comm_error_proto_rawDescData
}

var file_cspb_comm_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cspb_comm_error_proto_goTypes = []any{
	(ErrCode)(0), // 0: ErrCode
}
var file_cspb_comm_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cspb_comm_error_proto_init() }
func file_cspb_comm_error_proto_init() {
	if File_cspb_comm_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cspb_comm_error_proto_rawDesc), len(file_cspb_comm_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cspb_comm_error_proto_goTypes,
		DependencyIndexes: file_cspb_comm_error_proto_depIdxs,
		EnumInfos:         file_cspb_comm_error_proto_enumTypes,
	}.Build()
	File_cspb_comm_error_proto = out.File
	file_cspb_comm_error_proto_goTypes = nil
	file_cspb_comm_error_proto_depIdxs = nil
}
