// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: cspb/comm/struct.proto

package pb_common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Comm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UID           uint64                 `protobuf:"varint,1,opt,name=uID,proto3" json:"uID,omitempty"`
	ServerID      uint32                 `protobuf:"varint,2,opt,name=serverID,proto3" json:"serverID,omitempty"`
	SessionID     string                 `protobuf:"bytes,3,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comm) Reset() {
	*x = Comm{}
	mi := &file_cspb_comm_struct_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comm) ProtoMessage() {}

func (x *Comm) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_comm_struct_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comm.ProtoReflect.Descriptor instead.
func (*Comm) Descriptor() ([]byte, []int) {
	return file_cspb_comm_struct_proto_rawDescGZIP(), []int{0}
}

func (x *Comm) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *Comm) GetServerID() uint32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *Comm) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type TypIDVal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Typ           string                 `protobuf:"bytes,1,opt,name=typ,proto3" json:"typ,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Val           int64                  `protobuf:"varint,3,opt,name=val,proto3" json:"val,omitempty"`
	Pro           int32                  `protobuf:"varint,4,opt,name=pro,proto3" json:"pro,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypIDVal) Reset() {
	*x = TypIDVal{}
	mi := &file_cspb_comm_struct_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypIDVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypIDVal) ProtoMessage() {}

func (x *TypIDVal) ProtoReflect() protoreflect.Message {
	mi := &file_cspb_comm_struct_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypIDVal.ProtoReflect.Descriptor instead.
func (*TypIDVal) Descriptor() ([]byte, []int) {
	return file_cspb_comm_struct_proto_rawDescGZIP(), []int{1}
}

func (x *TypIDVal) GetTyp() string {
	if x != nil {
		return x.Typ
	}
	return ""
}

func (x *TypIDVal) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TypIDVal) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

func (x *TypIDVal) GetPro() int32 {
	if x != nil {
		return x.Pro
	}
	return 0
}

var File_cspb_comm_struct_proto protoreflect.FileDescriptor

const file_cspb_comm_struct_proto_rawDesc = "" +
	"\n" +
	"\x16cspb/comm/struct.proto\"R\n" +
	"\x04comm\x12\x10\n" +
	"\x03uID\x18\x01 \x01(\x04R\x03uID\x12\x1a\n" +
	"\bserverID\x18\x02 \x01(\rR\bserverID\x12\x1c\n" +
	"\tsessionID\x18\x03 \x01(\tR\tsessionID\"P\n" +
	"\bTypIDVal\x12\x10\n" +
	"\x03typ\x18\x01 \x01(\tR\x03typ\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x10\n" +
	"\x03val\x18\x03 \x01(\x03R\x03val\x12\x10\n" +
	"\x03pro\x18\x04 \x01(\x05R\x03proB*Z(github.com/gogu-x/gogs/pb/cspb/pb_commonb\x06proto3"

var (
	file_cspb_comm_struct_proto_rawDescOnce sync.Once
	file_cspb_comm_struct_proto_rawDescData []byte
)

func file_cspb_comm_struct_proto_rawDescGZIP() []byte {
	file_cspb_comm_struct_proto_rawDescOnce.Do(func() {
		file_cspb_comm_struct_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cspb_comm_struct_proto_rawDesc), len(file_cspb_comm_struct_proto_rawDesc)))
	})
	return file_cspb_comm_struct_proto_rawDescData
}

var file_cspb_comm_struct_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cspb_comm_struct_proto_goTypes = []any{
	(*Comm)(nil),     // 0: comm
	(*TypIDVal)(nil), // 1: TypIDVal
}
var file_cspb_comm_struct_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cspb_comm_struct_proto_init() }
func file_cspb_comm_struct_proto_init() {
	if File_cspb_comm_struct_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cspb_comm_struct_proto_rawDesc), len(file_cspb_comm_struct_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cspb_comm_struct_proto_goTypes,
		DependencyIndexes: file_cspb_comm_struct_proto_depIdxs,
		MessageInfos:      file_cspb_comm_struct_proto_msgTypes,
	}.Build()
	File_cspb_comm_struct_proto = out.File
	file_cspb_comm_struct_proto_goTypes = nil
	file_cspb_comm_struct_proto_depIdxs = nil
}
