// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: common/error.proto

package protoCommon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_OK                    ErrCode = 0
	ErrCode_ERR_UNKNOWN           ErrCode = -1
	ErrCode_ERR_PARAM             ErrCode = -2
	ErrCode_ERR_UNAUTHORIZED      ErrCode = -1001
	ErrCode_ERR_LOGIN_IN_PROGRESS ErrCode = -1002
	ErrCode_ERR_SERVER_NOT_FOUND  ErrCode = -1003
	ErrCode_ERR_USERNAME_EXISTS   ErrCode = -2001
	ErrCode_ERR_WRONG_PASSWORD    ErrCode = -2002
	ErrCode_ERR_INTERNAL          ErrCode = -2003
	ErrCode_ERR_GUILD_EXISTS      ErrCode = -3001
	ErrCode_ERR_GUILD_NOT_FOUND   ErrCode = -3002
	ErrCode_ERR_ALREADY_IN_GUILD  ErrCode = -3003
	ErrCode_ERR_NOT_IN_GUILD      ErrCode = -3004
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:     "OK",
		-1:    "ERR_UNKNOWN",
		-2:    "ERR_PARAM",
		-1001: "ERR_UNAUTHORIZED",
		-1002: "ERR_LOGIN_IN_PROGRESS",
		-1003: "ERR_SERVER_NOT_FOUND",
		-2001: "ERR_USERNAME_EXISTS",
		-2002: "ERR_WRONG_PASSWORD",
		-2003: "ERR_INTERNAL",
		-3001: "ERR_GUILD_EXISTS",
		-3002: "ERR_GUILD_NOT_FOUND",
		-3003: "ERR_ALREADY_IN_GUILD",
		-3004: "ERR_NOT_IN_GUILD",
	}
	ErrCode_value = map[string]int32{
		"OK":                    0,
		"ERR_UNKNOWN":           -1,
		"ERR_PARAM":             -2,
		"ERR_UNAUTHORIZED":      -1001,
		"ERR_LOGIN_IN_PROGRESS": -1002,
		"ERR_SERVER_NOT_FOUND":  -1003,
		"ERR_USERNAME_EXISTS":   -2001,
		"ERR_WRONG_PASSWORD":    -2002,
		"ERR_INTERNAL":          -2003,
		"ERR_GUILD_EXISTS":      -3001,
		"ERR_GUILD_NOT_FOUND":   -3002,
		"ERR_ALREADY_IN_GUILD":  -3003,
		"ERR_NOT_IN_GUILD":      -3004,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_error_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_common_error_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_common_error_proto_rawDescGZIP(), []int{0}
}

var File_common_error_proto protoreflect.FileDescriptor

const file_common_error_proto_rawDesc = "" +
	"\n" +
	"\x12common/error.proto*\x8a\x03\n" +
	"\aErrCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\x18\n" +
	"\vERR_UNKNOWN\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x16\n" +
	"\tERR_PARAM\x10\xfe\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1d\n" +
	"\x10ERR_UNAUTHORIZED\x10\x97\xf8\xff\xff\xff\xff\xff\xff\xff\x01\x12\"\n" +
	"\x15ERR_LOGIN_IN_PROGRESS\x10\x96\xf8\xff\xff\xff\xff\xff\xff\xff\x01\x12!\n" +
	"\x14ERR_SERVER_NOT_FOUND\x10\x95\xf8\xff\xff\xff\xff\xff\xff\xff\x01\x12 \n" +
	"\x13ERR_USERNAME_EXISTS\x10\xaf\xf0\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1f\n" +
	"\x12ERR_WRONG_PASSWORD\x10\xae\xf0\xff\xff\xff\xff\xff\xff\xff\x01\x12\x19\n" +
	"\fERR_INTERNAL\x10\xad\xf0\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1d\n" +
	"\x10ERR_GUILD_EXISTS\x10\xc7\xe8\xff\xff\xff\xff\xff\xff\xff\x01\x12 \n" +
	"\x13ERR_GUILD_NOT_FOUND\x10\xc6\xe8\xff\xff\xff\xff\xff\xff\xff\x01\x12!\n" +
	"\x14ERR_ALREADY_IN_GUILD\x10\xc5\xe8\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1d\n" +
	"\x10ERR_NOT_IN_GUILD\x10\xc4\xe8\xff\xff\xff\xff\xff\xff\xff\x01B'Z%github.com/gogu-x/gogs/pb/protoCommonb\x06proto3"

var (
	file_common_error_proto_rawDescOnce sync.Once
	file_common_error_proto_rawDescData []byte
)

func file_common_error_proto_rawDescGZIP() []byte {
	file_common_error_proto_rawDescOnce.Do(func() {
		file_common_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_error_proto_rawDesc), len(file_common_error_proto_rawDesc)))
	})
	return file_common_error_proto_rawDescData
}

var file_common_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_error_proto_goTypes = []any{
	(ErrCode)(0), // 0: ErrCode
}
var file_common_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_error_proto_init() }
func file_common_error_proto_init() {
	if File_common_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_error_proto_rawDesc), len(file_common_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_error_proto_goTypes,
		DependencyIndexes: file_common_error_proto_depIdxs,
		EnumInfos:         file_common_error_proto_enumTypes,
	}.Build()
	File_common_error_proto = out.File
	file_common_error_proto_goTypes = nil
	file_common_error_proto_depIdxs = nil
}
