// Code generated by deepcopy-gen. DO NOT EDIT.

package role

// DeepCopy 返回 Mgr 的独立副本。
func (in *Mgr) DeepCopy() *Mgr {
	if in == nil {
		return nil
	}
	out := *in
	out.Character = in.Character.DeepCopy()
	return &out
}

// DeepCopy 返回 Role 的独立副本。
func (in *Role) DeepCopy() *Role {
	if in == nil {
		return nil
	}
	out := *in
	if in.Skills != nil {
		out.Skills = make([]Skill, len(in.Skills))
		for index1, item2 := range in.Skills {
			var cloned3 Skill
			cloned3 = *(&item2).DeepCopy()
			out.Skills[index1] = cloned3
		}
	}
	if in.EquipmentIDs != nil {
		out.EquipmentIDs = make([]string, len(in.EquipmentIDs))
		for index4, item5 := range in.EquipmentIDs {
			var cloned6 string
			cloned6 = item5
			out.EquipmentIDs[index4] = cloned6
		}
	}
	return &out
}

// DeepCopy 返回 Skill 的独立副本。
func (in *Skill) DeepCopy() *Skill {
	if in == nil {
		return nil
	}
	out := *in
	return &out
}
