// Code generated by gen-register.py. DO NOT EDIT.
package codec

import (
	protoActivity "github.com/gogu-x/gogs/pb/protoActivity"
	protoChat "github.com/gogu-x/gogs/pb/protoChat"
	protoGateway "github.com/gogu-x/gogs/pb/protoGateway"
	protoGuild "github.com/gogu-x/gogs/pb/protoGuild"
)

func init() {
	RegisterMsg(
		&protoActivity.GetActivityListResp{},
		&protoActivity.JoinActivityResp{},
		&protoActivity.GetProgressResp{},
		&protoActivity.ClaimRewardResp{},
		&protoActivity.ActivityInfo{},
		&protoActivity.ActivityProgress{},
		&protoActivity.GetActivityListReq{},
		&protoActivity.JoinActivityReq{},
		&protoActivity.GetProgressReq{},
		&protoActivity.ClaimRewardReq{},
		&protoChat.ChatAck{},
		&protoChat.ChatReq{},
		&protoGateway.LoginResp{},
		&protoGateway.Frame{},
		&protoGateway.LoginReq{},
		&protoGateway.LogoutReq{},
		&protoGuild.CreateGuildResp{},
		&protoGuild.JoinGuildResp{},
		&protoGuild.LeaveGuildResp{},
		&protoGuild.GetGuildResp{},
		&protoGuild.GuildMember{},
		&protoGuild.GuildInfo{},
		&protoGuild.CreateGuildReq{},
		&protoGuild.JoinGuildReq{},
		&protoGuild.LeaveGuildReq{},
		&protoGuild.GetGuildReq{},
	)
}
