// Code generated by deepcopy-gen. DO NOT EDIT.

package asset

// DeepCopy 返回 Mgr 的独立副本。
func (in *Mgr) DeepCopy() *Mgr {
	if in == nil {
		return nil
	}
	out := *in
	if in.Assets != nil {
		out.Assets = make(map[uint64]int64, len(in.Assets))
		for key1, value2 := range in.Assets {
			var cloned3 int64
			cloned3 = value2
			out.Assets[key1] = cloned3
		}
	}
	return &out
}
