#!/usr/bin/env python3
# gen-register.py <go_out_dir> <proto_dir>
# 生成 pb/pbregister/register.go，只注册 Req/Resp/Ack/Ntf 消息
import sys, re
from pathlib import Path
from collections import defaultdict

go_out    = Path(sys.argv[1]).resolve()
proto_dir = Path(sys.argv[2]).resolve()

groups = defaultdict(list)  # go_package -> [MessageName, ...]

for proto in sorted(proto_dir.rglob("*.proto")):
    content = proto.read_text(encoding="utf-8")
    m = re.search(r'option\s+go_package\s*=\s*"([^"]+)"', content)
    if not m:
        continue
    go_pkg = m.group(1)
    for name in re.findall(r"message\s+(\w+)\s*{", content):
        if name.endswith(("Req", "Resp", "Ack", "Ntf")):
            groups[go_pkg].append(name)

# 过滤无消息的包
groups = {k: v for k, v in groups.items() if v}
if not groups:
    sys.exit("no messages found")

out_path = go_out / "pb" / "pbregister" / "register.go"
out_path.parent.mkdir(parents=True, exist_ok=True)

lines = ["// Code generated by gen-register.py. DO NOT EDIT.\n"]
lines.append("package pbregister\n\n")
lines.append("import (\n")
lines.append('\t"github.com/gogu-x/gogs/codec"\n\n')
for go_pkg in sorted(groups):
    alias = go_pkg.rsplit("/", 1)[-1]
    lines.append(f'\t{alias} "{go_pkg}"\n')
lines.append(")\n\n")
lines.append("func init() {\n")
lines.append("\tcodec.RegisterMsg(\n")
for go_pkg in sorted(groups):
    alias = go_pkg.rsplit("/", 1)[-1]
    for name in groups[go_pkg]:
        lines.append(f"\t\t&{alias}.{name}{{}},\n")
lines.append("\t)\n}\n")

out_path.write_text("".join(lines), encoding="utf-8")
total = sum(len(v) for v in groups.values())
print(f"generated {out_path} ({total} messages, {len(groups)} packages)")
