#!/usr/bin/env python3
"""Generate Go configuration structures from planner TSV/JSON metadata.

Usage: gen-conf.py <output_dir> <config_path>
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import jinja2

from config_source import (
    DATA_TYPES,
    GO_IDENTIFIER,
    ConfigError,
    ensure_identifier,
    read_config,
    source_files,
)
from config_templates import (
    get_registry_template,
    get_runtime_template,
    get_table_template,
)

PACKAGE_PATHS = {
    "cspb": "github.com/gogu-x/gogs/pb/cspb",
}
LOCAL_CUSTOM_TYPES = {
    ("cspb", "TypIDVal"): "TypIDVal",
}
SPECIAL_KEY_TYPES = {
    "D2ConfigCfg": "string",
    "UnlockConfigCfg": "string",
}
NUMBERED_TABLE = re.compile(r"^(\w+Cfg)_\d+$")
GENERATED_PREFIX = "// Code generated by gen-conf.py. DO NOT EDIT.\n"


def field_type(
    raw_type: str,
    parameter: str,
    packages: list[str],
    table_name: str,
    field_name: str,
) -> str:
    raw_type = raw_type.strip()
    parameter = parameter.strip()
    is_slice = raw_type.endswith("[]")
    base_type = raw_type[:-2] if is_slice else raw_type
    prefix = "[]" if is_slice else ""

    if base_type in DATA_TYPES and (not parameter or "index" in parameter):
        return prefix + DATA_TYPES[base_type]
    if not parameter:
        raise ConfigError(
            f"{table_name}.{field_name}: custom type {raw_type!r} requires a parameter"
        )

    parts = parameter.split("_")
    go_type = prefix
    if len(parts) > 1 and parts[1] == "P":
        go_type += "*"
    if len(parts) == 3:
        package_alias = parts[2]
        local_type = LOCAL_CUSTOM_TYPES.get((package_alias, parts[0]))
        if local_type is not None:
            return go_type + local_type
        package_path = PACKAGE_PATHS.get(package_alias)
        if package_path is None:
            raise ConfigError(
                f"{table_name}.{field_name}: unknown package alias {package_alias!r}"
            )
        if package_path not in packages:
            packages.append(package_path)
        go_type += package_alias + "."
    go_type += ensure_identifier(parts[0], f"{table_name}.{field_name} type")
    return go_type


def template_values(
    fields: dict[str, Any],
    table_name: str,
) -> tuple[list[str], list[list[str]]]:
    packages = ["sync/atomic"]
    values: list[list[str]] = []
    columns = zip(
        fields["domain"],
        fields["type"],
        fields["uppername"],
        fields["lowername"],
        fields["param"],
        fields["comment"],
    )
    for domain, raw_type, upper, lower, parameter, comment in columns:
        if "s" not in domain.lower():
            continue
        upper = ensure_identifier(upper, f"{table_name} field")
        lower = lower.strip()
        go_type = field_type(raw_type, parameter, packages, table_name, upper)
        bson_name = lower
        if "float" in go_type:
            bson_name += ",truncate"
        elif "index" in parameter:
            bson_name += '\" index:\"'
        if table_name in SPECIAL_KEY_TYPES and lower == "constant":
            bson_name += '\" selection:\"_'
        values.append([upper, go_type, bson_name, comment.strip() or "配置字段"])
    return packages, values


def output_name(table_name: str) -> str:
    name = table_name[:-3] if table_name.endswith("Cfg") else table_name
    return f"conf_{name.lower()}.go"


def render_table(output_dir: Path, fields: dict[str, Any]) -> str | None:
    source_name = ensure_identifier(fields["tablename"], "table")
    match = NUMBERED_TABLE.fullmatch(source_name)
    table_name = match.group(1) if match else source_name
    packages, values = template_values(fields, table_name)
    if not values:
        print(f"skip {source_name}: no server fields")
        return None

    key_type = SPECIAL_KEY_TYPES.get(table_name, "int32")
    key_arg = "key string" if key_type == "string" else "id int32"
    getter = "Get0(key)" if key_type == "string" else "Get(id)"
    rendered = jinja2.Template(get_table_template(key_type)).render(
        package_name=output_dir.name,
        struct_name=table_name,
        value_list=values,
        packages=packages,
        key_arg=key_arg,
        getter=getter,
    )
    destination = output_dir / output_name(table_name)
    destination.write_text(GENERATED_PREFIX + rendered.lstrip(), encoding="utf-8")
    print(f"generated {destination}")
    return table_name


def remove_stale_outputs(output_dir: Path) -> None:
    for path in output_dir.glob("conf_*.go"):
        try:
            first_line = path.open("r", encoding="utf-8").readline()
        except OSError:
            continue
        if first_line == GENERATED_PREFIX:
            path.unlink()
    for name in ("confs.go", "runtime.go"):
        path = output_dir / name
        if path.exists() and path.open("r", encoding="utf-8").readline() == GENERATED_PREFIX:
            path.unlink()


def render_registry(output_dir: Path, names: list[str]) -> Path:
    rendered = jinja2.Template(get_registry_template()).render(
        package_name=output_dir.name,
        names=sorted(set(names)),
    )
    destination = output_dir / "confs.go"
    destination.write_text(GENERATED_PREFIX + rendered.lstrip(), encoding="utf-8")
    return destination


def render_runtime(output_dir: Path) -> Path:
    rendered = jinja2.Template(get_runtime_template()).render(
        package_name=output_dir.name,
    )
    destination = output_dir / "runtime.go"
    destination.write_text(GENERATED_PREFIX + rendered.lstrip(), encoding="utf-8")
    return destination


def run_gofmt(paths: list[Path]) -> None:
    gofmt = shutil.which("gofmt")
    if gofmt is None:
        print("warning: gofmt not found; generated files were not formatted", file=sys.stderr)
        return
    subprocess.run([gofmt, "-w", *(str(path) for path in paths)], check=True)


def generate(output_dir: Path, config_path: Path) -> None:
    if not config_path.is_dir():
        raise ConfigError(f"config path is not a directory: {config_path}")
    output_dir.mkdir(parents=True, exist_ok=True)
    if not GO_IDENTIFIER.fullmatch(output_dir.name):
        raise ConfigError(f"output directory must be a valid Go package name: {output_dir.name}")

    remove_stale_outputs(output_dir)
    generated_names: list[str] = []
    generated_paths: list[Path] = []
    for path in source_files(config_path):
        table_name = render_table(output_dir, read_config(path))
        if table_name is not None and table_name not in generated_names:
            generated_names.append(table_name)
            generated_paths.append(output_dir / output_name(table_name))

    registry = render_registry(output_dir, generated_names)
    runtime = render_runtime(output_dir)
    run_gofmt([*generated_paths, registry, runtime])
    print(f"generated {len(generated_names)} configuration types in {output_dir}")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Go configuration structures from planner metadata."
    )
    parser.add_argument("output_dir", type=Path)
    parser.add_argument("config_path", type=Path)
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv[1:])
    try:
        generate(args.output_dir.resolve(), args.config_path.resolve())
    except (ConfigError, OSError) as error:
        print(f"gen-conf: {error}", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as error:
        print(f"gen-conf: gofmt failed with exit code {error.returncode}", file=sys.stderr)
        return error.returncode
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
