// Code generated by gen-register.py. DO NOT EDIT.
package pbregister

import (
	"github.com/gogu-x/tree/codec"

	pb_activity "github.com/gogu-x/gogs/pb/cspb/pb_activity"
	pb_auth "github.com/gogu-x/gogs/pb/cspb/pb_auth"
	pb_battle "github.com/gogu-x/gogs/pb/cspb/pb_battle"
	pb_chat "github.com/gogu-x/gogs/pb/cspb/pb_chat"
	pb_gateway "github.com/gogu-x/gogs/pb/cspb/pb_gateway"
	pb_guild "github.com/gogu-x/gogs/pb/cspb/pb_guild"
	pb_pf "github.com/gogu-x/gogs/pb/pfpb/pb_pf"
	sspb "github.com/gogu-x/gogs/pb/sspb"
)

func init() {
	codec.RegisterMsg(
		&pb_activity.GetActivityListAck{},
		&pb_activity.JoinActivityAck{},
		&pb_activity.GetProgressAck{},
		&pb_activity.ClaimRewardAck{},
		&pb_activity.GetActivityListReq{},
		&pb_activity.JoinActivityReq{},
		&pb_activity.GetProgressReq{},
		&pb_activity.ClaimRewardReq{},
		&pb_auth.LoginGameAck{},
		&pb_auth.LoginGameReq{},
		&pb_battle.StartBattleAck{},
		&pb_battle.StartBattleReq{},
		&pb_battle.BattleCreatedNtf{},
		&pb_battle.BattleActionNtf{},
		&pb_battle.BattleFinishedNtf{},
		&pb_battle.BattleResultConfirmedNtf{},
		&pb_chat.ChatAck{},
		&pb_chat.ChatReq{},
		&pb_gateway.LoginAck{},
		&pb_gateway.RegisterAck{},
		&pb_gateway.ServerListAck{},
		&pb_gateway.LoginReq{},
		&pb_gateway.RegisterReq{},
		&pb_gateway.LogoutReq{},
		&pb_gateway.GetServerListReq{},
		&pb_guild.CreateGuildAck{},
		&pb_guild.JoinGuildAck{},
		&pb_guild.LeaveGuildAck{},
		&pb_guild.GetGuildAck{},
		&pb_guild.CreateGuildReq{},
		&pb_guild.JoinGuildReq{},
		&pb_guild.LeaveGuildReq{},
		&pb_guild.GetGuildReq{},
		&pb_pf.RegisterReq{},
		&pb_pf.AuthLoginReq{},
		&pb_pf.AuthAck{},
		&pb_pf.VerifyTokenReq{},
		&pb_pf.VerifyAck{},
		&pb_pf.GetServerListReq{},
		&pb_pf.ServerListAck{},
		&pb_pf.CreateOrderReq{},
		&pb_pf.OrderAck{},
		&pb_pf.QueryOrderReq{},
		&sspb.NatsMsgReq{},
		&sspb.NatsMsgAck{},
		&sspb.NatsMsgNtf{},
	)
}
